### ISSUE TITLE
intermittent failure with npm install running lockdown on jenkins box with cb() never called!

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3303] opened 2013-04-24 01:08 UTC
on jenkins run this:
npm install
cd automation-tests
npm install
mkdir results
./scripts/run-all.js --platform win7_firefox_16 --parallel 10 --output xunit --env dev

results:
    For the 63 builds (mac, win linux) i got this 5 times.
    Edwin@ewong-16235:~/github/edmoz/jenkins-cli$ grep -B 3 -irn 'never called' logs/identity.browserid.\* 
    logs/identity.browserid.dev.linux_firefox_16.2089.txt-198-npm http 200 http://127.0.0.1:51174/htmlparser/-/htmlparser-1.7.6.tgz
    logs/identity.browserid.dev.linux_firefox_16.2089.txt-199-npm http 200 http://127.0.0.1:51174/connect-cookie-session/-/connect-cookie-session-0.0.2.tgz
    logs/identity.browserid.dev.linux_firefox_16.2089.txt-200-npm http 200 http://127.0.0.1:51174/connect-logger-statsd/-/connect-logger-statsd-0.0.1.tgz
    logs/identity.browserid.dev.linux_firefox_16.2089.txt:201:npm ERR! cb() never called!
    --
    logs/identity.browserid.dev.win7_firefox_16.2842.txt-198-npm http 200 http://127.0.0.1:45963/which/-/which-1.0.5.tgz
    logs/identity.browserid.dev.win7_firefox_16.2842.txt-199-npm http 200 http://127.0.0.1:45963/htmlparser/-/htmlparser-1.7.6.tgz
    logs/identity.browserid.dev.win7_firefox_16.2842.txt-200-npm http 200 http://127.0.0.1:45963/jshint/-/jshint-0.9.1.tgz
    logs/identity.browserid.dev.win7_firefox_16.2842.txt:201:npm ERR! cb() never called!
    --
    logs/identity.browserid.dev.win7_firefox_16.2851.txt-864-  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
    logs/identity.browserid.dev.win7_firefox_16.2851.txt-865-  COPY Release/iconv.node
    logs/identity.browserid.dev.win7_firefox_16.2851.txt-866-make: Leaving directory `/var/lib/jenkins/jobs/identity.browserid.dev.win7_firefox_16/workspace/node_modules/nodemailer/node_modules/mailcomposer/node_modules/mimelib/node_modules/encoding/node_modules/iconv/build'
    logs/identity.browserid.dev.win7_firefox_16.2851.txt:867:npm ERR! cb() never called!
    --
    logs/identity.browserid.dev.win7_firefox_16.2852.txt-198-npm http 200 http://127.0.0.1:56867/jshint/-/jshint-0.9.1.tgz
    logs/identity.browserid.dev.win7_firefox_16.2852.txt-199-npm http 200 http://127.0.0.1:56867/winston/-/winston-0.6.2.tgz
    logs/identity.browserid.dev.win7_firefox_16.2852.txt-200-npm http 200 http://127.0.0.1:56867/htmlparser/-/htmlparser-1.7.6.tgz
    logs/identity.browserid.dev.win7_firefox_16.2852.txt:201:npm ERR! cb() never called!
    --
    logs/identity.browserid.dev.win7_firefox_16.2860.txt-844-  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
    logs/identity.browserid.dev.win7_firefox_16.2860.txt-845-  COPY Release/iconv.node
    logs/identity.browserid.dev.win7_firefox_16.2860.txt-846-make: Leaving directory`/var/lib/jenkins/jobs/identity.browserid.dev.win7_firefox_16/workspace/node_modules/nodemailer/node_modules/mailcomposer/node_modules/mimelib/node_modules/encoding/node_modules/iconv/build'
    logs/identity.browserid.dev.win7_firefox_16.2860.txt:847:npm ERR! cb() never called!

**Comment by jrgm** [comment] 2013-04-24 07:12
Good find. I did some poking around with https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.osx_safari_5/configure to see some things I was interested in (I can remove those later).

Anyways, on the jenkins server, all jobs run as the same user on whatever schedule those jobs run. Since they are the same $HOME then npm will be using the same ~/.npm. On the jenkins box there are browserid jobs and other projects that use node.js. The browserid jobs use `npm-lockdown` which will need to share `/tmp/.npm` as that user if jobs run concurrently.

I set up an awsbox to just loop over the npm install with a clean clone. That works fine for two users running that task at the same time. However, if I interrupt one task in the middle, the other task sometimes reproduces the `npm ERR! cb() never called!`. 

I don't know where the real bug is (npm or lockdown). But we should configure the Jenkins jobs to use isolated per-job locations for the equivalent of $HOME/.npm and $TMPDIR/.npm.

**Comment by callahad** [comment] 2013-04-25 17:16
@jrgm "This is a 3 line fix in lockdown so it can have separate cache directories."

**Comment by jrgm** [comment] 2013-04-25 20:02
Actually, it's even better. It's a no line fix. Just need to update the checked in version of lockdown to match the version that we install in ./node_modules.

**Comment by jrgm** [comment] 2013-04-25 21:15
And there is already a PR for doing that update - https://github.com/mozilla/browserid/pull/3255

After that happens, jenkins builds on ci.mozilla.org can add:

```
export npm_config_cache=$HOME/.npm-some-name-unique-to-this-job
export npm_config_tmp=/tmp/.npm-some-name-unique-to-this-job
```

and that will eliminate competition from any other jenkins jobs.

**Comment by jaredhirsch** [comment] 2013-07-02 20:29
Closing, this problem was fixed in lockdown & is fixed on Jenkins (Jenkins is currently failing because we need to update the platform name in the tests :-P)

**Comment by jrgm** [comment] 2013-07-02 20:38
@6a68 - actually, it wasn't fixed in browserid, which uses scripts/lockdown and not the script from the installed lockdown (for good reason). And scripts/lockdown does not pass down the full environment, so no overriding `npm_*` environment variables in the child is possible.

**Comment by seanmonstar** [comment] 2013-07-02 21:03
yea, to fix this:

`cp ./node_modules/lockdown/lockdown.js ./scripts/lockdown.js`

Even better, I'd rather us change our lockdown dependency to point at our mozilla gitmirror, and then not have to do this ever.

**Comment by callahad** [comment] 2014-10-31 19:52
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:52 UTC
Labels: ★★★★, cleanup-2014
