### ISSUE TITLE
New users unable to sign in after creating a new account

### ISSUE THREAD

**Issue by karlpauls** [mozilla/persona#3950] opened 2013-10-04 08:34 UTC
We are experiencing a very bad situation with persona atm namely, some new users are unable to log in which is unacceptable (they might never come back). 

I managed to witness one of these failed attempts and this is how it happens:
- The user is running windows7 and downloads the latest version of firefox. 
- Next, she goes to our web app and hits sign in. 
  - The normal browserid window kicks in and she gives her email (which is not yet a browserid and not one of the special ones as gmail/yahoo/etc.). 
    hence, she gets told to check her mail to create the account. 
  - Now, she clicks the link in her email which opens a new tab in firefox and she sets up browserid. 
  - When she is done, she closes that tab and is back to the other tab which is our webapp.
- Upon trying to sign in again, she gives her email and her just set-up password.
  The browserid page tells her there is an Error and she should close the page.

![browserid_bug](https://f.cloud.github.com/assets/410610/1267825/490e09de-2ccd-11e3-80cf-40a6220ec527.png) 
- After waiting a day and trying again it still does say that - neither closing firefox, rebooting windows, etc. helps. So, i told her how to nuke her history and cache in firefox and after that, it works -- hence, im guessing something in this workflow messes something up in the local storage which prevents a normal sign in. 

For us, this is a pretty bad situation as we don't get any feedback if that happens and we might be losing new users due to this.

**Comment by callahad** [comment] 2013-10-04 08:53
Are you able to reproduce the issue? Does she have any addons installed?

**Comment by karlpauls** [comment] 2013-10-04 09:42
I am trying but I can not reproduce it on my mac. I have no windows around atm. 

Regarding the addons, it was a vanilla install of firefox which she just downloaded. I think she did tell it to import setting from her IE during installation but otherwise, it was a vanilla installation.

**Comment by karlpauls** [comment] 2013-10-04 09:48
I guess the one difference i can see between what happened for her and what happens on my mac is the following:

When i try to use a new email, i have to give a password and then get told that there is an email send. If I click the link inside that email, it opens a new tab in firefox and redirects me to our webapp directly (and I am signed in with the new email correctly). 

When she did this, it did open a new tab as well but it showed a page at mozilla which asked her to setup a password again and ultimately told her that the set-up of persona was successful but it didn't redirect her to our web app. 

Maybe that second flow is what caused the problem...

**Comment by callahad** [comment] 2013-10-04 11:20
Ah! That's interesting. It sounds like she may have opened the confirmation link in another browser?

This is the first report I've seen of this issue. I'll look more closely at that code path later tonight.

I'm terribly sorry this is happening to your users. If you can manage to reproduce the issue, that would help us immensely.

**Comment by csuciu** [comment] 2013-10-04 11:38
I'm able to reproduce this issue on Win7 & Firefox 24 (release) using the production env.

Here are the steps:
1.  go to 123done.org and sign in
2.  enter an email address (new to persona) - I used a secondary email
3.  enter the password (create/verify) and press on 'Done'

Issue 1: the sign in dialog pops up again and requests for password to sign is
1. go to the email client and click the confirmation link
2. https://login.persona.org/verify_email_address...... opens in a new tab and requests for password

Issue 2: after confirming the password the user is not automatically signed in. Any subsequent attempts to sing in using this email will fail with the above message

**Comment by karlpauls** [comment] 2013-10-04 11:42
Ok good. I did try various scenarios on my mac including chrome, safari, and firefox and can't reproduce this issue. It seems to be related to the Win7 & Firefox 24 scenario.

Needless to say, i hope this gets fixed asap :-)

**Comment by csuciu** [comment] 2013-10-04 12:15
I can reproduce on stage env also.
On both env, the issue is reproducible only if the IE settings are imported during Firefox installation.

**Comment by karlpauls** [comment] 2013-10-04 12:23
Ah, ok - that explains why I can't reproduce it. Importing the IE settings is the key.

**Comment by callahad** [comment] 2013-10-04 13:07
Hm. Unable to reproduce on a fresh Win 8 / IE 10 / Fx 24 VM. I don't have Win 7 handy, but I'll try to download a VM soon.

**Comment by karlpauls** [comment] 2013-10-04 13:09
Don't forget that apparently you have to import the IE settings on firefox install. This seems to be the key to make this issue appear.

**Comment by callahad** [comment] 2013-10-04 13:09
I did :)

**Comment by karlpauls** [comment] 2013-10-04 13:24
Ok. The only other component that might play a role is that she used outlook to open the mail and click the link. 

@csuciu did you use outlook as well or have you been using a different mail program?

**Comment by csuciu** [comment] 2013-10-04 13:25
I can't reproduce either on Win 8/ Firefox 24/IE10 (VM)

**Comment by csuciu** [comment] 2013-10-04 13:28
@karlpauls I used  Thunderbird.

**Comment by karlpauls** [comment] 2013-10-04 13:30
Ok. So we have it down to win7 & firefox24 with importing settings from IE.

**Comment by karlpauls** [comment] 2013-10-09 21:35
Any news on this one?
@callahad, did you manage to reproduce the issue as well?

**Comment by callahad** [comment] 2014-10-31 19:50
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:50 UTC
Labels: ★★★★, cleanup-2014
