### ISSUE TITLE
Sign up doesn't fail gracefully?

### ISSUE THREAD

**Issue by savs** [mozilla/persona#2513] opened 2012-09-22 13:44 UTC
On https://developer.mozilla.org/en-US/docs/Mozilla/Boot_to_Gecko/B2G_build_prerequisites
Click Edit.
Get "Sign In with Persona" page.
Click "Sign In". Get pop-up window "developer.mozilla.org uses Persona".
Enter email address. Click next. Results in a blank screen.

Second time around, with a different email address, resulted in "checking with your email provider" followed by "your email is new to us". It looks like the email check suffered connectivity issues.

Clicking on the email verification link, the first time around resulted in a blank page. The second time with a different email resulted in the "Thank you for signing up with Persona".

**Comment by shane-tomlinson** [comment] 2012-09-24 10:33
@savs - Thanks for the report! can you leave more information on which browser/OS combination you are using? I just able to complete the new user flow twice in Firefox 15.01 on OSX.

When you say "Enter email address. Click next. Results in a blank screen.", is that a blank screen in the dialog or on the persona site once you click on the link in the email?

Later on you comment "Clicking on the email verification link, the first time around resulted in a blank page." Is this a second blank page or the same as the first?

**Comment by savs** [comment] 2012-09-24 11:01
I'm testing using Safari 6.0.1 on OS X Mountain Lion.

The blank screen was the Persona site but without the flash in the middle – so looks like the js did not complete properly.

(By 'flash' I mean the transient/ajax information, not an adobe plugin!)

The email verification was a second blank page – clicking on the link in the email opened up a Persona page as before, and as before the flash in the middle did not appear, suggesting js fail somewhere along the line.

I haven't been able to duplicate this again, so it may just have been some temporary connectivity issues between the client-side js and the server (assuming that's how it's written).

**Comment by shane-tomlinson** [comment] 2012-12-10 12:27
@savs - I am going to close this since neither of us are able to reproduce. If you see this again, please re-open this issue. Thanks for the report!

**Closed as completed by shane-tomlinson** 2012-12-10 12:27 UTC
Labels: ★★★★, qa:verified, area:dialog
