### ISSUE TITLE
No emails in email-picker view

### ISSUE THREAD

**Issue by nmalkin** [mozilla/persona#2493] opened 2012-09-17 03:52 UTC
#### Symptom

![screenshot of email picker with no emails](http://f.cl.ly/items/3j1M2W3d0x3T1W3z2H1y/no-emails.png)
#### STR

Okay, so I haven't tried to reproduce this, but here's what I think happened:
1. Sign in to a site with new, secondary email address
2. Attempt to log in using same email address in a different browser, with an active Persona session
3. Email isn't associated with that account, so go through email verification again
4. Email gets associated with new account, is removed from old account (my guess)
5. Attempt sign-in with original browser (Persona session still active)
6. See screen above
#### Further symptoms
- Clicking "sign in" yields an alert with the message, "The selected email is invalid or has been deleted."
- The same screen appears if the dialog is closed and then re-opened
- Opening login.persona.org briefly flashes the account manager, then shows empty screen:
  ![empty screen on login.persona.org](http://f.cl.ly/items/282Y3B133S1g091X3M0h/empty-account-manager.png)
#### P.S.

This is on the production Persona instance. I vaguely remember seeing something similar in a bug before — maybe it's been fixed?

**Comment by seanmonstar** [comment] 2012-09-17 23:16
This may be related #1472, but I see the STR are a little different.

**Comment by nmalkin** [comment] 2012-09-18 01:31
Yeah, they do look similar. I think the root cause is the same.

**Comment by seanmonstar** [comment] 2012-09-18 02:14
I have a suspicion that #1472 was fixed by destroying all session when password changed, since I can't reproduce on dev/stage. Are you able to get this to happen on dev/stage?

**Comment by nmalkin** [comment] 2012-09-18 02:20
Just reproduced this on dev using the exact STR from my original post:
![still no emails, now on dev](http://f.cl.ly/items/340r2d3J042Z2A1J2I3D/still_no_emails.png)

**Comment by nmalkin** [comment] 2012-09-18 02:26
Specifically, here's what I did:
1. In Chrome, sign into [dev.]123done with (new, secondary) email address A
2. In Firefox, sign into 123done with (new, secondary) email address B
3. In Firefox, sign out of 123done
4. In Firefox, start to sign back in to 123done
5. When prompted about using email address B, choose to add a new email address
6. Add email address A
7. Still in Firefox, verify email address A and finish signing in
8. In Chrome, sign out of 123done
9. In Chrome, try signing back in to 123done
10. See screen above

**Comment by zaach** [comment] 2012-09-21 18:39
@lloyd suggested removing the user's account when they no longer have any email addresses.

**Comment by jaredhirsch** [comment] 2013-07-02 01:21
Closing--I can no longer repro this. The first browser (Chrome in most recent STR) now correctly shows the merged account. Please reopen if this is still a bug.

**Comment by jrgm** [comment] 2013-07-02 02:00
This _is_ still reproducible in production and dev. When the sign_in dialog comes up after "stealing" the email address to a different account, `session_context` says 

`{"csrf_token":"gmxu47J8+CJ2+vssYe0VqA==","server_time":1372730263346,"authenticated":true,
"auth_level":"password","has_password":true,"domain_key_creation_time":1372719754329,
"random_seed":"HMBxPMQ1ew7x8shHiHCJejqqrqgHF6qRkHVL/QDzEXk=","data_sample_rate":1,
"cookies":true,"userid":31}` 

and `list_emails` says `{"success":true,"emails":[]}`.

**Comment by shane-tomlinson** [comment] 2013-09-19 17:15
Has https://github.com/mozilla/browserid/pull/3820 fixed this?

**Comment by shane-tomlinson** [comment] 2013-09-19 17:15
Link to #1472

**Comment by shane-tomlinson** [comment] 2013-09-19 17:56
I just tested this twice, all good. Closing.

**Closed as completed by shane-tomlinson** 2013-09-19 17:56 UTC
Labels: ★★★★, area:server
