### ISSUE TITLE
onlogout called immediately after onlogin if 3rd party cookies are disabled

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2999] opened 2013-02-08 14:14 UTC
A user reported an oddity today that may affect many Chrome users.

If 3rd party cookies are disabled, onlogout is called immediately after onlogin.

The following test page shows the error.

```
<html>
  <script src="https://login.persona.org/include.js"></script>
<body>
<fieldset>
    <legend>Persona Login</legend>
    <button onclick="login_persona()">Login</button>
</fieldset>
<script>
window.login_persona = (function() {
  navigator.id.watch({
    loggedInUser: null,
    onlogin: function (assertion) {
      console.info ("Checking an assertion from Persona.");
    },
    onlogout: function () {
      console.info ("Persona thinks I am or should be logged out.");
    }
  });

  return function() {
    console.info ("User requested login");
    navigator.id.request();
  }
}());
</script>
</body>
</html>
```

To both users and developers, it appears that Persona is operating as it should until the onlogout function is invoked with no clear indication why.

Instead of leaving users clueless, we should show them how to whitelist the Persona domain.

Relate to:
#982, #989

**Comment by unprolix** [comment] 2013-02-08 22:41
I spent quite some time trying to track this down!

**Comment by jaredhirsch** [comment] 2013-02-14 17:44
@seanmonstar @shane-tomlinson here's an idea for a fix: can we try to set and read back a cookie value, then bail intelligently if the cookie didn't actually get set. sound like a good approach?

**Comment by seanmonstar** [comment] 2013-02-14 18:50
@6a68 we do that https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/network.js#L700

Maybe some path in the code doesn't hit that?

**Comment by jaredhirsch** [comment] 2013-02-21 21:56
Chrome's third-party cookie behavior is a bit more nuanced than Safari's. 

Chrome behaves as expected if you tell it to allow third-party cookies from any Persona **subdomain**, making an exception for `[*.]persona.org`, not just `persona.org`.

Looking more closely at what cookies we set vs whether we test for subdomains or just parent domain.

**Comment by toolness** [comment] 2013-02-21 22:04
> Instead of leaving users clueless, we should show them how to whitelist the Persona domain.

Wait, this doesn't actually seem like an ideal solution... Persona works just fine with the callback API, where the client website is responsible for storing the user's login state, so this seems like a regression, and an inconvenience for users who disable third-party cookies.

Why does Persona need to manage the user's login state? Can the callback API be made to support some of the options that the observer API uses, or is there a way for clients of the Observer API to intentionally opt-out of Persona's management of login state? The only reason mozilla/openbadges#511 needs to support it is so we can direct users from their email to our website instead of persona, which seemingly has nothing to do with third-party cookies.

Another reason I'm concerned about this solution is because it might be the case that certain locked-down systems, such as public library computers, may not even allow users to whitelist domains. (If they [disable View Source](http://www.toolness.com/wp/2011/03/three-lessons-learned-from-hack-jams/), they might as well disable third-party cookies too, but maybe I'm wrong.)

**Comment by toolness** [comment] 2013-02-21 22:10
Also, I'm willing and able to help resolve this bug by contributing to persona, so let me know if there's anything I can do to help!

**Comment by jaredhirsch** [comment] 2013-02-21 22:34
@toolness ordinarily persona does work with third-party cookies disabled. shane's repro page, if loaded on localhost with safari, logs you in without problems. chrome's unique handling of third-party cookies might be an issue here; it's only a guess, and I'm actively investigating. (sidestepping the question of why persona wants to hook into login/logout; we can take that to the dev-identity list or IRC if you want to talk about get vs watch APIs)

**Comment by stenington** [comment] 2013-02-21 22:42
I was running into this onlogout behavior with Firefox 18.

**Comment by jaredhirsch** [comment] 2013-02-21 22:49
hmm. FF18 + chrome don't allow the communication_iframe to touch its localStorage if third-party cookies are disabled.

continuing to dig :-)

**Comment by toolness** [comment] 2013-02-21 22:59
Is it possible for the `communication_iframe` to pass the token back to the parent window for it to store in _its_ `localStorage` instead? That could be done transparently by the `include.js` shim... Not sure how awesome it is security-wise.

**Comment by seanmonstar** [comment] 2013-02-21 23:38
The user's private key is stored in localStorage on persona.org domain, so 1) we don't want to store that in the localStorage of the RP, because then they have our user's keys, and 2) the communication_iframe wouldn't be able to access the key anyways, if localStorage was off.

**Comment by jaredhirsch** [comment] 2013-02-21 23:42
By having persona throw a popup on user click, i.e. in direct response to user action, we avoid third-party cookie restrictions, and safari (and FF nightly, according to @seanmonstar) intelligently detects that the user knows about this domain, and so relaxes the cannot-touch-localStorage rule. FF18 and Chrome are not so clever about distinguishing good and evil third parties.

It looks like we [explicitly decided](https://github.com/mozilla/browserid/blob/dev/resources/static/communication_iframe/start.js#L18-25), a while ago, not to check for storage in the communication_iframe, for the sake of IE compatibility. I suppose we may have to revisit that now, unless I find a simpler fix (maybe our [localStorage stub](https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/storage.js#L12-20) is missing a method that triggers an uncaught exception).

**Comment by jaredhirsch** [comment] 2013-02-22 15:20
I think what's happening is, the dialog does an explicit cookie check, but only on its own domain (checking for localstorage/cookies disabled globally).

This check succeeds.

Later, the communication_iframe does a cookie check deep in the stack, after the user has done the dialog login flow and the dialog is dismissed:

```
// on dialog_complete:
checkAndEmit ({
  getSilentAssertion ({
    checkAuthenticationAndSync ({
      checkAuthentication ({
        network.cookiesEnabled // which fails & returns false
```

I'm currently looking at a couple different ways of adding this check so that the user gets timely warning info in the dialog & expect to have a PR out today. Simplest thing I can think of is to have communication_iframe do a check on startup, right after opening the channel to the parent window, and firing the bad-news signal on page load, before the dialog is opened.

**Comment by toolness** [comment] 2013-02-22 16:38
Awesome, that's great--thanks @6a68 !

**Comment by jaredhirsch** [comment] 2013-02-22 20:34
@toolness think this should be fixed by my PR, expect it'll get attention Monday. arguably we should modify the cookies_disabled screen to warn the user that they have 3rd party cookies disabled

**Comment by jaredhirsch** [comment] 2013-02-27 18:25
@toolness Just to keep you up to speed--this fix requires cross-domain messaging changes that've taken longer than expected and tend to need lots of QA. This is at risk to ship with the next train, but that doesn't rule out a hotfix.

I'll keep this ticket posted as dev continues. Lower-level details are in the PR 3043.

**Comment by cmcavoy** [comment] 2013-03-01 15:20
Just checking in, any chance this can be a hotfix?

**Comment by jaredhirsch** [comment] 2013-03-05 19:38
@cmcavoy I don't think it's going to happen in the next few weeks. This might change, but it's doubtful--we are kinda overcommitted on Q1 goals. I'm bummed; I was hoping to get this done for you guys.

The good news here is that FF users won't have problems, but Chrome users will need to whitelist [*.]persona.org.

And we _will_ finish this off, just not in the timeframe you were hoping for. Owe you a :beer:

**Comment by jaredhirsch** [comment] 2013-03-12 23:27
Update! @lloyd and I went over this bug again today.

Rather than fail the login if third-party cookies are disabled, we can instead fall back gracefully, and simply not manage the user's session. This means that the RP will have to do its own session management for those users; the iframe will always assert the user's logged in.

Working on a patch with this in mind, aim to have a pull request out tomorrow. Should be relatively much simpler.

Related quote from IRC:

```
lloyd|afk       _6a68: just to close, I'm thinking telling the user they could log in less
frequently by adding an exception might be higher value than notifying the RP.  as far as
notifying the RP the best thing I can think of is a short suggested session duration in
assertion.          4:11
lloyd|afk       _6a68: given that this is a privacy concious user, the assumption is
that more frequent logins is a price they're willing to pay.            4:12
```

**Comment by toolness** [comment] 2013-03-14 04:23
Awesome, @6a68! Thanks for your work on this.

**Comment by shane-tomlinson** [comment] 2013-03-14 08:25
> This means that the RP will have to do its own session management for those users; the iframe will always assert the user's logged in.

@6a68 - do you mean to say the iframe will always assert the user is logged in or logged out? If logged in, what assertion will it pass back to the RP?

**Comment by jaredhirsch** [comment] 2013-03-14 09:19
@shane-tomlinson I'm thinking we just fire onmatch no matter what

**Comment by jaredhirsch** [comment] 2013-03-14 10:06
@shane-tomlinson maybe something like this? https://github.com/mozilla/browserid/pull/3101

You know, it's really a bit of a bummer that `navigator.cookieEnabled` doesn't tell the truth in the third-party frame context in FF (returns true even if cookies can't be set).

**Comment by shane-tomlinson** [comment] 2013-04-02 11:11
Link to #1903, #1835, #982, #989, #2575

**Comment by jaredhirsch** [comment] 2013-04-04 16:56
link to #3169

**Comment by callahad** [comment] 2013-04-04 20:19
Workaround for users: Add a third party cookie exception for `[*.]persona.org`

**Comment by jaredhirsch** [comment] 2013-04-04 20:56
Actually, depends on the browser. [*.]persona.org for chrome, but I think
persona.org is good enough for FF.

**Closed as completed** 2013-04-16 19:31 UTC
Labels: ★★★★
