### ISSUE TITLE
Google Revocation Bug

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/persona#3918] opened 2013-09-25 21:29 UTC
Just experienced this on 123done.org as I wanted to get fresh screenshots of Google's Request Permission dialog:
I revoked access to all persona.org related domains
I signed out of Gmail
I then signed into 123done.org with my Gmail address
I was immediately signed in to 123done
My old list showed "null" instead of the items
The 123done window closed after 10 seconds on its own
And now when I go back to 123done, I am signed in, but my list data is gone
I am able to get 2-click sign in to 123done while being signed out of Gmail

**Comment by edwindotcom** [comment] 2013-09-26 17:02
I'll work on repro'ing this today

**Comment by shane-tomlinson** [comment] 2013-09-26 17:02
This may be a bug with 123done, but placing at 4\* to investigate.

**Comment by callahad** [comment] 2013-09-27 07:55
The "null" list sounds like a 123done bug. I suggest opening a new bug in that repo.

The "can still sign in after logging out of Google" thing is by design -- sideshow respects the client's requested cert duration, so the user still has a valid identity certificate for a short while after signing out of Google. If that's the issue, I suggest filing a new bug in the Sideshow repo requesting shorter cert durations.

@seanmonstar -- care to weigh in on Sideshow cert durations?

**Comment by callahad** [comment] 2013-09-27 07:56
Closing as this specific bug appears unrelated to the mozilla/browserid repo.

**Closed as completed by callahad** 2013-09-27 07:56 UTC
Labels: ★★★★
