### ISSUE TITLE
UI buttons cannot be used if you add too many emails

### ISSUE THREAD

**Issue by klrmn** [mozilla/persona#2463] opened 2012-09-11 23:03 UTC
After adding 8 email addresses via the pop-up, the sign-in button is now half hidden. I expect that if I add 1-3 more, all of the buttons will be hidden.

http://imgur.com/zjMFn

**Comment by callahad** [comment] 2012-09-11 23:06
Closing as a dupe of #2399 -- should be resolved as of pull request #2422

Thanks, @klrmn!

**Closed as completed by callahad** 2012-09-11 23:06 UTC
Labels: qa:verified
