### ISSUE TITLE
clicking 'sign up' on anosrep.org goes to 'sign in' page, not 'create acct' page

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2458] opened 2012-09-11 18:05 UTC
go to anosrep.org, click 'sign up'
in the existing site, you're taken to login.persona.org/signup. 
in the staging site, you're taken to login.anosrep.org/signin.

**Comment by jrgm** [comment] 2012-09-11 18:24
"It's a feature!"

**Comment by seanmonstar** [comment] 2012-09-11 18:45
Yea, that's working as intended. We merged the Sign In and Sign Up pages into one.

**Closed as completed** 2012-09-11 18:45 UTC
Labels: qa:verified
