### ISSUE TITLE
cannot log into login.persona.org

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3921] opened 2013-09-26 16:09 UTC
Sohan Roy reports in [bug 921047](https://bugzilla.mozilla.org/show_bug.cgi?id=921047):

User Agent: Mozilla/5.0 (Windows NT 6.1; rv:27.0) Gecko/20100101 Firefox/27.0 (Beta/Release)
Build ID: 20130926030207

Steps to reproduce:

I clicked on sign in button on login.persona.org also i tried the same in bugzilla sign in icon(persona)

Actual results:

In both the cases no dialog boxes appeared nor did they prompt anything. It was like they were inactive components of the page.For this I had to log into Bugzilla the old traditional way(by remembering username and password

Expected results:

The dialog box should have appeared and I should be able to log in.

**Comment by jedp** [comment] 2013-09-26 16:17
I can't reproduce this on nightly 27.0a1 (2013-09-23)

**Comment by pdehaan** [comment] 2013-09-26 16:19
Unable to reproduce on OSX 10.8.5 w/ FF 25.0.

**Comment by shane-tomlinson** [comment] 2013-09-26 17:04
Hi Sohan,
Does this happen when you use a fresh Firefox profile or in a different browser?

**Comment by callahad** [comment] 2014-10-31 19:50
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:50 UTC
Labels: ★★★★, cleanup-2014
