### ISSUE TITLE
Resizing BrowserID dialogs doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#716] opened 2011-12-06 16:53 UTC
OS: All
Browser: All

STR:
1. Load a BrowserID client in the browser.
2. Click on the Sign In button to open the BID dialog.
3. Resize the dialog.

When the height it's reduced, the only change in the dialog is that it can be scrolled vertically.
When the length it's reduced, the whole UI changes:
- the site logo part of the dialog disappears
- the remaining elements on the dialog are enlarged
- the emails list is no longer scrollable, but it's fully displayed.
  Another issue is that the user cannot scroll horizontally even after reducing the length enough not to see the Sign In button anymore.

This issue reproduces with all the BrowserID dialogs.

**Comment by shane-tomlinson** [comment] 2012-02-17 15:17
@ioanab - closing as "by design" The changes that occur when resizing the dialog width are to accommodate mobile devices.

**Closed as completed by shane-tomlinson** 2012-02-17 15:17 UTC
Labels: ★★, qa:verified
