### ISSUE TITLE
Sign In button becomes unresponsive after openig and closing a sign in dialog

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2005] opened 2012-07-12 12:57 UTC
OS: Win 7
Browser: Opera 12

Steps:
1. Go to beta.123done.org in Opera 12
2. Click on  'Sign in with Persona' button -> Sign In dialog is open in a new tab
3. Close the Sign in dialog 
4. Click on 'Sign in with Persona' button again

Expected:
The button should be active and the Sign in dialog should open again

Actual:
The Sign in button is grayed out  and the Sign in dialog does not open. The button becomes active only after refreshing the page 

Note: Works fine on FF 13.0.1 and Chrome 20.0.1132

**Comment by seanmonstar** [comment] 2012-07-12 16:32
dupe of #1844

**Closed as completed by seanmonstar** 2012-07-12 16:32 UTC
Labels: qa:verified
