### ISSUE TITLE
Cannot create new BrowserID account in IE9

### ISSUE THREAD

**Issue by ryanttb** [mozilla/persona#97] opened 2011-07-21 22:00 UTC
The popup that appears after clicking the "Sign in" link on http://myfavoritebeer.org/ has no content.

Screenshot: http://skit.ch/bui3

**Comment by lloyd** [comment] 2011-07-21 22:16
ok, @stomlinson - any interest in diagnosing what's up on IE9?

**Comment by ryanttb** [comment] 2011-07-21 22:22
IE 9.0.1 if that helps. I notice on Chrome that there is a very quick screen that says something like, "Communicating with..." before showing the login screen. However, in IE9 I don't see that.

**Comment by ryanttb** [comment] 2011-07-21 22:26
I turned on script debugging. It's breaking on this line:

c.window.postMessage(JSON.stringify(a),c.origin)

with this error:

SCRIPT16386: No such interface supported

production.js, line 231 character 121

**Comment by shane-tomlinson** [comment] 2011-07-22 05:54
lloyd: I am getting the same error as TrippingTheBits.  The problem is with cfg.window.postMessage in line 409 of include.js.  Will dig further.

**Comment by shane-tomlinson** [comment] 2011-07-22 05:57
lloyd: some googling reveals: http://blogs.msdn.com/b/ieinternals/archive/2009/09/16/bugs-in-ie8-support-for-html5-postmessage-sessionstorage-and-localstorage.aspx  See bug #1.  IE9 is STILL broken in this regards it says at the bottom.

**Comment by ryanttb** [comment] 2011-07-29 19:27
Any new thoughts on this? What does Twitter use, JavaScript-wise? They post from their popup back to the app after the user Approves the link & I know it works in IE.

**Comment by shane-tomlinson** [comment] 2011-08-11 21:20
@TrippingTheBits - I can fix it using a proxy function, but I have not had the time to implement it.  It is on the roadmap.

**Comment by petebromberg** [comment] 2011-08-28 13:09
This IE 9 issue is a real problem. There are lots of people using IE9; I simply cannot use BrowserID until it is fixed. I see the last entry was August 11. Are you guys still actively working this? It didn't sound like it would be such a big deal to fix.

**Comment by shane-tomlinson** [comment] 2011-08-30 17:01
@petebromberg - I am working on getting IE working at the moment, hopefully we can have IE8/9 support in BrowserID within the next few weeks.

**Comment by petebromberg** [comment] 2011-08-30 17:09
Shane, that is terrific. Thanks for posting your update. I predict BrowserID will be _hot_.

**Comment by lloyd** [comment] 2011-09-17 23:03
IE8 & IE9 working on dev and beta.  closing this issue.

**Comment by petebromberg** [comment] 2011-09-17 23:29
Thanks for that!

**Comment by ryanttb** [comment] 2011-09-19 01:47
Yes, thank you! I can't wait to start using BrowserID on production sites!

**Comment by shane-tomlinson** [comment] 2011-09-19 04:00
@lloyd - Thanks for fixing this again!  I am reopening the issue, @jbonacci, @benadida and I discussed keeping issues open but adding the tag "in-dev" so that QA knows which ones to test and can close those they have validated.

**Closed as completed** 2011-09-30 14:44 UTC
Labels: ★★★★, qa:verified
