### ISSUE TITLE
The user is allowed to overwrite his BrowserID account

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#303] opened 2011-09-26 15:05 UTC
STR:
1. Open http://beta.myfavoritebeer.org/.
2. Create a new BrowserID account with your email address and log in.
3. Add some more email addresses to the BrowserID account.
4. Log out from BrowserID.
5. Go to the "Never used BrowserID?" page and try to create a new BrowserID account with the email address used at step 2.

Actual Results:
 The "a@a.com in use, If this email is yours you can sign in with it?" warning is displayed. Although the user was not announced about this, when going on with the sign in, his older account is overwritten by the new one (when using the same password as for the old one and when using a different one). The next time he tries to log in, his password is the new password and the emails associated to the old account are no longer associated to BrowserID.

Expected Results:
 Since the user can edit his account in other ways (cancel it, delete emails, change password), he should not be able to overwrite it this way.

**Comment by ghost** [comment] 2011-09-26 15:06
This issue reproduces on all OSs and browsers.

**Comment by shane-tomlinson** [comment] 2011-09-30 10:22
Duplicate of #138.  Adding #323 will fix this.  Closing.

**Closed as completed by shane-tomlinson** 2011-09-30 10:22 UTC
Labels: qa:verified
