### ISSUE TITLE
The password editing fields are displayed automatically after signing in on diresworb.org in IE8

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#849] opened 2012-01-06 13:34 UTC
OS: Windows XP
Browser: IE8

STR:
1. Launch https://diresworb.org in the browser.
2. Sign in to an account.
3. Observe the bottom of the Account Manager section.

The "Old Password" and "New Password" labels and text boxes are displayed automatically on the screen together with the "done" button (The user didn't click at all on the "edit" button).

Note:
This issue doesn't reproduce on the latest Firefox and Chrome browsers.

**Comment by shane-tomlinson** [comment] 2012-01-06 13:44
closing as duplicate of #810.

**Closed as completed by shane-tomlinson** 2012-01-06 13:44 UTC
Labels: qa:verified, qa:needs testcase
