### ISSUE TITLE
Confusing behavior when trying to add an email already associated to the BrowserID account in use

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#703] opened 2011-12-05 16:49 UTC
OS: Windows 7
Browser: Firefox 8.0

STR:
1. Open a BID client (except beta.myfavoriteshow.org).
2. Click on the Sign In button and sign in.
3. On the emails list dialog, click on the "Use a different email" link.
4. Enter one of the emails already associated to this BID account and click "Add".

Expected Results:
An error message with a confirmation button is displayed letting the user know that his email is already associated to BrowserID. Once the user clicks the confirmation button, the dialog is closed and he is signed in with that email.

Actual Results:
The "Check your email! We sent a confirmation email... " dialog is displayed. After a few seconds the dialog disappears automatically and the user is signed in with the entered email.

**Comment by shane-tomlinson** [comment] 2011-12-13 16:47
Fixed with bccd767b8734a5a365a4f44e2903c3c20d7f51ec.  Duplicate of #732.

**Closed as completed by shane-tomlinson** 2011-12-13 16:47 UTC
Labels: qa:verified, qa:needs testcase
