### ISSUE TITLE
Unable to Login from Chrome with Third-party Cookies and Site Data Blocked

### ISSUE THREAD

**Issue by kayaelle** [mozilla/persona#3786] opened 2013-08-13 14:07 UTC
Hello,

Users don't appear to be able to log in to persona from an outside site using chrome when third-party cookies and site data is blocked. Our site is issuing badges to the open badges backpack using browserid.verify

Example is this page:

http://achievery.com/claim/61

Clicking on the big green button -> persona login -> "Persona requires cookies to remember you." (screenshot attached).

Thanks

![screen shot 2013-08-13 at 9 59 50 am](https://f.cloud.github.com/assets/206059/954942/9c6bd5c2-0421-11e3-9445-e14432aa76c1.png)

**Comment by kayaelle** [comment] 2013-08-13 14:27
Should add that it is possible to login to persona directly even with third-party cookies blocked. Just not using browserid.verify from an outside site.

**Comment by callahad** [comment] 2013-08-15 17:04
Unfortunately, Persona currently requires third party cookies and site data, since we store user keys in localStorage.

Your users could add an exception for login.persona.org, and it should work.

**Comment by jaredhirsch** [comment] 2013-08-15 23:13
@callahad we store stuff in localStorage in a first-party context, since we do so _after_ the user has opened the popup. that can't be the source of this bug. reopening.

**Comment by jaredhirsch** [comment] 2013-08-15 23:16
@kayaelle I'm not able to reproduce this bug--the link works fine for me, the dialog behaves normally.

What email addresses are you trying to use to login? What browser, operating system, browser version?

**Comment by seanmonstar** [comment] 2013-08-15 23:21
@6a68 In the dialog, Persona is a 1st party, but loaded in the communication_iframe, where state is managed, it's a 3rd party. Disabled all 3rd party cookies (not allowed visited) causes this.

**Comment by jaredhirsch** [comment] 2013-08-15 23:29
@seanmonstar I'm confused. I can login to persona from the linked page (http://achievery.com/claim/61) in both FF and Chrome with third-party cookies totally disabled. What am I missing here? Is this link actually being hit from an app or something?

**Comment by jaredhirsch** [comment] 2013-08-15 23:31
specifically, my STR are
1. land on the page
2. click green 'add this badge' button
3. click persona button
4. dialog opens and loads just fine (???)

**Comment by seanmonstar** [comment] 2013-08-15 23:36
Ah, you're right. You also need to set the setting "Block sites from setting any data" in Chrome.

**Comment by jaredhirsch** [comment] 2013-08-15 23:46
Ah, ok. So the title of the bug refers to third-party cookies, and the STR refer to chrome's third-party cookie setting ("Block third-party cookies and site data"), and I can't repro this bug with those settings.

@kayaelle Can you give us some more info on the specific Chrome settings that are causing this problem for your users? Do you have cookies totally disabled ("Block sites from setting any data"), or just third-party cookies ("Block third-party cookies and site data")?

**Comment by shane-tomlinson** [comment] 2013-08-16 09:32
@6a68 - This bug will manifest with 3rd party cookies enabled and "Block sites from setting any data" checked. With that checked, we have no access to either cookies or localStorage. I believe @callahad was right in closing this as "cantfix"

**Comment by kayaelle** [comment] 2013-08-16 13:35
Hello - thanks for looking into this. 

This is the setting:

chrome->preferences->Show advanced settings->content settings-> (check) "Block third-party cookies and site data" with "Allow local data to be set" checked.

Strangely I can't replicate this today. As @6a68 mentions, it makes sense that sign in wouldn't work with "Block sites from setting any data" checked but I was following up on a user report with "Allow local data to be set" checked.  Will follow-up with that user because signing in as working as I'd expect today.

**Comment by jaredhirsch** [comment] 2013-08-17 00:25
@kayaelle Thanks so much for getting back to us. Did you have any luck getting in touch with your user?

**Comment by kayaelle** [comment] 2013-08-19 17:00
@6a68 - I did! He can also log in now with "Block third-party cookies and site data" with "Allow local data to be set" checked. Weird. Thank you!

**Comment by callahad** [comment] 2013-08-19 18:26
Huh. That is strange.

Good call on re-opening, @6a68. Since the specific issue seems to be resolved, I'd again suggest closing barring further incidents.

Thanks so much for the report, @Kayalelle!

**Comment by jaredhirsch** [comment] 2013-08-19 23:34
:beers: all around :-D

**Closed as completed by jaredhirsch** 2013-08-19 23:34 UTC
