### ISSUE TITLE
Using a never-seen-before email while IdP is offline uses Fallback IdP

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#3564] opened 2013-06-20 01:01 UTC
1. Take an IdP that Persona has seen, and put it offline.
2. Use an email address never seen before by Persona but comes from said IdP to sign in with Persona
3. Notice that you are prompted to create password.

If you use an email from the same IdP that has previsouly been used with Persona, you'll correctly be told that the IdP is offline currently.

**Comment by lloyd** [comment] 2013-06-20 01:10
Is this a regression?

Sean McArthur notifications@github.com wrote:
1. Take an IdP that Persona has seen, and put it offline.
2. Use an email address never seen before by Persona but comes from said IdP to sign in with Persona
3. Notice that you are prompted to create password.

If you use an email from the same IdP that has previsouly been used with Persona, you'll correctly be told that the IdP is offline currently.

---

Reply to this email directly or view it on GitHub:
https://github.com/mozilla/browserid/issues/3564

**Comment by seanmonstar** [comment] 2013-06-20 01:12
My quick looking suggests its because of this line: https://github.com/mozilla/browserid/blob/dev/lib/wsapi/address_info.js#L199

With the IdP being offline, the `primary.checkSupport` check says it's a secondary, and since it's unknown, it doesn't manage to do the check below of `isSecondary and seendRecently` to set the `state` to `offline`.

**Comment by seanmonstar** [comment] 2013-06-20 01:13
I don't think it's a regression, since that `address_info` hasn't changed in a while...

**Comment by lloyd** [comment] 2013-06-20 01:21
Great candidate for an automated test...  Then states is tricky and rarely exercised.  Fantastic find!

Sean McArthur notifications@github.com wrote:

I don't think it's a regression, since that `address_info` hasn't changed in a while...

---

**Comment by callahad** [comment] 2014-10-31 19:51
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:51 UTC
Labels: ★★★★, cleanup-2014
