### ISSUE TITLE
BrowserID links should look clickable

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#702] opened 2011-12-05 15:19 UTC
OS: All
Browser: All

Most BrowserID links are black and bold while very few of them (e.g. learn more) are blue. In general, links are not emphasized just by being bold, so the user might not realize what he sees is actually a link. The fact that there are some blue links in BID, makes it even less probable to the user that the black bold text is a link.

All the BID links should be blue (or some other color that makes it obvious they are links) both for consistency reasons and user friendliness.

**Comment by shane-tomlinson** [comment] 2011-12-05 15:54
Closing, a duplicate of issue #459.  @ioanab - I am in agreement.

**Comment by ghost** [comment] 2011-12-05 16:14
@shane-tomlinson - issue #459 is closed. I filed this new bug to make sure this issue is tracked and fixed. Please reopen this issue or 459 until it is fixed. Thanks

**Closed as completed** 2012-04-13 09:08 UTC
Labels: ★★★, qa:verified

**Comment by jrgm** [comment] 2012-05-01 23:54
verified on stage train-2012.04.27. Links are consistently styled.
