### ISSUE TITLE
uncaught exception in communication_iframe.js (possibly bigtent related)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3091] opened 2013-03-12 19:22 UTC
I don't have the particular STR at the moment, but I wound up in a state where loading beta.123done.org, the signin button would not show and the spinner just kept spinning. 

In the error console I get 

```
Timestamp: 3/12/13 12:18:24 PM
Error: TypeError: i is not a function
Source File: https://static.login.anosrep.org/v/2172a9e451/production/communication_iframe.js
Line: 4
```

I'll leave this browser in this state for a while if there any more debug info I can pull out of it let me know.

**Comment by karlht** [comment] 2013-03-12 20:18
Calling @edmoz, this is the same problem you ran into, yes?  Did we determine that it was does to a typo in the hostname?

**Comment by edwindotcom** [comment] 2013-03-12 20:58
I've reproduced this two separate times deleting anosrep.org cookies fixes this. but I don't have specific STR right now.

**Comment by ozten** [comment] 2013-03-12 21:06
Playing around, I haven't reproduced. Looking forward to STR.

**Comment by jrgm** [comment] 2013-03-12 22:27
So, I went back to the browserid I had set aside and it was no longer having this issue (possibly as some session somewhere had expired). So nothing left to pull out of debugger.

**Comment by lloyd** [comment] 2013-03-14 16:44
@lloyd to theorize with an eye toward indicators of this happening in production

**Comment by karlht** [comment] 2013-03-15 21:31
Just tickled this again ... trying to pare it down to a minimal case.  Theory so far:
1. The user has interacted with BigTent before (i.e. They have a history with persona with at least one successful BigTent login with a yahoo.com address.)
2. The user is not currently logged in.

But I can't get it to repro consistently.  More as I get it.

**Comment by lloyd** [comment] 2013-03-15 22:03
browser?

**Comment by lloyd** [comment] 2013-03-15 22:11
so this is train-2013.03.01, right?

**Comment by edwindotcom** [comment] 2013-03-15 22:24
I'm on Mac 10.8, Firefox Beta (20.0).  I believe this was train-2013.03.01.  Karl mentioned he repro'd one time and is working on steps to repro.

**Comment by karlht** [comment] 2013-03-15 22:28
I'm on beta (FF 20.0b5).  And I'm looking at the problem right now -- I
just can't seem to get the steps to repro from a clean browser.

**Comment by lloyd** [comment] 2013-03-15 22:39
STR for a problem that may be the same, may not, but exhibits the same symptoms:
1. create a persona acct with a single yahoo.com email via beta.123done.org
2. on the login.anosrep.org domain, localStorage.removeItem('emails')
3. remove all cookies on beta.123done.org
4. reload beta.123done.org

**Comment by lloyd** [comment] 2013-03-15 22:40
```
Uncaught TypeError: undefined is not a function communication_iframe.js:4
g.primaryUserAuthenticationInfo communication_iframe.js:4
g.isUserAuthenticatedToPrimary communication_iframe.js:4
(anonymous function) communication_iframe.js:4
j communication_iframe.js:4
n.success communication_iframe.js:4
(anonymous function) communication_iframe.js:4
(anonymous function) communication_iframe.js:1
```

**Comment by lloyd** [comment] 2013-03-15 23:10
17:07 < lloyd_> kthiessen: so bubbling up to a high level theory...
17:07 < lloyd_> kthiessen: I claim automatic certificate re-provisioning is broken for primary email addresses.
17:07 < lloyd_> kthiessen: that means, when you log into a site and the following are true, you're stuck:
17:07 < kthiessen> I wouldn't bet against you.
17:08 < lloyd_> 1. persona thinks you're logged into this site
17:08 < lloyd_> 2. the site doesn't think you're logged in
17:08 < lloyd_> 3. the site uses the observer api
17:08 < lloyd_> 4. you don't have a certificate for the primary email address you're logged into the site with.

**Comment by lloyd** [comment] 2013-03-15 23:39
resolve in train-2013.03.01 for deployment to prod on monday.

resolved in dev, deploying as I type.

great find you guys, this would have affected a ton of users if we went live with bigtent with it.

**Comment by shane-tomlinson** [comment] 2013-03-19 10:10
Since the fix was merged, closing this. Nice debugging everyone.

**Closed as completed by shane-tomlinson** 2013-03-19 10:10 UTC
Labels: ★★★★
