### ISSUE TITLE
The Sign in button on the emails list dialog doesn't work on mobile devices

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#472] opened 2011-10-24 16:04 UTC
Device: iPhone
OS: iOS 4.2.1
Browser: Safari 5.0.2

STR:
Case1: Multiple emails are associated to the BrowserID account:
1. Launch http://beta.myfavoritebeer.org in the above environment.
2. Tap on the Sign in button.
3. Sign in with an account with multiple emails associated (I had 6 emails).
4. Select an email and tap on the Sign in button.

The button is selected for a while (~30 seconds), then is automatically un-selected. The emails list page stays open and the user is not logged in.

Case2: One email address is associated to the BrowserID account:
1. Launch http://beta.myfavoritebeer.org in the above environment.
2. Tap on the Sign in button.
3. Sign in with an account with only one email associated.
4. Tap on the Sign in button.

The button is selected, then the emails list page is automatically closed. The user is not logged in.

**Comment by ghost** [comment] 2011-10-25 07:45
This issue reproduces on Android phones too:

Device: Samsung Galaxy S
OS: Android 2.2
Browser: Firefox 7.0.1
1. Launch http://beta.myfavoritebeer.org in the above environment.
2. Tap on the Sign in button.
3. Sign in with an account (it doesn't matter how many emails are associated to it).
4. Tap on the Sign in button.

The button is selected, then the emails list page is automatically closed. The user is not logged in.

**Comment by shane-tomlinson** [comment] 2011-10-27 17:15
duplicate of #399.

**Closed as completed by shane-tomlinson** 2011-10-27 17:15 UTC
Labels: qa:verified
