### ISSUE TITLE
Typing in login fields on Chrome/iPad (3rd gen) requires 3 touches

### ISSUE THREAD

**Issue by mattrco** [mozilla/persona#4092] opened 2014-02-14 10:42 UTC
When the login form appears in Chrome on an iPad running iOS7, I need to tap the email field 3 times to get focus and the keyboard to appear. It's the same for the password field.

In contrast, with Safari it takes one touch to focus the field and bring up the keyboard.

chrome://version reports:

```
Google Chrome   32.0.1700.21 (Official Build 330d8e1b5413a27efdcb2c4a9d68e11345bb8913) 
User Agent  Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/32.0.1700.21 Mobile/11B554a Safari/9537.53
```

I can reproduce this reliably -- let me know if you need more information. I'm not even sure this is something within your control, but thought it was worth reporting.

**Comment by jamesshore** [comment] 2014-02-15 20:15
I was unable to reproduce this on Chrome 31 or 32. The keyboard popped up as soon as I tapped each field.

```
Google Chrome 31.0.1650.18
User Agent: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) (etc)
```

```
Google Chrome 32.0.1700.21
User Agent: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) (etc)
```

**Comment by mattrco** [comment] 2014-02-17 13:13
Which iPad model did you use? (http://support.apple.com/kb/ht5452).

I'll update the issue when I know mine.

**Comment by jamesshore** [comment] 2014-02-17 19:25
Mine is A1395 16GB (iPad 2).

**Comment by mattrco** [comment] 2014-02-21 16:34
The device I used is an A1430. I've no idea if that's significant, though.

**Comment by jaredhirsch** [comment] 2014-02-23 01:15
@mattcottingham Actually, it is: per [the apple support article](http://support.apple.com/kb/HT5452), A1430 is a 3rd gen iPad.

I don't have one, does anyone? Updating the bug description accordingly.

**Comment by callahad** [comment] 2014-10-31 19:49
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:49 UTC
Labels: cleanup-2014
