### ISSUE TITLE
mobile compatibility

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#43] opened 2011-06-30 00:52 UTC
Android and iOS. From James Burke:

Android 2.2, Firefox Mobile 4.0.1 on a 7" Galaxy Tab: no messages in
the console about a possible error. I do not see another window in the
list of browser windows either. I tried the example on browserid.org,
but seems to have the same problem. Clicking the button does not show
the browserid window.

iOS 4, Mobile Safari, on iphone: a JavaScript error in the console:
"undefined Channel.build() called without a valid window argument".

**Comment by lloyd** [comment] 2011-06-30 04:53
Really!?  Works on my iphone.  The only issues I'm aware of on iOS are that key generation takes too long and lacks user feedback, and that the dialog needs to be visually optimized for mobile devices.

James, would you mind appending the precise steps to reproduce the issue that you're seeing?  One case where such symptoms could occur is if you clicked to login, the dialog popped up, and then you reloaded the page.

curiously -- lloyd

**Comment by jrburke** [comment] 2011-06-30 22:22
For iOS, I traced it down to using iScroll and having the sign in button inside that scrollable region. Apparently it was capturing some events and returned to default handlers in a way that Safari thought it was a popup and blocked it. So the fix was to not use iScroll for that region.

That fixed the pop-up, but after putting in my name and password, I waited for a while, and then eventually there was an error in the console:

https://browserid.org/dialog/crypto-stubs.js
JavaScript execution exceeded timeout.

I am using an iPhone 3GS, so maybe on an iPhone 4 it goes faster, and you already mentioned you had some thinking around how to reduce the crypto time, so I think you already have a handle on this issue.

The removal iScroll did not fix the Android issue, I'll keep looking at that, and I'm going to be trying it on an android phone that may have a different software setup. I'll post any results into this ticket.

**Comment by jrburke** [comment] 2011-07-04 23:48
Looked more on Android 2.3.4 with Firefox 5 Mobile: the demo beer application does not work, and when I did some local debugging in my app, it looks like the window.open in _open_window() fails. Maybe Fx 5 is really strict about popup windows even, ones as a result of user action?

I wonder if makes sense to allow an API to getVerifiedEmail where my app could call it with an URL to return to once verification had been received, and then allow navigation away from my page in the current window to complete the browserid process, and then when done navigate back to that URL that was passed to getVerifiedEmail.

The core issue of popup windows on Android probably needs more investigation first, but just writing out findings as I find them.

**Comment by jrburke** [comment] 2011-07-07 23:03
I got mobile firefox to work by not passing window properties to the window.open call, and did [a pull request for that change](https://github.com/mozilla/browserid/pull/45)

That helps pop the window on mobile firefox, but after authentication is done, the window does not disappear on its own. I had to manually close it and then went back to my web app and it was signed in/had the verified email.

Also, the sign in UI, with the Sign In and Cancel buttons on the bottom are difficult to use on a mobile device. I know mobile was not the initial target, just listing out items as I come across them.

**Comment by mattbasta** [comment] 2011-08-01 21:32
As it stands, tgavankar and I can't get BrowserID to work _at all_ for any mobile browser.
- Android stock browser seems to freeze at a "please wait" screen for some devices, though it occurs on all the smartphones that I've tested our code on.
- Firefox Mobile doesn't load the login popup at all
- iOS closes the keyboard after a second or so of focus on the email/password field, making it impossible to enter credentials.

This is testable on our site: http://munchylunchy.com/

**Comment by lloyd** [comment] 2011-08-01 21:45
@stomlinson Hey, will you have a moment to look at this in the coming day or two?

**Comment by shane-tomlinson** [comment] 2011-08-05 23:54
@jrburke - thanks for the debugging, I am going to start on fixing this next week.
@lloyd - What all devices do we need?  We have been approved for submitting a bug to get what we need.

**Comment by shane-tomlinson** [comment] 2011-08-05 23:55
Verifying that this is not working on Android 2.3 default browser, it opens BrowserID, but closes the original window.

**Comment by benadida** [comment] 2011-08-12 18:22
Compatibility matrix will be placed on wiki at some point next week.

This issue should be reduced in scope to: does this work on iOS Safari and Fennec?

**Comment by shane-tomlinson** [comment] 2011-09-21 11:51
We are working on iOS Safari and Fennec on both phones and tablets.  Working on Honeycomb default browser, but not Gingerbread's.

**Comment by mattbasta** [comment] 2011-09-21 12:18
Is it wise to ignore Gingerbread? 2.2 and 2.3 are what most (if not all) Android smartphones are running by default.

**Comment by shane-tomlinson** [comment] 2011-09-21 12:20
We most definitely want to support Gingerbread, it just hasn't happened yet with so many other high priorities.

**Comment by mattbasta** [comment] 2011-09-21 12:35
Froyo and Gingerbread's native browsers combined may very well be the most popular smartphone browsers. Is it not irresponsible to work on 3.x instead, which only makes up 1.5% of the market?

http://developer.android.com/resources/dashboard/platform-versions.html

Are there usage metrics that show a greater number of Fennec or Honeycomb users using BrowserID? What is the logic behind these priorities?

**Comment by shane-tomlinson** [comment] 2011-09-21 12:36
@mattbasta - we didn't go after honeycomb, we got it for free with other changes we made.

**Comment by shane-tomlinson** [comment] 2011-09-21 12:38
@mattbasta - in my above comment of "We are working on iOS..." I should have made that more precise and said - "BrowserID already works on iOS..."

**Comment by mattbasta** [comment] 2011-09-21 21:56
Ah, that makes more sense. :) Are those fixes in production? I'd like to test them with my applications.

**Comment by lloyd** [comment] 2011-09-21 21:58
they definitely are on https://dev.diresworb.org (our development environment) which will be in production in < 2 weeks.

**Comment by shane-tomlinson** [comment] 2011-10-19 08:47
Stock android browser on android 2.3 now a go.  I need some testing on 2.2.

**Comment by shane-tomlinson** [comment] 2011-11-10 11:28
Closing this as we have been supporting Android 2.2 for a while now.

**Closed as completed by shane-tomlinson** 2011-11-10 11:28 UTC
Labels: ★★★, qa:verified
