### ISSUE TITLE
mac opera only, incorrectly launches pop up window as a new tab

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3141] opened 2013-03-26 22:36 UTC
this is mac opera only.  no repro on Win opera.
1. goto beta.123done.org and click sign in

result: new tab is opened with sign in dialog

expected: should be in a new window at a specific size.  At first i thought it was just the browser, but i was able to go to other sites to pop up a sized pop up window.

**Comment by jaredhirsch** [comment] 2013-03-26 23:51
It's [well-known](http://www.quirksmode.org/js/popup.html) that Opera opens a window-tab if you don't specify height and width, but we're [doing just that](https://github.com/mozilla/browserid/blob/dev/resources/static/include_js/_include.js#L127) in include.js.

I suspect this may be a browser bug--Opera's bug tracker is closed, so I'm not sure how to definitively find the bug.

**Comment by callahad** [comment] 2013-03-27 01:30
As far as I can tell, this is intended behavior on Opera's part. The windows version offers an explicit preference for governing popup behavior. The Mac version omits that preference.

I'm going to vote wontfix -- everything still works, it's just aesthetically weird. But as the default behavior, I'm sure Opera's users are used to it. Curious to see the behavior on the Webkit-based version...

**Comment by jaredhirsch** [comment] 2013-03-27 03:42
@callahad but the quirksmode popup implementation correctly opens a new window, not a new tab, even on opera mac--so there may be a tweak we can make here.

**Comment by callahad** [comment] 2013-03-27 04:31
@6a68 I can't reproduce that behavior. Opera 12.50 on OS X 10.7 always opens in a tab for me, even with width and height set.

**Comment by shane-tomlinson** [comment] 2013-03-27 12:16
I thought there was a bug about this already, but I cannot find it.

**Comment by shane-tomlinson** [comment] 2013-03-27 12:17
This is a dup of https://github.com/mozilla/browserid/issues/423, more specifically we outline behaviors in: https://github.com/mozilla/browserid/issues/423#issuecomment-4025158

**Comment by shane-tomlinson** [comment] 2013-03-28 12:41
Closing as dup.

**Closed as completed by shane-tomlinson** 2013-03-28 12:41 UTC
