### ISSUE TITLE
Continuously prompted for password after logging into eyedee.me

### ISSUE THREAD

**Issue by ckolos** [mozilla/persona#940] opened 2012-01-23 22:17 UTC
After logging into eyedee.me and successfully auth'ing, I attempt to login to beta.myfavoritebeer.org. I select BrowserID as my auth method and after entering my email address for eyedee.me, I am reprompted, over and over, for my eyedee.me password.

I am using Nightly, 12.01a

**Comment by ckolos** [comment] 2012-01-23 22:19
Links to images showing, in rough chronological order, what I see: http://carrera.databits.net/~ckolos/bidbug

**Comment by ckolos** [comment] 2012-01-24 02:35
Yeah, the multiple verify is what I'm seeing too. I'm not getting the unknown user error though... I _do_ however get a very brief interstitial that seems to show the verify was successful. I can't get a screenshot of it fast enough though...

**Comment by lloyd** [comment] 2012-01-24 19:28
please clear cache and retest.  should be fixed in stage.

**Comment by ckolos** [comment] 2012-01-24 22:12
Respectfully, I disagree. Cleared cache and same result.

I do not have permission to reopen this bug and, frankly, I question it being closed without waiting for a result. Saying "Should be fixed in stage" isn't the same thing as "Yes, I saw this bug and fixed it in stage, but I will wait to see if that fix applies to you."

**Comment by ckolos** [comment] 2012-01-24 22:44
@jbonacci - Nightly 12.01a, dl'd from mozilla, updated today. Running on ArchLinux Kernel: 3.2.1-1-ARCH #1 SMP PREEMPT Fri Jan 13 06:50:31 CET 2012 x86_64 Intel(R) Xeon(R) CPU 5160 @ 3.00GHz GenuineIntel GNU/Linux

**Comment by lloyd** [comment] 2012-01-25 00:22
@ckolos Sorry for misreading the issue.  I have an arch linux machine here, I'll test under your precise environment this evening.

**Comment by jrgm** [comment] 2012-01-25 04:24
I'm on Ubuntu 11.10, but I cannot reproduce this. Sorry to say.

**Comment by lloyd** [comment] 2012-01-25 06:32
@ckolos I'm on Nightly 12.0a1 (2012-01-24) - Running on ArchLinux Kernel: Linux clover 3.2.1-2-ARCH #1 SMP PREEMPT Mon Jan 23 12:40:01 UTC 2012 x86_64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz GenuineIntel GNU/Linux

I can't reproduce this issue.  Here's what I did:
1. run firefox with a fresh profile
   1. `./firefox-bin -P`
   2. click `create profile`
   3. click `next`
   4. name the profile `fresh` and click `finish`
   5. click `start nightly`
2. go to http://beta.myfavoritebeer.org
3. click `sign in`
4. enter `lloyd@eyedee.me`
5. click `next`
6. click `verify`
7. type my password into eyedee.me that shows in the dialog
8. notice animations and stuff and find myself logged into myfavoritebeer

Please try the steps above, especially the creation of a new profile.  That will help us determine if this behavior is due to your preferences or extensions or plugins you have installed.

I'm downgrading this to a three star because we can't seem to reproduce it on the same platform/browser, and that suggests its environmental and not affecting a significant number of other users.  but leaving it open so we can figure out what the heck is going on.

**Comment by ckolos** [comment] 2012-01-25 15:29
Profile change seems to have fixed it. Thanks for digging in.

**Comment by ckolos** [comment] 2012-01-25 15:31
I will say this; I was visiting eyedee.me first, auth'ing there, then visiting beta.myfavoritebeer.org. That's a slightly different order than above, but regardless, with a new profile, the issue is non-reproducible.

**Comment by lloyd** [comment] 2012-01-25 17:15
dang, could it be that you had "third party cookies" disabled in your default profile?  Is this a duplicate of GH-982

**Comment by lloyd** [comment] 2012-01-25 17:19
10:18 < ckolos> lloyd: I can confirm that as a matter of course, I disable third-party cookies.

**Comment by lloyd** [comment] 2012-01-25 17:32
closing this down and moving discussion to GH-982

**Closed as completed by lloyd** 2012-01-25 17:32 UTC
Labels: ★★★, qa:verified, qa:needs testcase
