### ISSUE TITLE
Having difficulty verifying account

### ISSUE THREAD

**Issue by alexsaves** [mozilla/persona#3264] opened 2013-04-17 18:03 UTC
I keep going through the verification process without success. When I follow the verify link, it just gives me a blank page in the mozilla template. See video: http://screencast.com/t/dYCrxyuRPEew

**Comment by karlht** [comment] 2013-04-17 18:59
I am unable to reproduce this bug on my setup.  @alexsaves, may I ask what OS you're using, and what browser and version?  Do you have third-party cookies disabled, and are you using any extensions?  Let's see if we can replicate your setup as closely as possible.

**Comment by alexsaves** [comment] 2013-04-17 19:02
Using Windows 7. Happens in FireFox but I just found that it works fine in Chrome. I have Flash disabled in FF. Does that matter?
https://login.persona.org/verify_email_address?token=SFppesoRlKGmnN1z3D6zQXfc15LfHkrXDQgA8g23HZN6mf0w

**Comment by callahad** [comment] 2013-04-17 19:04
I don't have Flash on my machine either. I wonder if somehow localStorage or related was disabled or an addon was interfering...

**Comment by alexsaves** [comment] 2013-04-17 19:09
Possibly. Is it just a redirect, or is there a session token or something that is missing?

**Comment by seanmonstar** [comment] 2013-04-17 19:14
Is there an error thrown in the JavaScript?

Ctrl + Shift + K will show you the JS console. Open it before click the
link, and be sure JavaScript and Logging buttons are enabled.
​

**Comment by alexsaves** [comment] 2013-04-17 19:16
![jserror](https://f.cloud.github.com/assets/867447/393248/5354d716-a793-11e2-8777-0ca8236102c8.PNG)
Actually yah there is an error. Check out the screenshot

**Comment by seanmonstar** [comment] 2013-04-17 19:21
Interesting. Every release versions that browserid.js with its hash. Which
one do you see currently in source? This is the one I see:
https://static.login.persona.org/v/0c70f59571/production/en/browserid.js

**Comment by alexsaves** [comment] 2013-04-17 20:07
https://static.login.persona.org/v/0c70f59571/production/en/browserid.js

**Comment by alexsaves** [comment] 2013-04-17 20:07
I think because I'm using firebug it breaks on errors. Maybe thats why its not proceeding.

**Comment by seanmonstar** [comment] 2013-04-17 20:15
There's an option in Firebug to break on all errors, or only uncaught, or
not at all.

**Comment by alexsaves** [comment] 2013-04-17 20:24
Sure.. but it seems like a missing curly brace would be a fairly serious uncaught error.

**Comment by seanmonstar** [comment] 2013-04-18 01:09
It would be, but it's not an error anywhere else, so I wonder if it's a red
herring.

**Comment by callahad** [comment] 2014-10-31 19:52
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:52 UTC
Labels: ★★★, cleanup-2014
