### ISSUE TITLE
Firefox on Linux doesn't display address bar in BrowserID popup

### ISSUE THREAD

**Issue by graue** [mozilla/persona#3157] opened 2013-03-31 05:12 UTC
I use Firefox on Ubuntu, and the popup I get when logging in with Persona has no address bar visible. Screenshot:

![persona](https://f.cloud.github.com/assets/1730853/321350/d8382dca-99bf-11e2-8217-238c05483eb6.png)

This makes it impossible to verify that the login window is legitimate and not a phishing site. I'd expect to see an address bar with a "Mozilla Foundation (US)" SSL badge. In Chromium, I do see an address bar with such a badge.

I'm using Firefox 21.0a2 right now, but this bug dates to whenever I first used BrowserID — probably around August 2012, while on Firefox 14 or 15 stable. Until I tried it in Chromium recently, I thought the address bar was hidden on purpose, and that it was a questionable security decision, but I didn't realize it was a bug.

**Comment by callahad** [comment] 2013-03-31 06:07
Huh. What distro are you on? I can't reproduce this on Debian...

Maybe try creating a new profile (`firefox -ProfileManager`) temporarily to see if the problem is specific to some local configuration?

**Comment by graue** [comment] 2013-03-31 06:28
(Hi Dan!)

Okay, I figured this out... it's due to my weird setup. Long ago, to make Firefox compact while keeping the menu bar, I dragged the Location box out of the "Navigation Toolbar" and onto the "Menu Bar", then hid the navigation toolbar:

![nav](https://f.cloud.github.com/assets/1730853/321411/97cf66a2-99cb-11e2-9845-0f30b0f2c0b6.png)

Presumably since the popup hides the menu bar, it also, in my case, hides the location box.

Huh. Now I kind of feel like this is my fault — I don't know how you could work around this — but I like my setup. Any ideas?

**Comment by callahad** [comment] 2013-03-31 13:25
Hey Scott :)

Try resetting everything to its default location, then go to View -> Toolbars, and uncheck "Menu Bar". That collapses the menu into a single "Firefox" button that sites to the left of your tabs, leaving you with two lines.

**Comment by callahad** [comment] 2013-04-04 16:46
Sounds like this is resolved -- closing :)

**Closed as completed by callahad** 2013-04-04 16:46 UTC
Labels: qa:verified
