### ISSUE TITLE
Persona dialog blank on MSIE 11 on Windows 8.1

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3593] opened 2013-06-27 23:17 UTC
Robert Kaiser (KaiRo on moz IRC) reports that "Persona doesn't work on MSIE 11 on Win 8.1"

He explained on the `#planning` channel on Jun 27:

```
[16:11:06] <KaiRo>   jedp: the sign in popup comes up completely empty, the arrow design is there, but no textbox for filling in an email address - in the end, I guess someone will need to get an image from http://windows.microsoft.com/en-us/windows-8/preview-download and test directly with that browser
[16:12:01] <KaiRo>   jedp: of course, we can't be sure if they'll ship with that UA or if what breaks Persona is a bug on their side
[16:12:49] <KaiRo>   jedp: oh, and I turned off any kind of exception lists or anything they might automatically download - I installed all updates but manually
[16:13:10] <jedp>    KaiRo thanks for the details.  I'll file an issue.
[16:13:29] <KaiRo>   jedp: the latter is just in case they might send different UAs to different sites based on such a downloaded list
```

**Comment by jedp** [comment] 2013-06-27 23:22
Addendum, from KaiRo:

also, I see that those news sites about the "leaked UA string" from a few days ago say "Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko" while what I see in this Win8.1 preview build is "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko" (the missing "IE 11.0" in the latter is significant)

**Comment by shane-tomlinson** [comment] 2013-07-02 11:16
I am able to reproduce on dev, but not locally using Windows 8.1 IE11 Metro. Since these are development versions of Windows and IE, we will keep track of this and raise priority as the time for release gets nearer.

This does not reproduce on Windows 8/IE10.

**Comment by callahad** [comment] 2013-07-02 16:19
Just a quick note, if we're relying on detecting IE or anything, that may be causing the breakage, since IE11 removes references to "IE" in its UA string: http://www.nczonline.net/blog/2013/07/02/internet-explorer-11-dont-call-me-ie/

**Comment by shane-tomlinson** [comment] 2013-07-02 16:23
@callahad - could be - WinChan is the only place where we do UA sniffing for IE.

**Comment by vladikoff** [comment] 2013-07-02 18:14
Testing in the 'Metro' version of IE via 123done.org
![](http://v14d.com/i/51d3187345f1f.jpg)

**Comment by vladikoff** [comment] 2013-07-02 18:29
Here's a screenshot form the desktop version:
![](http://v14d.com/i/51d31ba39cdb3.jpg)

As you can see in the styles inspector #authentication_form is still 'display: none', 
If i uncheck that, i can see:
![](http://v14d.com/i/51d31bda81728.jpg).

**Comment by vladikoff** [comment] 2013-07-02 18:39
A bit of good news, sign in from login.persona.org works perfectly in both modes!

![image](https://f.cloud.github.com/assets/128755/738457/a1315d9e-e346-11e2-91b5-8745225513e9.png)

**Comment by callahad** [comment] 2013-09-24 15:51
Using Windows 8.1 Enterprise on a Surface Pro with IE 11.0.9600.16384.
1. First time login (with eyedee.me) works great in Metro mode.
2. Subsequent logins completely fail (blank dialog) in Metro mode.
3. First time login completely fails (blank dialog) in Desktop mode.

We know IE 11 / Win 8.1 is coming _soon._ What's the status of our fix so we don't have to scramble like we did for iOS 7?

**Comment by callahad** [comment] 2013-09-24 16:00
RTM bits are available on MSDN. Bumping this to 5-star to avoid breaking in 1-2 weeks when IE 11 gets released and we're all at the Summit.

**Comment by shane-tomlinson** [comment] 2013-09-24 18:11
There are (at least) two problems in the version of Windows 8.1 available on modern.ie

1) WinChan has not been correctly updated to browser sniff the new IE11 UA string, causing the postMessage to fail and the dialog to load no content.
2) The dialog window loses it's reference to window.opener after redirecting to the IdP

The second is reported fixed by @callahad using a Surface tablet.

See work started https://github.com/shane-tomlinson/browserid/compare/ie11

**Comment by ryanseys** [comment] 2013-09-28 21:54
No excuses not to have an IE (6/7/8/9/10/11) VM lying around when Microsoft is giving them out for free!

http://www.modern.ie/en-us/virtualization-tools#downloads

**Comment by shane-tomlinson** [comment] 2013-09-30 10:46
@ryanseys - I have IE6, 7, 8, 9, 10, 11 in Windows XP, Windows 7, Windows 8 and Windows 8.1 in VMs.

An issue for us is that the Windows 8.1 IE11 available on modern.ie is pre-release and does not act the same as RTM in some cases.

**Closed as completed** 2013-10-01 20:35 UTC
Labels: ★★★★★, area:dialog
