### ISSUE TITLE
Issues with parallel sign ins

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#580] opened 2011-11-15 17:14 UTC
Environments:
Ubuntu 11.10 + Chrome 15.0.874.120
Windows 7 + Firefox 8.0

Signing into different clients with different BrowserID accounts in the same browser doesn't work as expected:

Case1:
The user signs into http://beta.myfavoritebeer.org with his BrowserID account, then opens http://beta.myfavoritebooze.org in a new tab, signs in, then signs out. The user is signed out of his account in the first client as soon as signing out of the second client (this is visible when clicking "log out" or when the cookies expire).

The user would not expect to be completely signed out from a client just because he signed out of another one.

Case2:
The user signs into http://beta.myfavoritebeer.org with his BrowserID account, the he opens https://diresworb.org in another tab. On diresworb.org, the user edits another BrowserID account or creates a new one. As soon as the user is signed into diresworb.org, he is also signed out of myfavoritebeer and signed in with the account used on diresworb.org (this is visible when clicking "log out" or when the cookies expire).

Even if signing into different clients with different account affects the sign ins, signing into diresworb.org should not do it.

When the user clicks on the Sign In button in the client he first logged into, after logging into the second account in another client or on https://diresworb.org, the following error message is displayed:

"We are very sorry, there has been an error!
To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below.

```
Action: Establishing Relay
Relay frame could not be found"
```

On a second try it usually works fine.

**Comment by lloyd** [comment] 2011-11-16 13:22
This is as designed - browserid login is global.  It's not expected to be common that users will have different browserid accounts, and we'll attempt to consolidate all a users emails into a single account.

I'm closing down this issue as "by design", but feel free to open a larger discussion on the dev-identity if you're not content with my explanation here.

W.R.T. the error you see, _great_ find.  I oppened issue #588 to track this.

**Closed as completed by lloyd** 2011-11-16 13:22 UTC
Labels: qa:verified
