### ISSUE TITLE
MySQL database doesn't re-connect during deployment w/o restart

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2504] opened 2012-09-19 19:27 UTC
Although we've spent significant time improving how we handle connections to mysql, we saw stale dead connections for around 15 minutes during the deployment.

https://etherpad.mozilla.org/devops-beta-push

This was seen as 503 and slowness in wspai address_info for secondary email addresses.

atoll and jrgm can provide more background to reproduce issue.

Notes:
- heartbeat was okay even though we had busted mysql conn
- had to restart processes
- Suggestion: Add a seperate heartbeat to check every mysql conn
  - We should monitor this new heartbeat
- We seem to have hit some edge case not covered by Feb pooling fix
- mysql conn terminated to slaves as part of the deployment

**Comment by lloyd** [comment] 2012-09-20 19:32
given the data, this looks like a problem that was affecting webheads.  Webheads talk to mysql through zeus.

To attempt to reproduce this issue I'll start up an ephemeral instance and stall or stop mysql to audit the reconnection logic.

**Comment by lloyd** [comment] 2012-09-20 19:46
First attempt to reproduce: **Stop MySQL**
1. here I simply stopped the mysql daemon on the ephemeral instance
2. Spawnin the dialog displayed the error - the server is under extreme load
3. from the webhead log:
   
   {"level":"warn","message":"database connection down: Error: connect ECONNREFUSED","timestamp":"2012-09-20T19:41:56.359Z"}
   {"level":"warn","message":"database is down, cannot process request: Error: connect ECONNREFUSED","timestamp":"2012-09-20T19:42:01.210Z"}
   {"level":"info","message":"127.0.0.1 - - \"GET /wsapi/session_context HTTP/1.1\" 503 6 41 \"-\" \"-\"","timestamp":"2012-09-20T19:42:01.212Z"}
   {"level":"warn","message":"database is down, cannot process request: Error: connect ECONNREFUSED","timestamp":"2012-09-20T19:42:02.520Z"}
   {"level":"info","message":"127.0.0.1 - - \"GET /wsapi/session_context HTTP/1.1\" 503 3 41 \"-\" \"-\"","timestamp":"2012-09-20T19:42:02.521Z"}
   {"level":"warn","message":"database is down, cannot process request: Error: connect ECONNREFUSED","timestamp":"2012-09-20T19:42:07.776Z"}
   {"level":"info","message":"127.0.0.1 - - \"GET /wsapi/session_context HTTP/1.1\" 503 3 41 \"-\" \"-\"","timestamp":"2012-09-20T19:42:07.777Z"}
   {"level":"warn","message":"database is down, cannot process request: Error: connect ECONNREFUSED","timestamp":"2012-09-20T19:42:09.105Z"}
   {"level":"info","message":"127.0.0.1 - - \"GET /wsapi/session_context HTTP/1.1\" 503 3 41 \"-\" \"-\"","timestamp":"2012-09-20T19:42:09.106Z"}
   {"level":"warn","message":"database is down, cannot process request: Error: connect ECONNREFUSED","timestamp":"2012-09-20T19:42:11.199Z"}
   {"level":"info","message":"127.0.0.1 - - \"GET /wsapi/session_context HTTP/1.1\" 503 4 41 \"-\" \"-\"","timestamp":"2012-09-20T19:42:11.200Z"}
   {"level":"debug","message":"user is authenticated","timestamp":"2012-09-20T19:42:23.725Z"}
   {"level":"info","message":"127.0.0.1 - - \"GET /wsapi/session_context HTTP/1.1\" 200 8 248 \"-\" \"-\"","timestamp":"2012-09-20T19:42:23.726Z"}
4. restart mysql
5. service works as expected - no process restart required, reconnection logic happy.

Simply stopping mysql and waiting, then restarting, is insufficient to reproduce what we saw in production

**Comment by lloyd** [comment] 2012-09-20 19:53
Second attempt to reproduce: `killall -STOP mysqld`
1. send SIGSTOP to mysqld
2. load dialog
3. observe 5s delay between dialog load an "THE SERVER IS UNDER EXTREME LOAD"
4. from browserid.log
   
   ==> browserid.log <==
   {"level":"warn","message":"cannot reconnect to mysql! 1 outstanding queries #fail.","timestamp":"2012-09-20T19:49:41.914Z"}
   {"level":"warn","message":"database is down, cannot process request: database connection unavailable","timestamp":"2012-09-20T19:49:41.916Z"}
5. send SIGCONT to mysqld 
6. service works as expected, no restart of any processes required.

Simply pausing the process does not trigger any issues with implemented reconnect logic.

**Comment by lloyd** [comment] 2012-09-20 20:02
I don't believe there's any regression in the database re-connection logic, but rather that zeus is a required element of the failure.  In order to further diagnose this we need to get @jrgm, @atoll, and @lloyd in the staging environment trying to reproduce.

**Comment by lloyd** [comment] 2012-09-20 20:02
Also, when I stop mysql, heartbeats fail for me:

```
$ curl -i http://127.0.0.1:62700/__heartbeat__
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Connection: keep-alive
Transfer-Encoding: chunked

bad
```

**Comment by lloyd** [comment] 2012-09-20 20:03
Finally, @atoll, can you provide sanified logs for the period of downtime from webheads and dbwriters

**Comment by jrgm** [comment] 2012-09-20 20:41
It's actually @floatingatoll on github. atoll, see above. ^^

**Comment by lloyd** [comment] 2012-09-20 21:35
```
14:54 < atoll> okay, hi 
14:54 < atoll> so, here's how i caused the issue. on a slave, i ran "SHOW PROCESSLIST; KILL 1234567;"
14:54 < atoll> and then did not restart node.js
14:55 < atoll> this terminates the connection on the server side. the myqsl client in node is responsible for detecting the ERROR (2013) 
           Server has gone away error produced by the standard libmysql client libraries.
14:55 < atoll> it is my theory that it didn't.
14:57 < atoll> the specific internal error code emitted by libmysqlclient.so in that situation is CR_SERVER_GONE_ERROR, typically.
14:58 < atoll> node.js *should*, in the case of a 2013 error from the mysql client libs, try to reconnect once.
14:58 < atoll> (and resend the query)
14:58 < atoll> http://dev.mysql.com/doc/refman/5.1/en/auto-reconnect.html
14:58 < atoll> the python services mysql code recently implemented this. i do not know the status of it in node.js code.
14:59 < atoll> jrgm: does the above give you enough information to begin repro attempts?
```

**Comment by jrgm** [comment] 2012-09-24 21:08
I tried doing the `kill <threadid>` on:
1) two awsbox, one acting as the webhead and the other being the sole database.
2) in stage, where we have zeus between the webhead and the set of readonly databases.
I could not reproduce a problem by doing that. The mysql connection is re-established within about 50 seconds, and while running 250K ADU, the load_gen client does not detect any errors, nor can I locate any error in the browserid.log.

As @lloyd noted, the node.js driver does not bind to libmysqlclient; it implements the mysql protocol itself. On the awsbox, when I kill the mysql thread, a FIN is sent back to the client, which immediately re-handshakes and pushes data to re-establish the mysql connection.

**Comment by jaredhirsch** [comment] 2012-10-18 16:50
five stars but looks like it's gone dead. @lloyd, is this a wont-fix or is some action needed?

**Comment by callahad** [comment] 2014-10-31 19:54
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:54 UTC
Labels: ★★★★, area:server, area:ops, cleanup-2014
