### ISSUE TITLE
english means english

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2076] opened 2012-07-17 19:50 UTC
When I set my browser settings to prefer english first `en`, then a different language, we serve up the different language rather than `en-US`.

I would think that it would be more optimal to serve en-US in this scenario.

**Comment by seanmonstar** [comment] 2012-07-17 19:57
dupe of #1863

**Comment by shane-tomlinson** [comment] 2012-07-17 20:37
+1.  Is this apply universally?  Would a user from Mexico who has their Spanish set to es be alright if they were served up es-AR if we had that translation but not normal es?

**Closed as completed** 2012-07-17 21:12 UTC

**Comment by ozten** [comment] 2012-07-17 21:41
There are unit tests to match the base part of a language code.

There are also comments around potential political issues around doing this too broadly.
