### ISSUE TITLE
"Invalid cert in chain" errors reported

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/persona#1112] opened 2012-02-14 17:16 UTC
Jeff Schnitzer jeff@infohazard.org reports on 2/13/12:

```
I'm seeing verification responses of:

status=failure
reason=expired cert in chain

This seems to be during a check for persistent login (silent:true).  Is this
normal?  Am I doing something wrong?
```

When asked for confirmation, he reported on 2/14/12 that it was ongoing:

```
Yep, still seeing it... I haven't really explored the issue in any depth, but it's definitely
when reconstituting a persistent session.  I haven't really explored the issue, but
some things that might or might not be related:

* I did an eyedee.me login recently, so it shows in my sign in list
(although this is not what is being remembered)
* I'm on chrome 18.0.1025.11
* This is against an app running on localhost (in development)

I haven't seen it in other environments but we aren't in production so it might
just not have come up.  We should be going to limited production release next
week... but I've squelched this particular error from the user so it won't cause problems.
```

**Comment by benadida** [comment] 2012-03-01 18:20
can't reproduce, closing for now, will reopen if it happens.

**Closed as completed by benadida** 2012-03-01 18:20 UTC
Labels: ★★★, qa:verified
