### ISSUE TITLE
The links opened from BID pages should be localized

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1110] opened 2012-02-14 17:07 UTC
https://diresworb.org/about, https://diresworb.org/privacy and https://diresworb.org/tos should be localized.

Practically, all the links opened from BID pages should be localized. Since this might be difficult, at least those that are hosted on diresworb.org (respectively browserid.org) should be localized.

**Comment by ozten** [comment] 2012-02-14 17:35
This is a duplicate of #1085.

**Closed as completed by ozten** 2012-02-14 17:35 UTC
Labels: qa:verified
