### ISSUE TITLE
Dialog stuck on "Connecting to Persona" (reps.mozilla.org, firefox aurora)

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3066] opened 2013-03-04 16:39 UTC
Robert Reyes reports in https://bugzilla.mozilla.org/show_bug.cgi?id=847373:

Clicking on the Sign In link from reps.mozilla.org will launch a window for the Persona. But the actual login fields will not appear. Stuck to the almost blank window "Connecting to Persona".

![aurora-signin](https://f.cloud.github.com/assets/532953/217454/23e24958-84ea-11e2-8620-f943f489fe98.png)

**Comment by callahad** [comment] 2013-03-04 17:40
I'm unable to reproduce on old Nightly 21.0a1 (2013-02-01), old Aurora 19.0a2 (2012-12-01), or current Aurora 21.0a2 (2013-03-04).

**Comment by ozten** [comment] 2013-03-07 18:26
Was this a temporary issue?

I'm not able to reproduce.

If this still is happening, can you give exact platform info?

Closing, we need more information to troubleshoot.

**Closed as completed by ozten** 2013-03-07 18:26 UTC
Labels: ★★★★, area:dialog

**Comment by jrgm** [comment] 2013-03-07 18:53
apparently was continuing to happen  - https://bugzilla.mozilla.org/show_bug.cgi?id=847373#c6
