### ISSUE TITLE
Cannot authenticate with dev.myfavoritebeer.org - /api/login always returns null

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#498] opened 2011-10-27 10:45 UTC
Also filed under https://github.com/lloyd/myfavoritebeer.org/issues/27

**Comment by lloyd** [comment] 2011-10-27 15:23
cannot reproduce.  help?

**Comment by lloyd** [comment] 2011-10-27 15:42
naither i no @ioannab can reproduce.  assume this was temporary.  closing.

**Closed as completed by lloyd** 2011-10-27 15:42 UTC
Labels: ★★★★★, qa:verified, qa:needs testcase
