### ISSUE TITLE
BrowserID popup persists after logging in

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#511] opened 2011-11-01 02:34 UTC
This was originally filed as  https://bugzilla.mozilla.org/show_bug.cgi?id=697226

BrowserID popup persists after logging in.  The user has to manually close the popup. This usually happens when I have logged in using different accounts previously.

test account: krupa.mozbugs+100@gmail.com/jabberwocky (I have reproduced this behavior on other accounts as well.)

screenshot on myfavoritebeer.org : http://screencast.com/t/ALnO3nuS2DK

screencast on AMO : http://screencast.com/t/uYiwOGdCVb 

user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:7.0.1) Gecko/20100101 Firefox/7.0.1

**Comment by tonychung** [comment] 2011-11-01 04:45
Persistent popup is a blocker.  We shouldnt ever do that if the user is signed in.

**Comment by shane-tomlinson** [comment] 2011-11-01 10:23
@krupa - Is this still a problem?  Can you reliably reproduce it?  We had a problem last week with this in dev, but the problem should have never made it to prod and we thought it was resolved.  Does it still happen if you disable the Apps addon?

**Comment by shane-tomlinson** [comment] 2011-11-01 10:25
@krupa, so far, I have been unable to reproduce this error.  Does it happen with a fresh profile?  Does the assertion make it back to myfavoritebeer (does it show your beer?)

**Comment by lloyd** [comment] 2011-11-01 15:34
@shane-tomlinson - yes, the assertion _is_ making it back to the calling site.  you can see this in the screencast and the screenshot.

**Comment by lloyd** [comment] 2011-11-01 15:35
@krupa - can you reproduce this issue in any browser other than firefox on the same machine?

**Comment by lloyd** [comment] 2011-11-01 16:21
hey @krupa, first thanks a _ton_ for providing the screencast - it's really helpful to see what you're seeing.  The only thing that is missing for me is the console log that is obscured by the browserid dialog at second ten there's output on the console and I can't tell what it is (and that's the _really_ interesting moment in the show :)

One more note, I'm downgrading this to a _four_ star issue.  Have a look at the (freshly published) priority criteria to get and idea why: https://github.com/mozilla/browserid/wiki/The-BrowserID-Bug-Process

**Comment by krupa** [comment] 2011-11-01 18:07
I am trying to do the following:
- reproduce the issue on a fresh FF profile.
- I will see if this happens in any other browser.

I will report back once I have anything worthwhile. I am fine with the priority assigned to this issue.

**Comment by lloyd** [comment] 2011-11-01 18:08
very cool.  thank you @krupa.

**Comment by krupa** [comment] 2011-11-01 21:55
@lloyd, you mentioned that you wanted the console log. Here is a screenshot of that- http://screencast.com/t/ChEhFwf5y2rb. Let me know if you'd prefer that I pastebin it (I can also get headers).

I have been able to reproduce this issue in two separate firefox profiles but not on a fresh profile. The add-ons I have installed are: Adblock plus, firebug, OWA extension and Live HTTP Headers.

If anyone is in MV, I can show them the behavior on my mac.

**Comment by lloyd** [comment] 2011-11-03 20:59
given that developer tools need to be installed (firebug) and in use (developer tools open), and that there's a user facing work around (close the window or disable firebug) - I'm downgrading to 3 stars.  It would be useful to be able to use firebug on myfavoritebeer, but it shouldn't block important new feature development.

**Comment by krupa** [comment] 2011-11-14 22:17
We plan to release a developer preview on Nov 22. Assuming that we are reaching out primarily to AMO developers, it is not unreasonable to assume that most of them a) use Firefox and have firebug installed. b) use the dev tools pretty heavily.

I am concerned that this might turn into a bad user experience for most of our target audience for the developer preview. Is there a way to get this issue fixed sooner?

**Comment by tonychung** [comment] 2011-11-14 22:21
I spoke with Krupa and she's raising the urgency here of the user impact for AMO developer preview.   She's asking for a fix on the next train to fix if possible.   Reraising priority to 4 stars (since its only firefox affected, but AMO has a lot of them), but feel free to re-triage after taking a second look.

**Comment by shane-tomlinson** [comment] 2011-11-15 08:08
@tonychung, @krupa - is this a platform issue or a browserid specific issue?  By platform I mean, given that a developer has both Firebug installed and the error console open, does any page which opens a window from an iframe using window.open and then attempts to close that window using window.close suffer from the same problem?  We can try to apply a bandaid to BrowserID, but if this window.close is blocked because of a platform bug, we are going to have to think of a creative solution.

**Comment by shane-tomlinson** [comment] 2011-11-15 11:32
@thonychung, @krupa, I have verified that this is _not_ a BrowserID specific problem and at the moment I do not know of a fix.  @lloyd, @benadida - any ideas?

I have filed a Bugzilla issue, it has the test case as an attachment: https://bugzilla.mozilla.org/show_bug.cgi?id=702566

**Comment by benadida** [comment] 2011-11-30 03:12
@tonychung, @krupa : I can see how this would be a hassle for developers, but as @shane-tomlinson mentions, this is a bug in firebug that we cannot control: even the platform team is punting this to firebug. So I think we need to close this and mark it WONTFIX.

I recommend a heads-up in the Apps team developer FAQ.

**Closed as completed by benadida** 2011-11-30 03:12 UTC
Labels: ★★, qa:verified

**Comment by krupa** [comment] 2011-12-01 00:24
Thanks all for looking into this issue.
