### ISSUE TITLE
https://diresworb.org is confusing for a signed in user

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#438] opened 2011-10-17 13:50 UTC
OS: Windows 7, Ubuntu 11.04
Browser: IE9, Opera 11.51, Fx 7.0.1, Chrome 14.0.835.202

STR:
1. Open https://diresworb.org and sign in.
2. Observe the items on this page.

On the right bottom of the page, the "You may, at any time, cancel your account" message is displayed. This message and the link's functionality gives the user the impression that an account is his BrowserID password together with all the added email addresses. Still, the email addresses are listed under the "Your Accounts" section. 

If the perception about the account written above is correct, then the text should not be "Your Accounts" but something like "Your email addresses".

Otherwise, a clear definition should be given for the BrowserID account and all the BrowserID pages should respect it.

**Comment by shane-tomlinson** [comment] 2011-10-20 10:04
#447 was a duplicate of this, which has been closed.  "Your accounts" has been changed to "Your Email Addresses"

**Closed as completed by shane-tomlinson** 2011-10-20 10:04 UTC
Labels: qa:verified
