### ISSUE TITLE
signup of primary on main site /signup fails (404 on static.dev.anosrep.org/lib/winchan.js) 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1937] opened 2012-07-06 05:23 UTC
STR
1. Go login.dev.anosrep.org and click sign in.
2. enter &lt;something&gt;@eyedee.me and click the sign in button (where <something> can be either an existing or unknown address to eyedee.me).
3. screen transitions to show a verify button. Click the button.

Expected: dialog comes up with /authenticate_with_primary, loads /lib/winchan.js and /auth_with_idp/main.js and screen moves to eyedee.me/browserid/sign_in.html?email=...

Actual: dialog to /authenticate_with_primary comes up and is blank

Notes:
1. httpfox shows request to https://static.dev.anosrep.org/lib/winchan.js is 404
2. error console shows Error: WinChan is not defined, Source File: https://static.dev.anosrep.org/auth_with_idp/main.js, Line: 5
3. curl -v https://dev.anosrep.org/lib/winchan.js returns 301 to https://login.dev.anosrep.org/lib/winchan.js but that returns 404
4. this does not happen in current stage or in production
5. I am boring even myself

**Comment by shane-tomlinson** [comment] 2012-07-06 12:11
@jrgm - This issue goes deeper than the winchan problem.  Once the winchan include is fixed, there are problems re-starting the dialog once the user has authenticated with the IdP.  Digging in.

**Comment by shane-tomlinson** [comment] 2012-07-06 12:28
@benadida - The sessionStorage change from PR #1858 breaks authenticating to an IdP from the main site.

https://github.com/mozilla/browserid/blob/dev/resources/static/authentication_api.js#L36-40 shows that completeAuthentication and reaiseAuthenticationFailure are hard coding the return URLs back to the normal authentication dialog, which initially seemed like a good idea.  The problem is when authentication to an IdP occurs from the main site, the IdP is supposed to redirect back to https://login.persona.org/authenticate_with_primary - this is why we had the return_to parameter on the URL.

**Comment by shane-tomlinson** [comment] 2012-07-06 13:24
Marked 5\* since this is a regression.

**Comment by benadida** [comment] 2012-07-06 13:36
I'll get on this today.

**Comment by benadida** [comment] 2012-07-06 13:37
Now... this looks like it's not covered in tests. @shane-tomlinson any chance you can help me there?

**Comment by lloyd** [comment] 2012-07-06 22:48
fixed with PR #1955

**Closed as completed by lloyd** 2012-07-06 22:48 UTC
Labels: ★★★★★, qa:verified

**Comment by jrgm** [comment] 2012-07-07 04:03
works in dev for the original STR. Will need to reconfirm when we get to stage.

**Comment by jrgm** [comment] 2012-08-06 19:06
verified in train-2012.07.30 and in prior. Primary signin works.
