### ISSUE TITLE
Login via persona doesn't work through Safari

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/persona#4066] opened 2014-01-13 13:17 UTC
#### Websites tested on:
- mozillians.org
- bugzilla.mozilla.org
#### OS  : Mac OS X Version 10.9 Build 13A603 (Mavericks).

---
#### Current action:

Clicking the button doesn't open a new window for persona login.
#### Required action:

Clicking the button should open a new window for persona login.

Working perfectly on

**Comment by shane-tomlinson** [comment] 2014-01-13 13:34
@sudheesh001 - I am unable to reproduce:

![screen shot 2014-01-13 at 13 31 13](https://f.cloud.github.com/assets/848085/1900691/0c08df08-7c57-11e3-9474-00df6355619f.png)

Do you have any non-standard settings or any plugins installed?

**Comment by shane-tomlinson** [comment] 2014-01-13 13:35
My Safari version is 7.0.1 instead of 7.0 as noted by @sudheesh001.

**Comment by rashoodkhan** [comment] 2014-01-13 13:42
I can confirm this issue running on OS X 10.9 - Safari 7.0

**Comment by callahad** [comment] 2014-01-13 21:41
Thank you for the detailed report @sudheesh001, and thanks for confirming, @rashoodkhan.

I cannot reproduce the issue. I'm using OS X 10.9.1 (13B42) and Safari 7.0.1 (9537.73.11).

Does anything strange show up in the Error Console (Develop -> Show Error Console)? Does the problem still exist after upgrading to 10.9.1 and Safari 7.0.1? The "Develop" menu can be enabled in Preferences -> Advanced.

**Comment by fmarier** [comment] 2014-01-13 21:52
@sudheesh001 and @rashoodkhan, can you open https://people.mozilla.org/~fmarier/troubleshoot.html and provide a screenshot of what you see there?

**Comment by sudheesh001** [comment] 2014-01-14 02:24
@callahad , Checking from the Dev Tools on Safari, Here is what I get when I click on the Login Via Persona button.

```
[Error] TypeError: 'undefined' is not an object (evaluating 'navigator.id.request')
    login (browserid.js, line 25)
    (anonymous function) (browserid.js, line 82)
    dispatch (cf4ef383e132.js, line 205)
    eventHandle (cf4ef383e132.js, line 172)
```

@fmarier Here is the screenshot of the troubleshooting test.
![screen shot 2014-01-14 at 7 44 21 am](https://f.cloud.github.com/assets/4545925/1907151/f81b3d12-7cc2-11e3-9462-0f019e969908.png)

**Comment by fmarier** [comment] 2014-01-14 02:26
Hm, your sessionStorage and localStorage are not working... Are you running with extra privacy settings?

**Comment by sudheesh001** [comment] 2014-01-14 02:29
Nope. I just have System Proxy settings enabled. (HTTP, HTTPS)

**Comment by callahad** [comment] 2014-01-16 17:48
@sudheesh001 You're not in Private Browsing mode, are you? Also, does upgrading to OS X 10.9.1 / Safari 7.0.1 fix it?

**Comment by callahad** [comment] 2014-01-16 17:50
Triaging as 3-star -- bump to 4 if we can reproduce the issue.

**Comment by sudheesh001** [comment] 2014-01-16 19:41
@callahad , No I am not using Private Browsing. Upgrading to OS X 10.9.1 and Safari 7.0.1 doesn't still fix it. It still doesn't show the new window for the Persona, ends up moving to `www.mozillians.org/en-US/#` as soon as I click on the persona login. Still works fine on, Nightly UX, built from source. Built from `http://hg.mozilla.org/projects/ux/rev/b36251192036`

![screen shot 2014-01-17 at 1 06 31 am](https://f.cloud.github.com/assets/4545925/1934083/bbdbb636-7ee5-11e3-8aeb-2864dbea4e81.png)
![screen shot 2014-01-17 at 1 05 11 am](https://f.cloud.github.com/assets/4545925/1934084/bd242ed8-7ee5-11e3-9baa-2b99d58881ff.png)

**Comment by fmarier** [comment] 2014-01-16 19:58
Something is wrong with @sudheesh001 ' s browser and it would be great to know why localstorage and sessionstorage don't work.

We can't really do much if we can't reproduce it though.

**Comment by callahad** [comment] 2014-01-16 20:25
@sudheesh001 What is the full output of `defaults read com.apple.Safari`? (You may want to double-check and remove personal data before pasting -- especially the "RecentSearchStrings" key)

(Keys that may exist and be particularly interesting: `WebKitStorageBlockingPolicy`, `WebKitDatabasesEnabledPreferenceKey`, and `WebKitLocalStorageEnabledPreferenceKey`)

**Comment by sudheesh001** [comment] 2014-01-17 10:38
@callahad  , After deleting a few sensitive data here is the output of `defaults read com.apple.Safari` ,

```
{
    BookmarksSidebarWidth = 0;
    BookmarksToolbarProxiesWereConvertedForSafari4 = 1;
    CachedBookmarksFileDate = 411559931;
    CachedBookmarksFileDateNanoseconds = 0;
    CachedBookmarksFileDateSeconds = 1382017725;
    CachedBookmarksFileSize = 4490;
    CalSuccessfulLaunchTimestampPreferenceKey = "4.039851e+08";
    ConvertedNewWindowBehaviorForTopSites = 1;
    DidAddReadingListToBookmarksBar = 1;
    DidMigrateNewBookmarkSheetToReadingListDefault = 1;
    DidMigrateTabsToLinksForReaderKey = 1;
    DidMigrateToMoreRestrictiveFileURLPolicy = 1;
    DidMigrateWebKit1Preferences = 1;
    DidReportHistorySettings = 1;
    DidUnsubscribeFromRSSFeeds = 1;
    DomainsToNeverSetUp =     (
        "facebook.com",
        "google.com",
        "twitter.com"
    );
    DomainsWhereAutocompleteOffDeniedSaveOrFillOperation =     (

    );
    DownloadsPath = "~/Downloads";
    DownloadsPathWasConverted = 1;
    ExtensionsEnabled = 1;
    GestureNavSwipeTimeStamp = "4.106228e+08";
    HasPendingDefaultSearchProvider = 0;
    IncludeDevelopMenu = 1;
    LastApplicationCacheMessageTraceTime = "411224051.193188";
    LastExtensionMessageTraceTime = "411358188.729931";
    LastInstalledPlugInsMessageTraceTime = "411358199.834451";
    LastOSVersionSafariWasLaunchedOn = "10.9.1";
    LastSharedLinksMessageTraceTime = "411593959.221687";
    LocalFileRestrictionsEnabled = 1;
    ManagedPlugInPolicies =     {
        "com.AdobeExManDetectLib.AdobeExManDetect" =         {
            PlugInFirstVisitPolicy = PlugInPolicyAsk;
        };
        "com.apple.QuickTime Plugin.plugin" =         {
            PlugInDisallowPromptBeforeUseDialog = 1;
            PlugInFirstVisitPolicy = PlugInPolicyAllowWithSecurityRestrictions;
        };
        "com.google.googletalkbrowserplugin" =         {
            PlugInDisallowPromptBeforeUseDialog = 1;
            PlugInFirstVisitPolicy = PlugInPolicyAsk;
            PlugInHostnamePolicies =             (
                                {

                },
                                {

                }
            );
        };
        "com.google.o1dbrowserplugin" =         {
            PlugInFirstVisitPolicy = PlugInPolicyAsk;
        };
        "com.google.o3d" =         {
            PlugInFirstVisitPolicy = PlugInPolicyAsk;
        };
        "com.macromedia.Flash Player.plugin" =         {
            PlugInDisallowPromptBeforeUseDialog = 1;
            PlugInFirstVisitPolicy = PlugInPolicyAllowWithSecurityRestrictions;
        };
        "com.microsoft.SilverlightPlugin" =         {
            PlugInDisallowPromptBeforeUseDialog = 1;
            PlugInFirstVisitPolicy = PlugInPolicyAllowWithSecurityRestrictions;
        };
        "com.microsoft.sharepoint.browserplugin" =         {
            PlugInDisallowPromptBeforeUseDialog = 1;
            PlugInFirstVisitPolicy = PlugInPolicyAsk;
            PlugInHostnamePolicies =             (
                                {

                },
                                {

                }
            );
        };
        "com.oracle.java.JavaAppletPlugin" =         {
            PlugInFirstVisitPolicy = PlugInPolicyAsk;
        };
    };
    NSNavLastRootDirectory = "~/Desktop";
    NSNavPanelExpandedSizeForOpenMode = "";
    NSNavPanelExpandedSizeForSaveMode = "";
    NSNavPanelExpandedStateForSaveMode = 1;
    NSPreferencesContentSize = "";
    NSPreferencesSelectedIndex = 8;
    "NSTableView Sort Ordering Passwords Preferences" =     (
        ,
        1
    );
    "NSToolbar Configuration BrowserToolbarIdentifier" =     {
        "TB Display Mode" = 2;
        "TB Icon Size Mode" = 1;
        "TB Is Shown" = 1;
        "TB Size Mode" = 1;
    };
    "NSToolbar Configuration NSPreferences" =     {
        "TB Display Mode" = 1;
        "TB Icon Size Mode" = 1;
        "TB Is Shown" = 0;
        "TB Size Mode" = 1;
    };
    "NSWindow Frame BrowserWindowFrame" = "0 95 1438 783 0 0 1440 878 ";
    "NSWindow Frame NewBookmarksSheet" = "554 619 330 187 0 0 1440 878 ";
    "NSWindow Frame Preferences" = "52 133 593 390 0 0 1440 878 ";
    NewBookmarksLocationUUID = "DAFFDBC8-C4C6-46C0-A338-B02AF8C75EE9";
    NewestLaunchedSafariVersion = "537.73.11";
    OneStepBookmarkingLastDestinationUUID = "Reading List";
    OpenWindows =     (
        BrowserWindowControllerMac
    );
    PMPrintingExpandedStateForPrint2 = 0;
    ProxiesInBookmarksBar =     (
        "Top Sites",
        "Reading List"
    );
    RecentSearchStrings =     (

    );
    RegisteredSafariSyncClient = 1;
    RegisteredSafariSyncClientInSafari31Location = 1;
    RemoteConfigurationLastUpdateFailed = 0;
    RemoteConfigurationLastUpdateTime = "411278764.220731";
    SafariGeolocationPermissionPolicy = 1;
    SearchProviderIdentifierMigratedToSystemPreference = 1;
    ShowSidebarInNewWindows = 0;
    SidebarViewModeIdentifier = Bookmarks;
    SuccessfulLaunchTimestamp = "4.116252e+08";
    UserStyleSheetEnabled = 0;
    WebKitDeveloperExtrasEnabledPreferenceKey = 1;
    WebKitPrivateBrowsingEnabled = 0;
    WebKitRespectStandardStyleKeyEquivalents = 1;
    "__WebInspectorPageGroup__.WebKit2ApplicationChromeModeEnabled" = 1;
    "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DefaultTextEncodingName" = "iso-8859-1";
    "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" = 1;
    "com.apple.Safari.ContentPageGroupIdentifier.WebKit2PrivateBrowsingEnabled" = 0;
    "com.apple.Safari.ContentPageGroupIdentifier.WebKit2StorageBlockingPolicy" = 1;
    "com.apple.Safari.ContentPageGroupIdentifier.WebKit2UsesPageCache" = 1;
}
```

Also couldn't find all 3 keys given.
1. `WebKitStorageBlockingPolicy`
2. `WebKitDatabasesEnabledPreferenceKey`
3. `WebKitLocalStorageEnabledPreferenceKey`

**Comment by sudheesh001** [comment] 2014-01-22 03:36
@callahad , @fmarier , 

Update : Tried with another friend's Mac to login via persona using Safari, worked well on Safari on windows. This looks more like a Mac issue.

**Comment by callahad** [comment] 2014-10-31 19:50
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:50 UTC
Labels: ★★★, cleanup-2014
