### ISSUE TITLE
The user cannot log in using BrowserID on Android phone's native browser

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#318] opened 2011-09-27 13:19 UTC
Device: Google Nexus S phone 
OS: Android version: 2.3.4
Browser: native

STR:
1. Open http://beta.myfavoritebeer.org/ in Firefox.
2. Try to log in using BrowserID.

Actual Results:
 When clicking on the Sign in button, a BrowserID "Communicating with server" dialog is displayed. The Signing in dialog is never displayed.

Expected Results:
 The user can log in without any issues.

**Comment by pboos** [comment] 2011-09-29 00:29
I can confirm this issue!
I am having this issue as well on an Android Project (OpenPhoto) where we use a WebView to log in. Clicking on "Sign in" opens the correct page, but does not show any login fields => can not log in.

**Comment by jmathai** [comment] 2011-09-29 05:07
Also confirmed on the OpenPhoto site using the browser on Android 2.3.

It does work using mobile Firefox 7.

 http://current.openphoto.me/

**Comment by shane-tomlinson** [comment] 2011-09-30 10:16
Caused by #325, duplicated elsewhere, closing.

**Closed as completed by shane-tomlinson** 2011-09-30 10:16 UTC
Labels: qa:verified
