### ISSUE TITLE
typing an incorrect password for an existing account gives no feedback

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#353] opened 2011-10-04 21:48 UTC
this is on current dev, with the new design.  I'm not seeing any visual feedback at all when I input an incorrect password.  Steps to reproduce:
1. http://dev.myfavoritebeer.org
2. click `sign in`
3. click `this is not me` if you're currently authenticated
4. type in an email address that you know is already registered
5. type in the incorrect password
6. hit enter or click the button
7. notice that there's no feedback.  wtf?

**Comment by shane-tomlinson** [comment] 2011-10-05 06:58
Duplicate of #335, closing.

**Closed as completed by shane-tomlinson** 2011-10-05 06:58 UTC
Labels: ★★★★★, qa:verified

**Comment by shane-tomlinson** [comment] 2011-10-05 11:18
68943d7ec724a4cb39357ce555bf31021d65a37d adds the authentication error message.  7cf678ce084fe8bf8fd2737cddd5dc41e6c2f8b8 and ffe2737831db9fcaef7ea7111a87e50c65283a05 add an "email already taken" message.

**Comment by shane-tomlinson** [comment] 2011-10-05 13:49
merge e4cfc151d147fd197bab3a82e732c04f5620d9b2 makes the tooltips all fancy.
