### ISSUE TITLE
can't sign-in with stock browser on android

### ISSUE THREAD

**Issue by tracywalker** [mozilla/persona#708] opened 2011-12-05 22:58 UTC
With Android 2.2 stock browser at beta.myfavoritebeer.org, click sign-in

a cert message comes up, click continue.

then I get "We are very sorry, there has been an error" "to retry...

**Comment by jrgm** [comment] 2011-12-05 23:26
After the cert message, Tracy,  is there also a link the "there has been an error" with See more info?

Does that, when you reveal it, say "action: establishing relay. Relay frame could not be found". 

What is the exact URL that you are hitting at diresworb.org (if you are in the popup).

**Comment by tonychung** [comment] 2011-12-05 23:31
I can reproduce this error on the following devices:
- Iphone iOS5 , safari
- Samsung Galaxy S 2, Android 2.3.3, Stock browser

bumping priority up to 5.  this is a shipblocker for mobile devices using stock browser.

Error mentions:  "Relay frame could not be found"

screenshot: http://i.imgur.com/i6z7F.png

Logcat from Android phone: 
12-05 15:34:13.880: DEBUG/FastDormancy(2842):  before ======= ENTER DORMANCY =======
12-05 15:34:13.880: DEBUG/FastDormancy(2842): [FD] ON default: true
12-05 15:34:13.880: DEBUG/FastDormancy(2842): Before mDormFlag: false in getCapaDormancy()
12-05 15:34:13.880: DEBUG/FastDormancy(2842): After mDormFlag: false in getCapaDormancy()
12-05 15:34:13.980: VERBOSE/browser(17100): BrowserActivity.onPageFinished: url = https://diresworb.org/sign_in#9KT4nK2vwebview = android.webkit.WebView@40559318
12-05 15:34:13.985: VERBOSE/browser(17100): BrowserActivity.onProgressChanged: progress == 100 truefalsetruefalse
12-05 15:34:14.485: DEBUG/BookmarkAppWidgetProvider(17100): getBitmap query count=1
12-05 15:34:14.650: DEBUG/BookmarkAppWidgetProvider(17100): setBookmark success=true
12-05 15:34:14.650: DEBUG/BookmarkAppWidgetProvider(17100): getBitmap query count=1
12-05 15:34:14.660: DEBUG/BookmarkAppWidgetProvider(17100): getBitmap query count=1

**Comment by shane-tomlinson** [comment] 2011-12-06 14:47
@tonychung - this appears to be a duplicate of #596 which we said (which I confirmed yesterday with @benadida - see https://github.com/mozilla/browserid/issues/596#issuecomment-2782783) we are not going to resolve yet.  There is a workaround - setting a default browser as @jbonacci has pointed out.

**Comment by lloyd** [comment] 2011-12-16 07:08
please re-test this issue on dev.diresworb.org or dev.myfavoritebeer.org.  I don't _think_ this one is solved with the new window communication implementation that landed tonight, but it's worth a test.

**Comment by martinrevert** [comment] 2011-12-21 04:33
Working smoothly in Android 2.3.7 with stock browser, but having the exact problems of description trying to use this implementation of BrowserID:

https://github.com/jrburke/idme

I don't know what to expect: Could be an implementation problem of that solution or you guys think that I have to wait for this changes to get that solution productive?

thanks!

**Comment by jrburke** [comment] 2011-12-21 06:04
@martinrevert the idme experiment does use a fork of the browserid code, and so the flow is a bit different. I'll follow up with you in [this idme issue](https://github.com/jrburke/idme/issues/1)

**Closed as completed** 2012-03-13 21:44 UTC
Labels: ★★★★, qa:verified
