### ISSUE TITLE
Cannot log in to BrowserId using stock browser on Froyo

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#823] opened 2011-12-29 22:03 UTC
Android Build: 2.2.2
Browser: Stock
Website: http://www.mozillians.org

Steps to Reproduce:
1. Go to the website mentioned above.
2. Click on "Log In"

Actual Results:
New window is opened at connection error page at browserid.org

Expected Results:
New window is opened at browserid hosted sign on page

**Comment by benadida** [comment] 2011-12-29 22:04
@sammybahamas any chance your phone is set up to not have a default browser? There is an Android 2.2 bug related to not having a default browser set.

**Comment by ghost** [comment] 2011-12-29 22:08
There is a 100% chance that my phone is set up purposely to not have a default browser. This sounds like a dupe!

**Comment by ghost** [comment] 2011-12-29 22:10
My device is the LG Revolution, but I don't think that should matter. Also, this sounds like the issue mentioned by Ben.

**Comment by benadida** [comment] 2011-12-29 22:10
@sammybahamas cool, that's reassuring. We're working on the assumption that most users have a default browser setup. That said, this is no longer an issue in android 2.3+. If we can find a workaround for 2.2, we'll definitely let you know.

**Comment by benadida** [comment] 2011-12-29 22:12
this is a dupe of #708 so I will close this one. Note that we may have fixed this in 2.2, but I'm not so sure yet.

**Closed as completed by benadida** 2011-12-29 22:12 UTC
Labels: qa:verified
