### ISSUE TITLE
Error message when tapping on confirmation link

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2052] opened 2012-07-16 13:40 UTC
OS: Android 2.3.4
Browser: Firefox mobile release

Steps:
1. Receive a confirmation email on Gmail
2. Tap on confirmation link

Expected:
Persona sign in page should open

Actual:
Error page is displayed. Please see the screenshot http://imageshack.us/photo/my-images/189/devicez.png/

Unable to reproduce on Stock browser using Gmail or on Firefox mobile using Yahoo

**Comment by lloyd** [comment] 2012-07-19 17:21
jrgm, can you figure out the extent of affected users?

**Comment by jrgm** [comment] 2012-07-19 22:39
I cannot reproduce with android 2.3.4 firefox release and current gmail mobile client

@csuciu - what is the full URL in the browser's urlbar. Do you have the original email? Why is it loading from google.com/gwt.......

**Comment by jrgm** [comment] 2012-07-19 23:18
Oh, duh. Or you're using gmail.com on the phone. Duh. And you said so. Sorry.

**Comment by jrgm** [comment] 2012-07-19 23:32
I sent myself an email with the single line 'https://www.google.com' - When I get that message at gmail.com and click on that link, I get exactly the same error. Don't know what's wrong with gmail.com, but not our bug. Closing.

**Closed as completed by jrgm** 2012-07-19 23:32 UTC
Labels: ★★★, qa:verified

**Comment by jrgm** [comment] 2012-07-20 00:02
I passed along this issue to someone on Fennec to file or find a bug about this in bugzilla.mozilla.org
