### ISSUE TITLE
New User Sign In Flow - No Way Back

### ISSUE THREAD

**Issue by edent** [mozilla/persona#770] opened 2011-12-19 11:28 UTC
I tried the MyFavoriteBeer demo site.  After sign up, there's no way to get back to the site.

Got a pop up, signed in, told me to check my mail.  I minimised the popup, and went to my mail. Clicked the verify link.

Got the message "Your new address is set up and you should now be signed in. You may now close this window and go back to myfavoritebeer.org"

a) MyFavoriteBeer.org isn't clickable - so I've got no way to get back to the site!
b) It's a tab, not a window
c) The pop-up is still present.

Not a great first use experience.

**Comment by shane-tomlinson** [comment] 2011-12-19 11:33
@edent - which browser are you using?

**Comment by shane-tomlinson** [comment] 2011-12-19 11:37
@edent - I just went through the flow again to verify things are working properly, in Firefox 8.0.1 things are as they are supposed to be.  When you checked your email, did you replace myfavoritebeer.org with your email provider?

**Comment by edent** [comment] 2011-12-19 11:41
Firefox 8.0 (Ubuntu)

I got an email through which said

"Thanks for verifying your email address.  This message is being sent
to you to complete your sign-in to http://myfavoritebeer.org.

Finish registration by clicking this link:
https://browserid.org/verify_email_address?token=JgjUfDzwibU9LFwfGq1q50mZetE0Gy9aRy3RW1FZpfwtyEnw"

I clicked on that and it took me to the page which said "thanks,
please close this window".

On 19 December 2011 11:37, Shane Tomlinson
reply@reply.github.com
wrote:

**Comment by edent** [comment] 2011-12-19 17:27
Ah, I use gmail. So I opened mail.google.com in my browser.
On 19 Dec 2011 16:49, "jbonacci" <
reply@reply.github.com>
wrote:

**Comment by shane-tomlinson** [comment] 2011-12-20 09:49
@jbonacci - your explanatory skills are awesome. 

Are we causing user confusion with our sign up flow?

**Comment by lloyd** [comment] 2011-12-22 18:00
this is a duplicate of issue #385

**Closed as completed by lloyd** 2011-12-22 18:00 UTC
Labels: qa:verified
