### ISSUE TITLE
build a mediawiki plugin to support BrowserID

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1229] opened 2012-03-01 17:17 UTC

**Comment by shane-tomlinson** [comment] 2012-03-12 12:58
@benadida - I looked into doing this last year and ran into a roadblock that I had no obvious solution for - currently there is no way of retrieving a user account by email address.  To confirm this was a really a problem, I had a chat with a Wikipedia developer at MozFest - he confirmed my suspicion.  The reason, he explained, is because email addresses are optional in Wikimedia.  I did not pursue the plugin further due to time constraints. 

Any developers interested in writing this plugin - it'd be awesome!  Just be aware that as of Nov 2011 (not sure of the current state), a method is needed to retrieve accounts by email.

**Comment by shane-tomlinson** [comment] 2012-04-19 17:20
Please see: https://github.com/stomlinson/browserid_mediawiki_extension

**Comment by seanmonstar** [comment] 2012-09-24 18:56
closing this. if it's still a problem, please reopen.

**Closed as completed by seanmonstar** 2012-09-24 18:56 UTC
Labels: ★★, qa:verified
