### ISSUE TITLE
The message displayed after confirming an email address should be corrected

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#436] opened 2011-10-17 13:32 UTC
OS: Windows 7, Ubuntu 11.04
Browser: IE9, Opera 11.51, Fx 7.0.1, Chrome 14.0.835.202

STR:
1. Start signing up to BrowserID from the server or a client.
2. After the confirmation email is sent, open it and click on the confirmation link.
3. Enter a password, confirm it and sign in.

The "Thank you signing up with BrowserID. You can now use..." message is displayed. The message should be "Thank you for signing up ..."

**Comment by shane-tomlinson** [comment] 2011-10-20 09:29
#444 is a duplicate of this and has been fixed.  Closing.

**Closed as completed by shane-tomlinson** 2011-10-20 09:29 UTC
Labels: qa:verified
