### ISSUE TITLE
Confirmation emails blocked by Postini (DKIM)

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2668] opened 2012-11-01 03:48 UTC
Confirmation emails from Persona are marked as spam by Postini:

![Postini Junk Folder](https://raw.github.com/gist/3991555/6e6a9ac4a1dd30078ba7c245d986a6184e1d3ad8/persona_emails_blocked_by_postini.png)

**Comment by callahad** [comment] 2012-11-01 06:21
Dupe of #2581, yes?

**Closed as completed** 2012-11-01 16:34 UTC
Labels: qa:verified
