### ISSUE TITLE
Host fonts locally.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1695] opened 2012-06-06 12:54 UTC

**Comment by shane-tomlinson** [comment] 2012-06-06 12:55
The new fonts are hosted locally by several Mozilla properties.  We should get a copy of these and stop relying on Google to provide us with the fonts.

**Comment by callahad** [comment] 2012-06-06 19:40
This looks like a dupe of #908 and/or #769. @shane-tomlinson should you reassign those to yourself and close this one?

**Comment by shane-tomlinson** [comment] 2012-06-07 07:50
Good call @callahad.  I closed the other two in favor of this one.

**Closed as completed** 2012-06-12 17:35 UTC
Labels: ★★★★, qa:verified
