### ISSUE TITLE
Localizing login.persona.org

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1991] opened 2012-07-12 00:41 UTC
We should make login.persona.org localizable. Right now it is half in English half in another language if you visit it with a browser that speaks some other language by default.

/cc @ozten @lloyd

**Comment by seanmonstar** [comment] 2012-07-12 01:05
dupe of #1862

**Comment by shane-tomlinson** [comment] 2012-07-12 07:51
closing as dupe.

**Closed as completed by shane-tomlinson** 2012-07-12 07:51 UTC
Labels: qa:verified

**Comment by mathjazz** [comment] 2012-07-12 08:36
Sorry, let's continue discussion under #1862.
