### ISSUE TITLE
look into using Google's code for popup

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#64] opened 2011-07-15 05:22 UTC
Google has code that does the popup RPC approach in a highly cross-browser compatible way:

https://code.google.com/p/oauth2-postmessage-profile/

We should see if we can replace our popup approach with theirs, so that we can gain IE7 compatibility and more.

**Comment by lloyd** [comment] 2011-08-12 18:13
duplicate of issue #97

**Closed as completed by lloyd** 2011-08-12 18:13 UTC
Labels: qa:verified
