### ISSUE TITLE
"Blank" screen after confirming secondary email

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2103] opened 2012-07-19 06:53 UTC
Steps:
1. add a new secondary email
2. click the confirmation link in email

Expected:

The page that appears should immediately tell me that something is happening and that confirmation is in progress.

Actual:

A "blank" (well, it's themed, but the main part is basically empty) page shows up for 2-3 seconds, then a message shows up saying that the email was confirmed. Then a redirect happens after 5 seconds.

**Comment by shane-tomlinson** [comment] 2012-07-19 15:54
I believe this is caused by #2024

**Comment by callahad** [comment] 2014-10-31 19:54
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:54 UTC
Labels: ★★★, cleanup-2014
