### ISSUE TITLE
browserid.org/verify returns empty reply

### ISSUE THREAD

**Issue by ncalexan** [mozilla/persona#2091] opened 2012-07-18 15:00 UTC
This was moved from https://bugzilla.mozilla.org/show_bug.cgi?id=774924.

The following string is a cert that causes browserid.org/verify to (timeout and) return an empty reply:

<code>eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjEzNDI1Njk4NjcxODAsInByaW5jaXBhbCI6eyJlbWFpbCI6InRlc3RAbW9ja215aWQuY29tIn0sInB1YmxpYy1rZXkiOnsiYWxnIjoiUlMiLCJlIjoiNjU1MzciLCJuIjoiMTAwNzAwMTczNjY0NDg4NTQ4NzE2OTI5OTE0NDM0NzUxNjAyMDkwNjg0NTM1NDIwMzUyODUyNzkyNTIxMjM3MjA5Mjk3Mzc4OTc2ODY2NDgyNzAwODMzOTU4MzAxMTcxNDA4MjQzMTM3ODU5NzEwNjk1NjcwNjYzNjQ1MTAwNTc2OTg4MTE5MzA2MDM5NDY1NjIxNzU5MTQ4NTU2OTg5OTQwNDM1Mzc2NTM0NjQwOTkyNTYzMDgyNDkxOTI1NjgwMTk1MTAyNTYzNzU4MjI1MTkxNDIwMzY0NDYxODY5ODA1NjMxOTk3NjA3MTc3MzYyMTQzODAxNjgzNTM3ODc5NTQxOTA4OTQwODg4MzcyMzMyNDc5OTI4MjkwOTIwMTI1MTQ1NjcyOTk5MDkzMzYxNzIwMTcxIn0sImF1ZCI6bnVsbCwiaXNzIjoibW9ja215aWQuY29tIiwiaWF0IjoxMzQyNTY2MjY3MTgwfQ.LHcJf5MX3vZ30V5Q2JGww0UEpYy5LkQ_iBZ9R9-ehDDnv61aGigwbtXiZdxBz7exAE1G6WZdeRpBQLsSSqOmflhebhpGYB9yhnn1WJTPZ7XcjsuXSHEgFygLs2m3__4JfCJeOPt634PzrviPDzYPKi7RVP1lI7p5kdrDf2yftVx_Uc1kKXjs-JCbkfkwei15ifl-Tqg1h3wUqM1Z4UM3jKA_YpWEHoivlDFuKMoCpGLuqa5MHtSr7oVujWgoqoHzwByyxeUDpBbtXOjHfYGC1E4bajMhD8YLk_PYqEEQqmpYr98SDtc02fMqqTbsId-nNIvoGkevJiSixCZ1SZGZdw~eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjEzNDI1Njk4NjcyMTQsImF1ZCI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDgwIiwiaXNzIjoiMTI3LjAuMC4xIiwiaWF0IjoxMzQyNTY2MjY3MjE0fQ.Q9cY6Q1RhIf1IL2pjzxT4l-lI8nWfTl8rYtC5LD7HF_H8kLge_VzlxhcBVmxq9UnFy4WkHvZuTzWs_7RFI08JNDUnU4pR6kBUATe2M6oahUc0l6PEZm5saOhkZaxRmagQgyLYJoxfux0RJRymVRPL8_5ktw0_Bkj6xGSGPLeYsA</code>

While debugging, I found that the issue might be that:
- one of the signatures had "aud":null in it.
- the signed public key had "alg":"RS" instead of "algorithm":"RS".
- the RSA keys involved were too short.

It seems likely that this input hits a bad path in your validation.

**Comment by benadida** [comment] 2012-07-18 15:04
thanks @ncalexan ! Very helpful.

**Comment by lloyd** [comment] 2012-07-18 16:39
yeah @ncalexan thanks for following up on this!

**Comment by lloyd** [comment] 2012-07-19 16:58
let's understand impact here and what exactly is going on, then decrement accordingly

**Comment by warner** [comment] 2012-07-20 01:58
This is probably similar to the symptoms seen in the (still-private) [bugzilla 770302](https://bugzilla.mozilla.org/show_bug.cgi?id=770302), in which another validation failure (bad base64 padding) threw an exception that wasn't caught and caused a lost-progress condition (the callback was never fired, so the requests just hangs forever. Where "forever" means "after 30 seconds the Zeus load balancer times out and kills the request with a 500".

**Comment by ncalexan** [comment] 2012-07-20 04:46
Brian: as I was debugging this, I first thought it was a base 64 padding issue, and then convinced myself it was not (by hand verifying the segments were correctly base64 url encoded).  It is definitely possible that it was a padding issue, since I was touching a lot of things to try to make progress.  30 seconds and 500 is a legitimate bug, right?

**Comment by warner** [comment] 2012-07-21 00:29
@ncalexan yeah, it's certainly legitimate. What I meant was that 30seconds+500 is the symptom of an uncaught exception, in your case triggered by unusual/bad cert parameters, in the 770302 case by bad base64 padding. It's an unfortunate consequence of the express.js callback style that uncaught exceptions lead to lost-progress rather than immediate errors, which also tends to lose details about the exact error, making it annoying to debug.

**Comment by lloyd** [comment] 2012-07-21 23:34
not a regression, worth understanding and fixing, cannot reproduce ATM (cause underpin.no is offline?)

kicking down to 4 stars

**Comment by jaredhirsch** [comment] 2013-07-25 17:20
link to #2027 - seems like jwcrypto isn't handling errors cleanly?

**Comment by callahad** [comment] 2014-10-31 19:54
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:54 UTC
Labels: ★★★★, cleanup-2014
