### ISSUE TITLE
sign_in dialog: cancel button unresponsive after cancelling out of primary authentication page

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1016] opened 2012-01-31 23:53 UTC
1) Have account1@example.com on beta.myfavoritebeer.org

2) Be signed out of beta.myfavoritebeer.org; click 'Sign in'

3) in the sign_in dialog, enter 'account2@eyedee.me' (and account that you are not logged in at eyedee.me.

4) dialog tells you that you have to verify with eyedee.me; click verify

5) in the eyedee.me/browserid/sign_in, click cancel

6) You return to the 'Verify with email provider' screen. 

7) Click cancel. Nothing happens. Click verify. Nothing happens.
   Only option is to close window, but back on myfavoritebeer,
   the Sign in button is disabled and a page refresh is needed
   to attempt another signin.

**Comment by shane-tomlinson** [comment] 2012-02-01 11:58
Closing as duplicate of #967

**Closed as completed by shane-tomlinson** 2012-02-01 11:58 UTC
Labels: qa:verified, qa:needs testcase

**Comment by jrgm** [comment] 2012-02-03 23:38
vfy dup
