### ISSUE TITLE
Add "add email" button to manage page

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#843] opened 2012-01-04 23:18 UTC
I've heard multiple times from confused users that they'd like to be able to add an email from the manage page on browserid.org.

I know it's not the common case for most users, but for the ones that go exploring (and currently that's a lot, since a lot of web devs are trying it out and exploring the tech) it's sometimes a bit confusing that there's no way to add an email from there.

**Comment by shane-tomlinson** [comment] 2012-01-05 00:02
Closing as duplicate of #421.

**Closed as completed by shane-tomlinson** 2012-01-05 00:02 UTC
Labels: qa:verified

**Comment by ghost** [comment] 2012-02-22 15:15
Verified as duplicate of #421.
