### ISSUE TITLE
IE8: Logout link _completely_ invisible/undiscoverable on beta.myfavoritebeer.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#985] opened 2012-01-26 00:41 UTC
1) Go to http://beta.myfavoritebeer.org and signin.

Expected: when logged-in, the logout link is visible and clickable

Actual: logout link is undiscoverable. This is _not_ the same as it just being
hard to locate (known issue).  On my winxp/IE8 system, I cannot locate the
link, either by selecting all the content to get reverse highlighting, or by
hovering over where it should be (by locating it with Developer Tools). (It
does show up if I switch IE8 to Quirks Mode).

My system is running IE 8.0.6001.18702, on 
WInXP Version 5.1.2600 Service Pack 3 Build 2600, 
on VMWare.

**Comment by jrgm** [comment] 2012-01-26 02:03
No, it's (faintly) visible, and also hoverable, on FF10beta{WinXP, WIn7, OSX, Ubuntu), Chrome16(WinXP, OSX, Ubuntu), and IE9/WIn7

**Comment by shane-tomlinson** [comment] 2012-01-26 13:08
@jrgm - I'm not able to reproduce with WinXP SP3/IE8.

https://skitch.com/set117/ghbnt/winxp-sp3-ie8-running

**Comment by jrgm** [comment] 2012-01-26 17:24
So, it's a function of the length of the email address.

Try set117+x@yahoo.com or set117+xy@yahoo.com

**Comment by shane-tomlinson** [comment] 2012-02-07 16:59
@lloyd - issued two pull requests for this - one to myfavoritebeer.org one to myfavoritebooze.org

https://github.com/lloyd/myfavoritebooze.org/pull/4
https://github.com/lloyd/myfavoritebeer.org/pull/48

**Comment by shane-tomlinson** [comment] 2012-02-21 11:28
Closing as fixed with above pull requests.

**Closed as completed by shane-tomlinson** 2012-02-21 11:28 UTC
Labels: ★★★, qa:verified

**Comment by jrgm** [comment] 2012-02-23 03:43
Actually, I'd been through today on winxp/ie8 on beer|booze, and it works fine now. Thanks @shane-tomlinson

**Comment by jrgm** [comment] 2012-02-23 03:44
(Note: this went live on myfavorite(beer|booze) maybe on Friday).
