### ISSUE TITLE
Broken in b2g 1.2

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/persona#4014] opened 2013-11-06 19:04 UTC
Testing on a 1.2 geeksphone Peak.

STR:
1. Open Tools > App Manager (in FF nightly) (might have to install [adb helper](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Using_the_App_Manager#Adb_Helper_Add-on))
2. Add http://download.atlasct.com/evernav/manifest.webapp as a hosted app
3. Connect to device, accept prompt on phone, push, then run Evernav
4. Go through sign in flow

Expected:
Signed in

Actual:
Sign in window doesn't even show!

**Comment by edwindotcom** [comment] 2013-11-06 22:24
@pdehaan can you try and repro - I'll try on 1.3

**Comment by edwindotcom** [comment] 2013-11-06 22:44
I'm not able to reproduce the issue on 1.3.  I successfully signed in with Persona via App Manager install of EverNav

**Comment by edwindotcom** [comment] 2013-11-06 22:53
I'm on the latest 1.2 Buri device and was able see the sign in window and authenticate as expected the first time.  However, the second time, logout, then sign in, my screen would go black when the keyboard launches upon text input. I'll log this as a different bug.

**Comment by edwindotcom** [comment] 2013-11-06 23:01
related issue: https://github.com/mozilla/browserid/issues/4015

**Comment by callahad** [comment] 2013-11-07 17:38
Tagging as 5-star. @jedp, please re-triage.

**Comment by edwindotcom** [comment] 2013-11-07 18:25
@nickdesaulniers can you paste in any relevant logcat output?  I'm basically unable to reproduce this issue, I think you may be hitting #4015.  I'd like to close this issue out.

**Comment by nickdesaulniers** [comment] 2013-11-07 18:29
Nothing of note in logcat or dmesg.

**Comment by jedp** [comment] 2013-11-22 21:21
I can't reproduce the problem; I downloaded and signed into Evernav; also logged out and logged in again.  However, I don't have a Peak 1.2, and since Geeksphone makes their own builds (and they broke persona on the 1.1 release), we'd need to QA with that build to be sure.

@edmoz if your screen goes black when the keyboard launches, I think you should file that as a keyboard bug in bugzilla!  That does not sound good.

@nickdesaulniers are you able to set preferences on your device?  If so, you can get verbose persona logging with this gaia pref:

```
pref("toolkit.identity.debug", true);
```

Otherwise logcat won't show anything of much interest for persona :(

**Comment by edwindotcom** [comment] 2013-11-22 22:24
@jedp bug logged - though not specifically saying a keyboard issue: https://bugzilla.mozilla.org/show_bug.cgi?id=942331

**Comment by nickdesaulniers** [comment] 2013-11-22 23:00
`lolcat` ?? HA!

**Comment by seanmonstar** [comment] 2014-03-02 19:28
Open 5-star for this long is wrong. Either this should be closed, or de-starred, or fixed asap. I'm guessing it should be closed.

**Closed as completed by seanmonstar** 2014-03-02 19:28 UTC
Labels: ★★★★★, FxOS
