### ISSUE TITLE
Sometimes you must re-enter your password after email verification

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1451] opened 2012-04-17 20:43 UTC
This issue is born out of issue #1440.  It describes a race condition that requires you to occasionally have to re-enter your password after email verification during new account creation.

STR:
1. go to myfavoritebeer
2. click sign in
3. enter a secondary email that has never been used before
4. click verify
5. wait for the email
6. click the link in the email
7. complete the process on the landing page
8. notice that the dialog is now asking you for your password

This is difficult to reproduce, it occurs for stomlinson about 1 in three tries, and from his location requests to our beta servers to `user_creation_status` and `complete_user_creation` take 200ms and 1.2s respectively.  I cannot reproduce the issue in 10 tries and these calls take 100ms and 700ms for me, respectively.

**Comment by lloyd** [comment] 2012-04-17 21:54
this issue should maybe be used as an opportunity to fix all race conditions related to authentication and polling.  like issues #1445 and #1440

**Comment by jrgm** [comment] 2012-04-27 03:34
The STR in GH-1256 are the same (modulo the notes about latency effects here). I'll close that one in favour of this one.

**Comment by shane-tomlinson** [comment] 2012-06-22 13:24
Closing as duplicate of #1555.

**Closed as completed by shane-tomlinson** 2012-06-22 13:24 UTC
Labels: ★★★★, qa:verified, qa:needs testcase
