### ISSUE TITLE
after verifying email address,  /signup, /forgot redirects to /signin

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1682] opened 2012-06-04 23:43 UTC
This only happens for the XUL Fennec client, not for any other browser on Android (FF Beta, Aurora, Nightly, Stock, Chrome Beta). 

STR: 
1. Go to diresworb.org and click sign up; enter a secondary email address, two passwords and submit.
2. Get the email for verify_email_address and open in the same browser

Expected: The /signup page transitions to show the usual logged-in account management UI.

Actual: /signup transitions to /signin and asks for an email address. However the user is logged in at this point, since clicking on a linke to diresworb.org/ will show the account management UI.

adb logcat doesn't show any relevant error.

**Comment by shane-tomlinson** [comment] 2012-06-18 14:50
@jrgm - I did this a bit more generally, the email does not have to be verified in the same browser.  I was able to reproduce this verifying the email in a separate browser on a separate machine.  Digging in.

**Comment by shane-tomlinson** [comment] 2012-06-22 14:07
Link to #1555 - These may have very similar root causes.

**Comment by shane-tomlinson** [comment] 2012-07-26 15:28
I am now getting this for all browsers on the main site for either resetting a password or signing up.

**Comment by jrgm** [comment] 2012-08-14 18:22
Was this mistakenly closed in confusion over GH-2179? I don't see this in dev with FF, Chrome, but I definitely have this with IE8.

**Comment by shane-tomlinson** [comment] 2012-09-28 11:18
This is still reproducible on login.dev.anosrep.org and mistakenly closed as @jrgm says, re-opening.

**Comment by shane-tomlinson** [comment] 2012-09-28 11:20
Updating with modified STR:
1. Go to login.dev.anosrep.org and click sign up; enter a secondary email address, two passwords and submit.
2. Get the email for verify_email_address and open in a different browser.

Expected: The /signup page transitions to show the usual logged-in account management UI.

Actual: /signup transitions to /signin and asks for an email address.

**Closed as completed** 2012-10-17 17:19 UTC
Labels: ★★★★, qa:verified
