### ISSUE TITLE
in mobile sizing, background screen bleeds through to 'Check your email' screen

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3756] opened 2013-08-07 03:10 UTC
Not the end of the world, and the image below is for desktop osx FF23, but I can also see through the foreground screen on android4.3 chrome.

STR
1. Bring up the dialog and enter an unknown secondary address.
2. Enter a password twice and continue. 
3. If on desktop, narrow the window to show the mobile layout. 

Look at the lower right corner and you can see the continue button in the background screen pulse every 3 seconds.

![background-bleed-through](https://f.cloud.github.com/assets/758162/921893/ce2618f6-ff0e-11e2-8393-d68b65a5b2ff.png)

**Comment by callahad** [comment] 2013-08-08 16:39
Ask FxOS people about intended styling of overlays...

**Comment by shane-tomlinson** [comment] 2013-08-12 09:50
Since this screen was never part of the original B2G designs, @mhanratty and I decided to use the error screen. The error screen design is attached, showing the bleed through. Closing as as by design.

![screen shot 2013-08-12 at 10 48 36](https://f.cloud.github.com/assets/848085/946531/6c5b022e-0334-11e3-83d0-c32a2ed19cc2.png)

**Closed as completed by shane-tomlinson** 2013-08-12 09:50 UTC
Labels: ★★★, qa:verified, FxOS

**Comment by jrgm** [comment] 2013-08-12 19:19
Verified. It's still ugly though :P
