### ISSUE TITLE
Sent verification email at a wrong email address

### ISSUE THREAD

**Issue by adamkalis** [mozilla/persona#2237] opened 2012-08-07 00:20 UTC
Steps to reproduce:
1. Go at https://login.anosrep.org/signup
2. Enter a valid email address and press "Verify email"
3. Change the address to another valid (let's say that the user has initially typed a wrong email)
4. Complete the "Password" and the "Verify Password" fields and press "Verify email"

What happens:
The verification email has been sent to the first valid email address (the one at the 2nd step).

What should happen
The verification email should be sent at the correct address (the one at the 3rd step) or the UI should change and don't let the user to change the email address at the 3rd step as it happens at the pop-up Persona window.

**Comment by jrgm** [comment] 2012-08-07 00:58
I can't reproduce this on https://login.anosrep.org/signup. If I am on the screen with "Create Account" and the fields "Email address", "Password", "Verify Password", and the email is filled in with the initial email chosen -- if I then slightly edit the email address or completely replace it, the email is sent to the email of the 3rd step (the edited/replaced one). 

I'm sure you do actually have this issue, but I need a bit more detail to reproduce, including browser+operating-system. Thanks.

**Comment by adamkalis** [comment] 2012-08-07 11:03
I just reproduce it twice on firefox 64bit stable (on my regular profile) and 64bit nightly (on clean profile) at linux (debian testing).

I forgot to say that after the last step I get the message that an email has sent at the changed email (3rd step) but the email actually is sent at the first email.

I rewrite more detailed the steps :)
I will use two emails email1 and email2 which both are not signed up on Persona.
1. Go at https://login.anosrep.org/signup
2. Enter email1 at "Email Address" field and press "Verify email"
3. Enter email2 at "Email Address" field
4. Enter a password at the "Password" and the "Verify Password" fields and press "Verify email"
5. The message says that an email has sent at email2

In my case the email is sent at email1 and not email2.

I'll try later to reproduce it with other OS and/or browsers and I'll come back with the results.

**Comment by shane-tomlinson** [comment] 2012-08-08 15:55
@adamkalis - Thanks for the issue submission.  Can you try your STRs against the current dev environment at https://login.dev.anosrep.org/signin?  We have done a substantial rework to the signin/signup flow for the main site.  Both signin/signup have been merged into the /signin page.

**Comment by adamkalis** [comment] 2012-08-08 16:18
I close this issue as it is now solved. Thanks for the changes!

**Closed as completed** 2012-08-08 16:18 UTC
Labels: qa:verified
