### ISSUE TITLE
POST 400 causing pages to fail to load

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3850] opened 2013-08-30 21:43 UTC
http://cl.ly/image/0T0X0o2D0y2w

I was signed in already when I hit the page. Let me know if you need more details.

**Comment by stevenvergenz** [comment] 2013-09-05 12:45
Confirmed, this is happening on my site too. However, because I make a call to logout() on login failure, my page infinitely refreshes. This has happened multiple times to me on my site.

Two pieces of information may be useful. First, the 400 error only seems to be thrown when the user does not log out and allows the session to remain open for a long time, for me overnight. When I load/reload the page the next morning the 400 error is returned. Second, clearing the persona local storage fixes the problem (for me anyway).

**Comment by jaredhirsch** [comment] 2013-09-05 16:49
4 stars to investigate

**Comment by shane-tomlinson** [comment] 2013-09-05 16:50
relate to #3625

**Comment by shane-tomlinson** [comment] 2013-09-05 16:51
This is actually a dup of #3625, with the Gmail bridge instead of the Yahoo! bridge.

**Comment by callahad** [comment] 2014-10-31 19:51
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:51 UTC
Labels: ★★★★, area:server, cleanup-2014
