### ISSUE TITLE
beta.123done does not finish loading the sign in button on Firefox release on Android 2.2.2

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#3633] opened 2013-07-09 15:56 UTC
Environment:
beta.123done.org
Firefox 22 release
HTC Desire (Android 2.2.2) and LG Optimus 2X (Android 2.2.2)

1 .Load http://beta.123done.org in Firefox

Actual: The loading image just continues to spin, and the sign in button is never shown. 

Expected: The Sign in button should load

**Comment by edwindotcom** [comment] 2013-07-09 16:21
I'm not able to reproduce this on FF 22 on Droid X Android 2.3.3

**Comment by shane-tomlinson** [comment] 2013-07-09 16:42
@csuciu - are your cookies enabled?

**Comment by csuciu** [comment] 2013-07-09 16:57
@shane-tomlinson 
Yes, cookies are enabled.
@edmoz 
I was able to reproduce only on those two 2.2.2 devices.
On Samsung Galaxy R Android 2.3.4 I can't reproduce

**Comment by shane-tomlinson** [comment] 2013-07-09 17:02
@6a68 - hate to put this on you, can you check if stage has the 'native' keyword fix?

**Comment by edwindotcom** [comment] 2013-07-09 17:06
might be 2.2.2 only - I'll try and track one down.

**Comment by edwindotcom** [comment] 2013-07-09 17:09
looks like fix for #3595 is on train 07.03 see: (line 7) https://github.com/mozilla/browserid/blob/dev/ChangeLog so NOT on stage as of now.

**Comment by jrgm** [comment] 2013-07-09 20:51
Note: #3595 is only supposed to happen when using uncompressed javascript (i.e., doesn't apply to stage/prod). 

train-2013.06.19 does contain a different fix for the use of the native keyword - GH-3522
https://github.com/mozilla/browserid/blob/train-2013.06.19/ChangeLog

**Comment by jaredhirsch** [comment] 2013-07-10 17:26
@shane-tomlinson I believe the 'native' keyword issue affects both Android 2.2 and 2.3, which rules out this particular bug. I'll try to reproduce with my 2.2 Galaxy S.

**Comment by jaredhirsch** [comment] 2013-07-10 17:32
@csuciu @shane-tomlinson I can't repro this on stage with my 2.2 handset (_not_ 2.2.2) using FF 22.

I'm inclined to wontfix this; the Android fragmentation long tail is really long.

**Comment by shane-tomlinson** [comment] 2013-07-11 11:22
@csuciu - What make/model of phone is this? Are you using default Firefox settings?

**Comment by csuciu** [comment] 2013-07-11 13:01
@shane-tomlinson  - HTC Desire A8181 and I'm using the default Firefox settings.

I can reproduce also on stock browser/same device:
1. when visiting beta.123done.org, android displays a 'Security warning: There are problems with the security certificate for this site. This certificate is not from a trusted authority.' issued by 'GeoTrust'. 
2. dismiss the warning with 'Cancel'

Actual: The loading image just continues to spin, and the sign in button is never shown.

**Comment by callahad** [comment] 2013-07-11 13:13
Hm. Are we not sending the full cert chain?

**Comment by callahad** [comment] 2013-07-11 16:45
@csuciu Does normal http://123done.org/ work for you?

**Comment by callahad** [comment] 2013-07-11 18:01
(Triage note: if this is only an issue on Beta, then this is a 3-star ops issue to serve the right intermediate cert. If this is also an issue on Prod, then we're in 5-star ops territory.)

**Comment by csuciu** [comment] 2013-07-12 08:35
@callahad - I'm seeing the same behaviour in production (http://123done.org/)

**Comment by callahad** [comment] 2013-07-12 16:09
The GeoTrust root is only included by default in Android &ge; 2.3.

[Android &le; 2.2 requires a cross-root intermediate certificate from Equifax](https://knowledge.geotrust.com/support/knowledge-base/index?page=content&id=SO15937&actp=search&viewlocale=en_US&searchid=1373645110094).

[More than 95% of all active Android devices are on version 2.3 or greater](https://developer.android.com/about/dashboards/index.html).

Since this is a 5% use case for Android, downgrading to 4-stars. Assigning to Gene to install the cross-root intermediate cert.

**Comment by callahad** [comment] 2013-07-12 16:10
@gene1wood Does that sound good to you? Thanks!

**Comment by callahad** [comment] 2013-07-12 16:10
(Nice find, @csuciu!)

**Comment by gene1wood** [comment] 2013-07-12 16:43
@callahad I don't think this is a cert chain issue. We've been aware of the requirement for Android 2.2 for the last year or so and have always served fully chained certs that go back to the old school Equifax cert. You can see here that we're serving certs chained back to Equifax : 

http://www.sslshopper.com/ssl-checker.html#hostname=login.anosrep.org

http://www.sslshopper.com/ssl-checker.html#hostname=login.persona.org

Still trying to think what's causing this but I don't think it's the cert chain.

**Comment by gene1wood** [comment] 2013-07-12 16:47
@csuciu Does the error message literally say "issued by 'GeoTrust'."? I only ask because the immediate issuer's name is "GeoTrust SSL CA" not "GeoTrust"

**Comment by callahad** [comment] 2014-10-31 19:51
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:51 UTC
Labels: ★★★★, cleanup-2014
