### ISSUE TITLE
browserid.org should support optional two-factor authentication

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#56] opened 2011-07-14 23:29 UTC
browserid.org, as the primary (and ideally only) trusted third-party service used as a fallback for browsers without BrowserID support, needs to take great care with the identities it manages, so that other sites relying on BrowserID can count on a high level of security.  In particular, browserid.org should support optional two-factor authentication configured by the user, such as by verifying previously unseen browsers via a different channel (such as the user's email), or by supporting client SSL certificates (again, at the option of the user).  browserid.org should also ideally allow the user to configure a GPG/OpenPGP key to use with the email address, to avoid sending email verification tokens in the clear.

For maximum usability, browserid.org shouldn't necessarily _require_ stronger authentication, but if the user relies on BrowserID to keep all the other services they use secure, then BrowserID needs to support stronger authentication at the user's option.

**Comment by dugsong** [comment] 2011-09-09 15:02
Check out https://github.com/duosecurity - no support for SSL certs or e-mail, though. By design.

**Comment by bct** [comment] 2011-09-09 15:56
It's worth pointing out that Duo Security's service is free for open source projects: http://www.duosecurity.com/pricing

**Comment by swarren** [comment] 2012-01-21 18:06
N-factor authentication would be better. Allow a whole bunch of options, and allow the user to require any arbitrary subset of them (or let them choose to require N of M they've configured, N being the user's own choice). Possible choices:
- Regular password
- Google authenticator code
- RSA keyfob
- SSL client certificate (one popular OpenID site does this, I forget which though)
- Call a telephone number and have the user say yes/no (or enter a passcode)  (one popular OpenID site does this, I forget which though)
- Send SMS containing a one-time code each login attempt
- Send email containing a one-time code each login attempt
- Require user to be on a specific IP subnet (my bank does this, so I can only log in from home or work not some random other network, but I can override this by getting a code through SMS, voice phone, or email)

Also, authentication should expire after some time period, so even if you're still logged in, you need to re-authenticate.

**Comment by joshtriplett** [comment] 2012-01-22 18:14
While I agree that offering several options seems like a feature, I don't think it makes sense to make the process too complicated by having the user choose "N of M", especially not in the default path.  Remember that browserid.org only exists to support browsers without native BrowserID support.  Let's not bikeshed it too much. :)

I'd suggest picking some sensible subset inspired by bank-level security and encouraging that.  Anything beyond that falls in the realm of advanced users, who might find themselves better served by using a browser with native BrowserID support, possibly with extensions adding whatever authentication mechanisms they desire.

**Comment by swarren** [comment] 2012-01-22 19:21
Huh, browserid.org could use some link to the "big picture" background explanation then; I couldn't see anything that implied that the website was just a stop-gap measure.

I wouldn't rely on "bank security" as a good guide; most banks just rely on a user+password which isn't very secure.

**Comment by joshtriplett** [comment] 2012-01-22 19:42
> Huh, browserid.org could use some link to the "big picture" background explanation then; I couldn't see anything that implied that the website was just a stop-gap measure.

Good point.  The documents posted around the launch of BrowserID talked about this quite a bit, but the developer documentation on browserid.org ought to talk about it too.

> I wouldn't rely on "bank security" as a good guide; most banks just rely on a user+password which isn't very secure.

I suppose I meant the banks that actually implement security beyond the norm, which includes all the ones I've worked with.  More generally: pick something sensible based on sites which implement good two-factor authentication.

**Comment by shane-tomlinson** [comment] 2012-09-12 13:38
@callahad - What is your take on this?

**Comment by callahad** [comment] 2012-09-12 16:14
@shane-tomlinson If BigTent covers as many users as we expect it to, adding two-factor auth to our fallback feels moot.

@vthunder -- agree?

**Comment by ozten** [comment] 2012-09-12 16:30
The type of people who are passionate about two factor auth are also the type of people who can host their own IdP today or someday pay for a hosted IdP solution which uses YubiKeys, N-factor auth, etc.

**Comment by callahad** [comment] 2012-09-12 17:21
That seems like consensus. Closing this for now -- our fallback IdP is meant to be temporary, and security conscious users can set up their own IdPs, or use Gmail / Yahoo's two-factor option once BigTent goes live.

**Closed as completed by callahad** 2012-09-12 17:21 UTC
Labels: qa:verified
