### ISSUE TITLE
The Cancel button on the Add Email dialog is non-responsive in Firefox 9

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#781] opened 2011-12-20 15:24 UTC
OS: Windows XP
Browser: Firefox 9

STR:
1. Launch http://beta.myfavoritebooze.org/ in the browser.
2. Sign into a BrowserID account.
3. Click on the "Use a different email" link.
4. Enter an email address already associated to this account.
5. Click on the "Add" button.
6. Click on the "Cancel" button.

The Cancel button is not responsive.

**Comment by shane-tomlinson** [comment] 2011-12-20 16:09
Duplicate of #765 which has not yet made beta.

**Closed as completed by shane-tomlinson** 2011-12-20 16:09 UTC
Labels: qa:verified
