### ISSUE TITLE
it-CH (debug) translation broken in dev env

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1230] opened 2012-03-01 17:30 UTC
steps to reproduce:
1. change your language to it-CH
2. go to dev.myfavoritebeer.org and click sign-in
3. notice that "BrowserID is the fast and secure way to sign in" is not "translated"

**Comment by lloyd** [comment] 2012-03-01 17:30
labeling this five stars, understanding what's broken and why should block rolling `train-2012.03.01`

**Comment by ozten** [comment] 2012-03-01 19:22
This is not a bug.

A string was changed, but we haven't extracted and merged strings yet.

**Closed as completed by ozten** 2012-03-01 19:22 UTC
Labels: ★★★★★, qa:verified
