### ISSUE TITLE
Confusing behavior when trying to add an email already associated to the currently used BrowserID account

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#780] opened 2011-12-20 15:06 UTC
OS: Windows XP
Browser: IE8, Firefox 9.0

STR:
1. Launch http://beta.myfavoritebooze.org/ in the browser.
2. Sign into a BrowserID account.
3. Click on the "Use a different email" link.
4. Enter an email address already associated to this account.
5. Click on the "Add" button.

The "Check your email!" dialog is displayed for 1-2 seconds, then it disappears and the user is logged in with the email he entered at step 4.

An error message should be displayed to let the user know that email is already associated to the current account.

**Comment by shane-tomlinson** [comment] 2011-12-20 16:00
Closing as duplicate of #703, which got fixed last week but has not yet made beta.

**Closed as completed by shane-tomlinson** 2011-12-20 16:00 UTC
Labels: qa:verified, qa:needs testcase
