### ISSUE TITLE
postMessage and header errors in Chrome

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#4083] opened 2014-01-28 13:28 UTC
Reported by @davidascher in the #identity channel. 

Two errors:
1) `Failed to execute 'postMessage' on 'DOMWindow': The target origin provided('https://gmail.login.persona.org') does not match the recipient window's origin ('https://login.persona.org').` in `communication_iframe.js:1`

2) `Refused to set unsafe header "Connection"` in provision.js:43

![screenshot 2014-01-28 11 18 43](https://f.cloud.github.com/assets/848085/2019265/cd0f17b6-881f-11e3-9013-fcceac489d07.png)

**Comment by davidascher** [comment] 2014-01-28 14:41
FYI, the above was on Chrome Canary (34) but I get very similar things on 32.

**Comment by peder541** [comment] 2014-02-07 02:05
These errors seem to pop up if the user hasn't been shown the "Remember You?" screen. They persist after the screen is shown if "This session only" is selected, but I can't reproduce it after selecting "One month."

Errors happen on Firefox under these same circumstances but the console reports something different:
"The X-Content-Security-Policy and X-Content-Security-Report-Only headers will be deprecated in the future. Please use the Content-Security-Policy and Content-Security-Report-Only headers with CSP spec compliant syntax instead."
"This site specified both an X-Content-Security-Policy/Report-Only header and a Content-Security-Policy/Report-Only header. The X-Content-Security-Policy/Report-Only header(s) will be ignored."

**Comment by callahad** [comment] 2014-10-31 19:49
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:49 UTC
Labels: cleanup-2014

**Comment by lucabrunox** [comment] 2015-10-22 20:24
Well I'm having this issue too... any idea to fix it? Is the user really logged in or not?

**Comment by james-odrscoll** [comment] 2015-11-23 05:51
I am getting the same error, was able to recreate the same error with django dev server by calling with 127.0.0.1 instead of localhost:8000.

This puts you into a redirect loop.

**Comment by lucabrunox** [comment] 2015-11-23 08:59
I believe it's a matter of what changes on the server and what persona expects from its cookies and html5 local storage... the problem solved by itself for me, it's only happening sometimes when I update the server. It's some kind of mismatch.
