### ISSUE TITLE
"unknown email address" thrown during initial signup with primary email address

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2838] opened 2012-12-07 23:02 UTC
STR:
1. create a new IDP at https://testidp.org
2. set the idp environment to https://login.dev.anosrep.org
3. use the sample email to login via http://dev.123done.org
4. keep doing #3 until it doesn't work
5. notice "Uncaught Error: unknown email address"

This exception is called right after list_emails is invoked.

**Comment by lloyd** [comment] 2012-12-08 02:46
I can reproduce this on dev every time.  I cannot reproduce this on an ephemeral instance I deployed with the exact same sha - transition.personatest.org

**Comment by lloyd** [comment] 2012-12-08 03:16
Here's what I know:
1. Occurs on dev, minified or not
2. Does not occur on ephemeral instance
3. Occurs on Linux chrome or osx chrome
4. Does not occur in incognito mode
5. Appears that the problem correlates with failed cert key and logout requests from comm iframe
6. Occurs on dev with or without minification

How can this be?   Next step is to disable bigtent on dev and dig into comm iframe

**Comment by shane-tomlinson** [comment] 2012-12-09 19:03
@lloyd - I am unable to reproduce this error as specified in Chrome/OSX. Is there a voodoo incantation that needs to be done?

**Comment by lloyd** [comment] 2012-12-10 18:59
No, it was a flakey temperamental error I spent hours trying to isolate, and upon restart it vanished.  

I don't know if this is a ghost or not.

**Comment by ozten** [comment] 2012-12-12 22:33
I'm also unable to reproduce.

Steps - Did you use 'click' or 'noauth' in your testidp.org?
Did you log out of the dialog and close it, or just 'this is not me' and re-enter your addresss.

**Comment by shane-tomlinson** [comment] 2012-12-13 18:06
Closing down as cannot reproduce, feel free to re-open if found again!

**Closed as completed by shane-tomlinson** 2012-12-13 18:06 UTC
Labels: qa:verified
