### ISSUE TITLE
[b2g] navigator.id.logout() should always call the onLogout handler.

### ISSUE THREAD

**Issue by wraithan** [mozilla/persona#2997] opened 2013-02-07 01:49 UTC
Currently if you are logged in, you can call `navigator.id.logout()` an infinite number of times and it will always call `onLogout`. If you aren't logged in at page load time then hitting `navigator.id.logout()` does not call `onLogout`.

What we'd like for webpay is to always call `onLogout` regardless of the logged in status of the user.

Here are some bugs being caused by this:
https://bugzilla.mozilla.org/show_bug.cgi?id=838812
https://bugzilla.mozilla.org/show_bug.cgi?id=836860

**Comment by seanmonstar** [comment] 2013-02-07 02:16
The `onlogout` handler purposefully only triggers if the state goes from logged in to logged out. If the user isn't logged in originally, then it's not true that there has been an `onlogout` event.

What's the problem you're trying to solve? Is it not possible to know if the user was logged in previously in some specific way?

**Comment by wraithan** [comment] 2013-02-07 06:14
It actually doesn't though, since it will trigger an infinite number of times once a person is logged in. The only case when `onlogout` isn't triggered is when the user was never logged in.

We need to definitely clear the user's cookies then redirect them. We purposefully do the redirect in the `onlogout` handler so we know that their cookies have been removed. AFAIK browserid doesn't give us a way to query if the user is logged in or not. We considered doing something janky like setting a global variable in `onlogin` then checking for it when our logout button is clicked, but thought we'd raise the issue to browserid.

Currently `onlogin` always works regardless of the number of times you call `navigator.id.request()` I'd argue the `onlogout` should work the same way.

**Comment by callahad** [comment] 2013-02-07 17:53
Setting to 4 stars for needing review / consideration.

@seanmonstar and @jedp  -- can you take a look at this? Added [b2g] to title since this impacts marketplace, but please also consider if it would make sense to change our spec / implementation in general.

**Comment by jedp** [comment] 2013-02-07 17:58
It makes sense to me, and I don't think it's marketplace- or b2g-specific in the end.  It seems to me that if an RP assigns an `onlogout` handler, the RP can reasonably expect that if there's a logout button exposed, and the user clicks it, it should call the handler.

**Comment by seanmonstar** [comment] 2013-02-07 18:03
This isn't b2g-specific.

I'll be the contrarian: The `onlogin` should only be triggered if the user completes the login process from `nav.id.request`. If they don't, such as canceling and closing the dialog, it should not call the `onlogin` process. (If it does, that's a separate bug.)

Likewise, `onlogout` should only be called if a user was actually logged out.

@wraithan The root of the problem is not having an easy way of knowing if the user is logged in?

**Comment by callahad** [comment] 2013-02-07 19:29
This needs to make it into MDN, but here's how the API works.

You tell Persona what you believe about the user's state by including a `loggedInUser` parameter in your call to `id.watch`. Persona will always believe that the user wants to be logged in as someone, or wants to be logged out. Persona will then invoke the appropriate callback to harmonize that state.

<table>
<thead>
<tr><td><strong>You Believe</strong></td><td><strong>Persona Believes</strong></td><td><strong>Callback</strong></td></tr>
</thead>
<tbody>
<tr><td>foo@example.com</td><td>foo@example.com</td><td>onmatch</td></tr>
<tr><td>null</td><td>foo@example.com</td><td>onlogin</td></tr>
<tr><td>undefined</td><td>foo@example.com</td><td>onlogin</td></tr>
<tr><td>foo@example.com</td><td>null</td><td>onlogout</td></tr>
<tr><td>null</td><td>null</td><td>onmatch</td></tr>
<tr><td>undefined</td><td>null</td><td>onlogout</td></tr>
</tbody>
</table>

**Caveats:**
1. The `onmatch` callback doesn't actually exist, yet. So instead you'd get nothing in those cases.
2. If both you and Persona think someone is logged in, but disagree on who, then you'll get an `onlogin` callback for the user that Persona believes wants to be logged in.

**Comment by wraithan** [comment] 2013-02-07 19:38
The disagree case where they both believe someone is logged in should be in the table, not listed as a caveat.

The `onmatch` not existing means it should be documented as doing nothing otherwise you confuse users.

**Comment by seanmonstar** [comment] 2013-02-07 21:00
@callahad :+1: \* 1000

**Comment by callahad** [comment] 2013-02-07 21:35
MDN (https://developer.mozilla.org/en-US/docs/DOM/navigator.id.watch) has been updated -- closing this bug. @wraithan, let me know if you guys run into any more issues related to this.

**Closed as completed by callahad** 2013-02-07 21:35 UTC
Labels: ★★★★, qa:verified, area:api
