### ISSUE TITLE
BrowserID does not support internationalized emails RFC 6530

### ISSUE THREAD

**Issue by graingert** [mozilla/persona#1370] opened 2012-03-31 23:05 UTC
Using an email with unicode characters fails, eg `test@example.бг` or `Rδοκιμή@gmail.com` the JS shim alerts that "This field must be an email address."

https://tools.ietf.org/html/rfc6530

At some point the domain should be converted to punycode, at what point is this?

**Comment by graingert** [comment] 2012-03-31 23:09
This also brings up issues where `test@xn--hxajbheg2az3al.xn--jxalpdlp` must be considered the same as `test@παράδειγμα.δοκιμή` throughout the BrowserID stack

**Comment by shane-tomlinson** [comment] 2012-03-31 23:16
@graingert - thanks - this is a duplicate of #1294, closing this one and keeping the original open.

**Closed as completed by shane-tomlinson** 2012-03-31 23:16 UTC
Labels: qa:verified
