### ISSUE TITLE
AGAIN!  exception in l10n code during first page load after VM provisioning

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1080] opened 2012-02-09 06:47 UTC
Now, featuring a new stack trace:

```
TypeError: Second argument must be a string or a buffer.
    at GettextDomain.checkMagick (/home/app/node_modules/node-gettext/index.js:34:14)
    at new GettextDomain (/home/app/node_modules/node-gettext/index.js:10:10)
    at Gettext.addTextdomain (/home/app/node_modules/node-gettext/index.js:221:28)
    at Object.handle (/home/app/code/lib/i18n.js:117:29)
    at next (/home/app/node_modules/connect/lib/http.js:201:15)
    at Object.logger [as handle] (/home/app/node_modules/connect/lib/middleware/logger.js:155:5)
    at next (/home/app/node_modules/connect/lib/http.js:201:15)
    at Object.handle (/home/app/code/lib/heartbeat.js:29:14)
    at next (/home/app/node_modules/connect/lib/http.js:201:15)
    at Object.handle (/home/app/node_modules/express/lib/http.js:84:5)
```

missing mo file?  Given that `i18n.js` line 117 looks like this:

```
    mo_cache[locale].gt.addTextdomain(locale,
                                       fs.readFileSync(mo_path));
```

perhaps I need to define a `debug_lang` for aws deploy? hmm.

```
remote:   "debug_lang": "it-CH",
```

ideas?

**Comment by ozten** [comment] 2012-02-09 06:55
Thanks for assigning to me. I didn't test missing  config. I think I default no config to it-CH. If debug locale, we should switch to our debug locale, so we shouldn't try to load .mo files for it-CH.

I'll look at various config missing and if that causes this issue.

**Comment by lloyd** [comment] 2012-02-09 06:55
no longer to test l10n in dev.  does that make this silly thing a 5 star?

**Comment by lloyd** [comment] 2012-02-09 06:57
omg that's so cool!  I gave it _double_ five stars!  

ozten, not something that needs to be looked at at this late hour, I'm just having fun breaking github's issue labels.

**Comment by ozten** [comment] 2012-02-09 17:05
The issue with a vanilla deploy is deep in node-gettext.
During the exception:
locale=en_US mo_path=/home/app/code/locale/en_US/LC_MESSAGES/messages.mo

The problem is calling equals on a buffer with an array:
magic Buffer de 12 04 95
GettextDomain.bigMagic= [ 149, 4, 18, 222 ]

/home/app/code/locale/en_US/LC_MESSAGES/messages.mo looks reasonable.

Still investigating.

**Comment by ozten** [comment] 2012-02-09 17:44
temporary_preview doesn't exhibit this behavior.

In the same place in node-gettext, the Identical inputs (AFICT from util.inspect)
magic Buffer de 12 04 95
GettextDomain.bigMagic= [ 149, 4, 18, 222 ]

md5sum locale/en_US/LC_MESSAGES/messages.mo 
24fecb88319f62a7a67051da3c7b6118
on both boxes.

**Comment by ozten** [comment] 2012-02-09 19:19
The presence of postprocess 0.2.1 is the root cause of this bug.

It uses buffertools 1.0.7 which is incompatible with node-gettext. It monkey patches equals for buffers... which gettext does also.

**Comment by ozten** [comment] 2012-02-09 19:32
https://gist.github.com/1782430

**Closed as completed** 2012-02-09 20:02 UTC
Labels: ★★★★★, qa:verified
