### ISSUE TITLE
Confirmation for removing last email always displays in English

### ISSUE THREAD

**Issue by merike** [mozilla/persona#2492] opened 2012-09-16 19:59 UTC
When trying to remove my email from Persona (https://translate.personatest.org/) I get:

 Removing the last address will cancel your Persona account.
 Are you sure you want to continue?

This is actually translated for Estonian but never displays. Currently also seeing the same for pl and it for example.

**Comment by shane-tomlinson** [comment] 2012-09-17 13:29
In client.po, this strong looks like:

```
msgid ""
"Removing the last address will cancel your Persona account.\n"
"Are you sure you want to continue?"    
```

In es/client.json, this is converted to:

```
"Removing the last address will cancel your Persona account.\\nAre you sure you want to continue?": [                                                         
    null,
   "Al eliminar la última dirección se cancelará tu cuenta en Mozilla Persona.\\n¿Seguro que deseas continuar?"
],
```

where the original `\n` is converted to `\\n`.

With the added `\`, the string is not correctly matched. Manually removing the extra `\` correctly causes the string to match.

**Comment by shane-tomlinson** [comment] 2012-09-17 13:59
po2json.js is converting `\n` to `\\n`, but I do not yet understand where.

I have made a temporary fix for this in compile-json.sh, but this seems like it should be moved into po2json.js:

```
Index: compile-json.sh
===================================================================
--- compile-json.sh (revision 109156)
+++ compile-json.sh (working copy)
@@ -31,7 +31,8 @@
     jsonfile="$2/${lang}/${stem}.json"
     mkdir -p $2/${lang}
     echo -n ";var json_locale_data = " > $jsonfile
-    $1/po2json.js -p  $pofile >> $jsonfile
+    ## po2json converts \n to \\n. use sed to convert back
+    $1/po2json.js -p  $pofile | sed 's/\\\\n/\\n/g' >> $jsonfile
     echo ";" >> $jsonfile
 done
 rm $lockfile
```

**Comment by jrgm** [comment] 2013-05-13 03:43
Actually, in train-2013.04.26, this text is still always in English despite Chrome or Firefox being in German or Estonian. Sorry, to the late check of this on this train.

**Comment by mathjazz** [comment] 2013-07-11 13:50
2 users reported this is still an issue. Cannot check if it's still the case in the latest train, because of #3646.

**Comment by mathjazz** [comment] 2013-07-12 07:09
#3646 is now fixed and I cannot reproduce this issue anymore. Waiting for localizers to confirm.

**Comment by mathjazz** [comment] 2013-07-12 11:43
Confirmed to be working. This bug can be closed now.

**Comment by jrgm** [comment] 2013-07-12 18:18
Yep. Thanks @mathjazz. Looks right to me in et, de, pl, es, zh-CN. Closing.

**Closed as completed by jrgm** 2013-07-12 18:18 UTC
Labels: ★★★★, qa:verified, area:server
