### ISSUE TITLE
Confirmation email says clicking link will "automatically sign in to" service, but it doesn't

### ISSUE THREAD

**Issue by cpeterso** [mozilla/persona#2600] opened 2012-10-15 21:53 UTC
I wanted to associate a second email address with my existing Persona account. So I went to myfavoritebeer.org and tried to log in with a new email address. I received the confirmation email as expected and it said, **"Click to confirm this email address and automatically sign in to myfavoritebeer.org."**

When I clicked the link, a Persona.org page opened that simply said, **"Your address has been verified!"** and stopped. I expected the page to redirect to myfavoritebeer.org and automatically sign me into myfavoritebeer.org.

When I browsed back to myfavoritebeer.org and refreshed the page, I was still not signed in. I had to manually sign in using my just-confirmed email address.

**Comment by callahad** [comment] 2012-10-15 23:37
Aw, man. Thanks for finding that. Root cause: MyFavoriteBeer uses the old `.get()` API, which doesn't support redirection and automatic sign-in.

**Comment by cpeterso** [comment] 2012-10-16 00:05
I saw the same problem with openphoto.me's confirmation email. Can persona.org customize the confirmation email depending on which API version the website is using?

**Comment by lloyd** [comment] 2012-10-18 16:57
let's drop "automatically" in the email

**Comment by ozten** [comment] 2012-10-18 17:27
Grabbing, will do.

**Comment by lloyd** [comment] 2012-10-18 17:35
merged

**Closed as completed by lloyd** 2012-10-18 17:35 UTC
Labels: ★★★, qa:verified
