### ISSUE TITLE
Slow activation emails from fallback IdP for all Microsoft controlled email accounts

### ISSUE THREAD

**Issue by jamesshore** [mozilla/persona#4058] opened 2013-12-23 21:31 UTC
I've had two subscribers over the last two days complain that they didn't get an activation email from Persona after creating a Persona account. From my records, it looks like they each waited about 30 minutes before complaining.

I've just tried creating a new account myself (at 1:10pm Pacific time on Dec 23rd). As of 20 minutes later, no activation email has arrived.

Is something broken in the fallback IdP?

(PS: I also posted this to the Persona mailing list, but I'm not sure if it went through.)

**Comment by jamesshore** [comment] 2013-12-23 21:34
I'm fairly certain this is specific to the fallback IdP. The two subscribers used @live.com and @outlook.com; my test used @jamesshore.com.

Most of my subscribers use a BigTent email (@yahoo.com or @gmail.com). The last non-BigTent subscription I had was on Dec 21 at 8:44pm Pacific time. Assuming they didn't already have a Persona account, that means this issue is new in the last two days.

**Comment by jamesshore** [comment] 2013-12-23 21:43
I've just heard from one of my subscribers that the activation email came through for them, about 2.25 hrs after subscribing. I haven't seen mine yet (33 minutes after signing up).

**Comment by seanmonstar** [comment] 2013-12-23 21:50
It could be our email queue is blocked up, but I don't have the credentials
to log in and check it.

**Comment by jamesshore** [comment] 2013-12-23 22:13
My test activation email came through after 59 minutes. I've updated the issue title from "No activation emails" to "Slow activation emails."

**Comment by gene1wood** [comment] 2013-12-24 03:13
I'll take a look at the SocketLabs queue

**Comment by gene1wood** [comment] 2013-12-24 03:19
Indeed, we're seeing delayed delivery on emails destined for many microsoft domains (e.g. hotmail.com live.com outlook.com and country localized hotmail.com sites. Note the problem is only affecting microsoft properties. I'll open a ticket with Socketlabs to find out what's going on.

**Comment by gene1wood** [comment] 2013-12-24 03:28
I've opened a critical ticket with Socketlabs (#BJB-343-83383) on this issue

**Comment by jamesshore** [comment] 2013-12-24 03:29
Thanks!

**Comment by gene1wood** [comment] 2013-12-24 17:07
I got word back from our email provider. Microsoft is deferring our inbound emails. I'll continue to try to determine why this is happening.

> Good morning Gene,
> 
> It looks like Microsoft is temporarily rate limiting messages from your server's dedicated IP address.  Here is the SMTP error code we are receiving when attempting to deliver one of these messages which has been deferred:
> 
> "421 PR(ct1) (BAY0-MC1-F26) Unfortunately, some messages from 142.0.176.212 weren't sent. Please try again. We have limits for how many messages can be sent per hour and per day. You can also refer to http://mail.live.com/mail/troubleshooting.aspx#errors."
> 
> When looking into this for you, I was able to determine a few things.  First, your IP address has a very strong reputation with Microsoft overall, and you have experienced very high inbox placement rates at their domains.  Microsoft is somewhat unique in that they do provide Email Service Providers with a bit more information than most ISPs do, including approximate inbox placement rates and IP reputation.  I have attached an image from Microsoft's Smart Network Data Services control panel which is where we retrieve this data.  A result in green means that the IP address experienced >90% inbox placement that day.  Yellow would be for 10%-90%, and red would be displayed if less than 10% inbox placement was achieved.  As you can see, you've experienced >90% inbox placement at Microsoft domains for all qualifying days.
> 
> That being said, it looks like your server has recently seen quite a few complaints from users at Microsoft domains [ https://cp.socketlabs.com/servers/6535/reports/complaints ].  My best inclination is that these complaints may be why Microsoft is temporarily deferring your messages.  Again, this is a temporary deferral, and they are likely just doing so for a short period of time until they can determine whether these higher complaint rates are a new trend or just an anomaly.  The best way to resolve this issue is to ensure that complaint rates remain as low as possible.  Unfortunately, I cannot predict an exact timeframe in which this may be resolved.
> 
> To address your second question regarding when the issue began, it looks like we started receiving these deferrals around 12/22/2013 at 10:30:35 PM EST.
> 
> Please let me know if you have any further questions regarding any of this, and I would be happy to further assist.
> 
> Kind regards,
> 
> ## 
> 
> Matt at SocketLabs

**Comment by gene1wood** [comment] 2013-12-25 01:23
I've added an SPF record in hopes of convincing microsoft that our mail is valid. I'm considering trying to cut us over to Amazon SES since socketlabs support is gone for the holidays

**Comment by seanmonstar** [comment] 2013-12-25 03:08
You rock Gene, I don't care what Lloyd says.

**Comment by gene1wood** [comment] 2013-12-26 07:08
The Socketlabs support department re-opens in about 7 hours. I've asked them to do whatever they can to resolve this. I haven't cut us over to AWS SES as I'm not comfortable doing so without testing in staging first and am hoping that Socketlabs can fix this in the morning and I can avoid calling a firedrill with QA. So far we're up to 8000 microsoft emails delayed.

**Comment by gene1wood** [comment] 2013-12-26 15:54
Socketlabs has done some magic on their side and the issue appears to be resolved. The microsoft domains have all flushed their email through

> Good morning Gene,
> 
> Thank you for your patience regarding this issue during our holiday hours.  We understand the critical nature of the issue you are experiencing, and I have made some temporary changes to the outbound IP address for your Email On-Demand server that appear to have allowed these messages to start flowing.  I am also going to reach out to Microsoft's team to see if we can determine a reason for why these messages are being deferred, and hopefully come up with some sort of resolution.  I will be sure follow up with any details I receive from Microsoft.
> 
> Thank you,
> 
> ## 
> 
> Matt at SocketLabs

**Comment by gene1wood** [comment] 2013-12-26 18:24
Got some further info back from socketlabs. Microsoft doesn't have much insight beyond suggesting we join 2 programs to get feedback when this type of thing happens, but I suspect we can't do that since socketlabs is the email agent not us.

Socketlabs is seeing an increase in "Hard failure rates" though I'm not sure what this is. I'll try to find out more.

Though I don't think this is what is happening, this event does bring to mind the potential attack of someone generating lots of persona fallback accounts with non gmail/yahoo email addresses thereby getting microsoft to block our emails.

> Hello Gene,
> 
> I received a response from Microsoft's support team, but unfortunately they weren't really able to provide any information or resolution to this issue.  Here is their response:
> 
> > Dear Matt
> > 
> > We have completed reviewing the IP(s) you submitted. The following table contains the results of our investigation.
> > 
> > 142.0.176.212
> > We were unable to identify anything on our side that would prevent your mail from reaching Outlook.com customers.
> > 
> > If you are still experiencing deliverability issues, please reply to this email with a detailed description of the problem you are having, including specific error messages, and an agent will contact you.
> > 
> > If this is a new IP space, and you have not yet begun to send mail to Outlook.com users, please reply to this email and one of our support team members will contact you to collect more information.
> > 
> > Regardless of the deliverability status, Outlook.com recommends that all senders join two free programs that provide visibility into the Outlook.com traffic on your sending IP(s), the sending IP reputation with Outlook.com and the Outlook.com user complaint rates.
> > 
> > Junk Email Reporting program (JMRP) When an Outlook.com user marks an email as "junk", senders enrolled in this program get a copy of the mail forwarded to the email address of their choice. It allows senders to see which mails are being marked as junk and to identify mail traffic you did not intend to send. To join, please visit http://support.msn.com/eform.aspx?productKey=edfsjmrpp&page=support_home_options_form_byemail&ct=eformts.
> > 
> > Smart Network Data Services program (SNDS). This program allows you to monitor the ‘health’ and reputation of your registered IPs by providing data about traffic such as mail volume and complaint rates seen originating from your IPs. To register, please visit http://postmaster.live.com/snds/.
> > 
> > There is no silver bullet to maintaining or improving good IP reputation, but these programs help you proactively manage your email eco-system to help better ensure deliverability to Outlook.com users.
> > 
> > Thank you,
> > 
> > Outlook.com Deliverability Support
> 
> While awaiting their response this morning, I continued to look into the issue myself as well.  Here are some observations I found:
> - To address a question you asked previously, it looks like there has been a small trend upward in complaint rates at Microsoft domains specifically in the last 90 days.  Complaints rose from about 0.25% to 0.37% (although this has actually been trending back downward over the past 5 days).
> - Hard failure rates for your Email On-Demand server have been somewhat high, averaging about 14% over the past 90 days.  Typically, we want this number to be as low as possible to achieve the best deliverability, and we definitely recommend a hard failure rate below 10% for this reason.
> - It looks like a significant percentage of your messages are related to the domain "mineshafter.info", particularly "Complete sign-in" messages.  Are all of the addresses being contacted on behalf of this domain verified addresses?
> 
> Again, it looks like temporarily remapping your mail to another outbound IP address was able to get the previously backed up messages delivered, but I would still like to determine the root cause of the issue so that we can work together to prevent it from occurring again going forward.
> 
> Regards,
> 
> ## 
> 
> Matt at SocketLabs

**Comment by bryandonnovan** [comment] 2013-12-30 19:43
I tried registering a new hotmail address -- more than 2 hours later, still no confirmation email received.  Similar reports received from customers.  

I tested the fallback IdP using my vanity domain name, and the email was received instantly, as expected.

**Comment by gene1wood** [comment] 2014-01-02 17:07
The queue has appeared good (not filling with microsoft destined emails) but there were 2 mass deliveries on Monday around 10am PST and noon PST. These could have been flushes of microsoft email that was being delayed prior to Monday 10AM PST. I've started a thread with the identity team here at Mozilla to discuss how to proceed (changing email providers, etc)

**Comment by gene1wood** [comment] 2014-01-06 18:31
We also saw a mass delivery on 12/29 which I hadn't noticed before. We've seen no further flushes and the queue size has remained steady since 12/30

**Comment by callahad** [comment] 2014-01-16 17:39
This has been resolved. Closing.

**Closed as completed by callahad** 2014-01-16 17:39 UTC
