### ISSUE TITLE
Unusual number of l10n do not translate msgid "%s uses Persona instead of usernames to sign you in."

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2869] opened 2012-12-14 01:03 UTC
I was just checking that the dialog came up in most of our localizations. But I noticed that more languages that I would expect, while the reset of the strings in the dialog (in the "prompting for email address" state) were translated, this one was not.

msgid "%s uses Persona instead of usernames to sign you in."

I'm wondering if there is something technical wrong with the files that is hinting to not translate that.

/cc @mathjazz

**Comment by jrgm** [comment] 2012-12-14 01:09
And closing. I was filtering for the languages that are 100% translated on verbatim, but my filter seems to have bit-rotted and was covering languages that are not 100%. Still that string has been in there for a long time, IIRC, and for example it's not translated in French.

**Comment by ozten** [comment] 2012-12-14 01:30
Reopening, because an hour ago I changed a file in SVN.

@mathjazz - Let's double check that the change I made in Bug#809901 won't break us in production.

**Comment by ozten** [comment] 2012-12-14 01:39
For example - check out 'fr'.

There is a string '123done uses Persona instead of usernames to sign you in.' in English. This _is_ a new string, so probably localizers didn't get to it... but it is also a string that was affected by the `#~` bug.

Meaning that before now the dialog said

```
#~ "%s utilise Persona au lieu d'un nom d'utilisateur pour vous identifier."
```

So probably the right thing to do is to go into all .po files and uncomment the new strings. Any ideas why they would have ended up with `#~`?

**Comment by jrgm** [comment] 2012-12-14 02:28
@ozten Actually I was testing in stage with an rpm built last night, so not with current dev or svn.

**Comment by mathjazz** [comment] 2012-12-14 14:04
@ozten, I don't think this is related to Bug#809901. Let's compare FR and SL.

Both locales have the string translated in messages.po:
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/fr/LC_MESSAGES/messages.po
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/sl/LC_MESSAGES/messages.po

Both locales have the same string marked as obsolete in client.po:
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/fr/LC_MESSAGES/client.po
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/sl/LC_MESSAGES/client.po

Anyhow, in FR the string is displayed in English, but in Slovenian it's translated.

I believe that the problem was already spotted by @jrgm. FR is not at 100%, while SL is.

**Comment by ozten** [comment] 2012-12-14 17:23
One last question over at https://bugzilla.mozilla.org/show_bug.cgi?id=809901#c23 and then we can push to production.

**Comment by ozten** [comment] 2012-12-14 17:55
Cool, @mathjazz explained that this string moved from client.po to messages.po.

Confirmed in https://github.com/mozilla/browserid/compare/b90eb77...train-2012.11.23#L215L7

**Closed as completed by ozten** 2012-12-14 17:55 UTC
Labels: qa:verified

**Comment by jrgm** [comment] 2012-12-18 06:29
FR in production looks right to me. verified.
