### ISSUE TITLE
Locale: [sv] The user can't sign into any pages (RPs+server) with BrowserID

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1126] opened 2012-02-15 17:05 UTC
OS: Windows 7
Browser: Firefox 11.0, IE9
Language: Swedish

STR:
1. Load a BrowserID client in the browser.
2. Try to sign in using a valid BID account.
3. Load https://diresworb.org/ in the browser.
4. Try to sign in using a valid BID account.

The user can't sign into any pages (RPs+server) with BrowserID when the language is set to Swedish: 
When trying to sign in from clients, the dialog remains on the Communicating with server... message. 
When trying to sign in/up from the server, your email is removed from the corresponding textbox, then nothing else happens.

After changing the language and restarting the browser, everything works fine again.

**Comment by ghost** [comment] 2012-02-15 17:20
When the language is set to Serbian, the user can sign in/up from the client but he still can't sign in/up from the server.

**Comment by ozten** [comment] 2012-02-15 17:20
This is a duplicate of Issue 1125.

**Comment by ozten** [comment] 2012-03-01 20:33
This sounds like the postprocessing bug.

This works now in stage and production.

**Closed as completed by ozten** 2012-03-01 20:33 UTC
Labels: ★★★★, qa:verified
