### ISSUE TITLE
Interrupting the load of a page triggers onlogout

### ISSUE THREAD

**Issue by madjar** [mozilla/persona#3006] opened 2013-02-13 15:24 UTC
Hello there

I have noticed that interrupting the load a a page by refreshing or clicking a link before the page is fully loaded triggers the `onlogout` callback. This happens in both Firefox and Chromium.

My `watch` call is the following :

```
navigator.id.watch({
    loggedInUser: currentUser,
    onlogin: function(assertion) {
        if (assertion) {
            var $form = $("<form method=POST "+
                "      action='/login'>" +
                "  <input type='hidden' " +
                "         name='assertion' " +
                "         value='" + assertion + "' />" +
                "  <input type='hidden' " +
                "         name='came_from' "+
                "         value='http://localhost:8080/' />" +
                "  <input type='hidden' " +
                "         name='csrf_token' "+
                "         value='6a8d9fe56679633bd1d84506ece60ef68046741d' />" +
                "</form>").appendTo($("body"));
            $form.submit();
        }
    },
    onlogout: function() {
        var $form = $("<form method=POST "+
            "      action='/logout'>" +
            "  <input type='hidden' " +
            "         name='came_from' "+
            "         value='http://localhost:8080/' />" +
            "  <input type='hidden' " +
            "         name='csrf_token' "+
            "         value='6a8d9fe56679633bd1d84506ece60ef68046741d' />" +
            "</form>").appendTo($("body"));
        $form.submit();
    }
```

It is the demo application of pyramid_persona. The login and logout views simply change the cookies.

To reproduce the bug, I hit the refresh button repeatedly and, with the right timing I get logged-out.

Sorry I'm not able to provide a more precise description on how to reproduce, I have troubles investigating because the bug is triggered by leaving the page, so I can't see the state of the page after the bug triggered.

**Comment by seanmonstar** [comment] 2013-02-13 19:08
Marking dupe of #2423

**Closed as completed by seanmonstar** 2013-02-13 19:08 UTC
Labels: qa:verified

**Comment by madjar** [comment] 2013-02-13 19:59
@seanmonstar Hadn't see you last explanation on #2423, and I though they weren't linked. Sorry for the dupe.

**Comment by seanmonstar** [comment] 2013-02-13 20:01
No sorry needed, thanks for adding pressure. More pressure, means we can prioritize better. I was just housekeeping.
