### ISSUE TITLE
Many main site pages not set up for i18n.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1085] opened 2012-02-10 12:07 UTC
Steps to reproduce:

1) Set default language to Spanish [es]
2) go to https://diresworb.org

See screen shot:
https://skitch.com/set117/8yq8s/browserid-main-site-not-translated-spanish

This affects ALL languages.

Looking through all the ejs templates in resources/views, the following are not gettextified.

about.ejs
forgot.ejs
idp_auth_complete.ejs
index.ejs
privacy.ejs
signin.ejs
signup.ejs
tos.ejs
unsupported_dialog.ejs

**Comment by ozten** [comment] 2012-02-14 17:33
This is by design for our first release. See

https://etherpad.mozilla.org/localize-browserid
https://bugzilla.mozilla.org/show_bug.cgi?id=706572

We are in the process of re-designing the public site. This will be properly localized. I'll create a l10n-rebrand milestone and put these bugs in it, as well as closing duplicates.

**Comment by lloyd** [comment] 2012-02-16 18:10
duplicate of GH-1111

**Closed as completed by lloyd** 2012-02-16 18:10 UTC
Labels: qa:verified
