### ISSUE TITLE
L10n preview is not updating

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#2147] opened 2012-07-24 09:43 UTC
The preview site we have used until this train only allows us to preview dialog translations:
http://ozten.com/random/browserid/bid_test.html

Now that we also localize the main site, localizers need l10n preview for it. 

I thought it was https://l10n-preview.diresworb.org/, but it doesn't update automatically when translations get commited to SVN.

**Comment by ozten** [comment] 2012-07-24 14:33
CC @gene1wood

**Comment by mathjazz** [comment] 2012-07-25 10:09
The dialog preview site is also not updated:
http://ozten.com/random/browserid/bid_test.html

Shouldn't this happen automatically, when the new train is cut?

This issue is pretty urgent, becasue ~50% strings have changed in the current train and localizers have nowhere to preview traslations.

**Comment by floatingatoll** [comment] 2012-07-26 05:48
I looked at the logs on the l10n-preview server, and it seems to be both updating regularly in the cron logs and also reflecting the "latest" revision in ver.txt, and the "browserid" (behind the router) node.js process was last restarted moments after the update to the latest commit, r107808.

If someone can suggest other diagnostics that I haven't tried yet, I'd be happy to try them.

```
$ curl https://l10n-preview.diresworb.org/ver.txt | grep locale
locale svn r107808

$ grep '^07/25/12.*complete$' /var/log/locale-update.log
07/25/12-01:54:01: locale-update.sh: update to r107801 complete
07/25/12-01:58:58: locale-update.sh: update to r107802 complete
07/25/12-03:18:58: locale-update.sh: update to r107803 complete
07/25/12-03:29:02: locale-update.sh: update to r107804 complete
07/25/12-04:09:00: locale-update.sh: update to r107805 complete
07/25/12-11:14:02: locale-update.sh: update to r107808 complete

$ svn info /var/tmp/l10n-preview-locale
URL: http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale
Last Changed Rev: 107808

$ cd /var/tmp/l10n-preview-locale; svn log -r 107808:HEAD
------------------------------------------------------------------------
r107808 | tobias_ <fredy@freemail.gr> | 2012-07-25 11:07:53 -0700 (Wed, 25 Jul 2012) | 1 line
Commit from Mozilla Verbatim by user tobias_.: 71 of 106 messages translated (10 fuzzy).
------------------------------------------------------------------------

$ ps auwx | grep bin/browserid
450      12798  0.0  3.3 948908 25464 ?        Sl   11:14   0:25 node bin/browserid
```

**Comment by ozten** [comment] 2012-07-26 06:29
@mathjazz are these the STR?

Steps to Reproduce:

1) Set language to zh-tw (Chinese/Taiwan)
2) go to https://l10n-preview.diresworb.org/about

Expected

All content is localized.

Actual

Only parts of the footer and header are localized.

---

If so, doesn't Issue #1862 (and closed duplicate Issue #2047) need to be fixed first?

**Comment by mathjazz** [comment] 2012-07-26 06:37
@ozten: yes, these are the steps to reproduce.

**Comment by mathjazz** [comment] 2012-07-26 06:41
Strings that appear on https://l10n-preview.diresworb.org/about were extracted and are already available in ~15 languages. So I guess #1862 is not causing the issue.

**Comment by mathjazz** [comment] 2012-07-26 06:46
I can see the json file updated for zh-TW:
https://l10n-preview.diresworb.org/i18n/zh_TW/messages.json

But the strings (e.g. "Persona is flexible") still show up in English:
https://l10n-preview.diresworb.org/about

**Comment by lloyd** [comment] 2012-08-03 00:30
There is a new translation environment we'll be using for now.

URL to main site:  https://translate.personatest.org
URL to website that uses it: http://translate.123done.org
URL to current github SHA and SVN version deployed: https://translate.personatest.org/ver.txt

Updating details:

polls SVN at 5 minute intervals.  When change is detected, update takes about 8 minutes, that means 15 minutes is the maximum expected time between translations being committed and updates being visible.

**Closed as completed by lloyd** 2012-08-03 00:30 UTC
Labels: ★★★★★, qa:verified

**Comment by gion-andri** [comment] 2012-08-03 06:32
Thanks. That's great!
But https://translate.123done.org/ does not seem to work (Unable to connect).

**Comment by lloyd** [comment] 2012-08-03 06:35
ack!  I'm sorry, it's http://translate.123done.org (no ssl)

And when translations are changed, you must wait until https://translate.personatest.org is updated (at this very moment apparently someone has committed translations and the server is updating)

**Comment by gion-andri** [comment] 2012-08-03 06:49
Thanks. It works great!
