### ISSUE TITLE
[IE8] error dialog shows up with solid black background (i.e., not just dimmed)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1485] opened 2012-04-23 21:00 UTC
This is specific to IE8

STR
1) disable cookies in IE8
2) go to https://diresworb.org/signup
3) Enter a never before seen email address and click 'verify email'
4) An error message is shown as expected 'Browserid requires cookies'

However, the rest of the screen is now all black, not just dimmed as in other browsers.

**Comment by shane-tomlinson** [comment] 2012-04-24 08:20
Label 5 star since this is a regression.

**Comment by shane-tomlinson** [comment] 2012-04-24 16:39
Closing - merged into train-2012.04.11 and current dev.

**Closed as completed by shane-tomlinson** 2012-04-24 16:39 UTC
Labels: ★★★★★, qa:verified

**Comment by jrgm** [comment] 2012-04-24 18:06
verified fix on stage for train-2012.04.11 with the latest round of updates
