### ISSUE TITLE
Persona sign in page zoomed in when signing in from bugzilla.mozilla.org

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2008] opened 2012-07-12 14:19 UTC
OS: Win 7
Browser: FF 13.0.1

Steps:
1. Go to bugzilla.mozilla.org
2. Press on Persona 'Sign In' button -> Sign in dialog is open
3. Check the sign in dialog

Expected:
The dialog is properly displayed

Actual:
The content of the page is zoomed in.  After resizing the window, the page turns to normal
Screenshot - http://imageshack.us/photo/my-images/543/signink.jpg/

**Comment by shane-tomlinson** [comment] 2012-07-12 16:47
@csuciu - Thanks @csuciu for the report!  I have been unable to reproduce this.  Can you give us a screen cast of the steps you used to produce this?

**Comment by csuciu** [comment] 2012-07-13 09:11
Here you can find the screen capture - http://www.screencast.com/t/cExasmMq2H
It looks like the size of the sign in window generated from bugzilla.mozilla.org is wrong.

**Comment by jrgm** [comment] 2012-07-20 04:18
Oh, weird. I just brought up the dialog from https://id.etherpad.mozilla.org and the window was in the narrowed state.
But in another FF that I was running on osx desktop at the same time it is not narrowed. 

Top image: FF 16.0.a2 using my "home" profile (i.e., I use it normally and don't muck with it's state for testing).
Bottom image: FF 13.0.1 using a profile that I regularly use but trash at will for testing (so, usually relatively fresh).

So differences are fresh vs. new profile, and ff13 vs ff16

I used to know where FF persists window/site settings, but no longer. I can ask with desktop folks tomorrow. 

Thanks @csuciu for finding this!

![img](https://img.skitch.com/20120720-8nhr6hebkdi3twi94jnsk7jc6w.png)

**Comment by jrgm** [comment] 2012-07-20 04:35
I tried my "home" profile with FF 13.0.1, and I still get the same narrowed width of the dialog. So it would appear this is due to some persisted state in the profile. Weirder yet is that popping the dialog from a different RP than id.etherpad.mozilla.org (e.g, bugzilla.mozilla.org) comes up in the correct full width. o_O

**Comment by shane-tomlinson** [comment] 2012-07-31 12:48
@jrgm - Is your profile zoomed in?

**Comment by jrgm** [comment] 2012-07-31 17:52
@shane-tomlinson "is my profile zoomed in?". Not sure I understand the question.

**Comment by shane-tomlinson** [comment] 2012-07-31 18:01
@jrgm - have you zoomed in on a page using the keyboard or CMD +.  Are those settings persisted across browser resets?

**Comment by shane-tomlinson** [comment] 2012-07-31 18:02
@jrgm - They _are_ persisted across browser restarts.  I just zoomed in two levels, shut the browser down, started back up, and the page was still zoomed in - this seems to occur on a per-domain basis.  Could this have been the problem with this particular profile?

**Comment by jrgm** [comment] 2012-07-31 18:05
Possibly, although I almost never change from the default size in my personal size.

**Comment by jrgm** [comment] 2012-07-31 21:47
So, yeah, that is exactly the issue. I looked in my profile with sqlite3 on content-prefs.sqlite with 

```
select g.name,s.name,p.value from settings as s 
join prefs as p on p.settingID = s.id 
join groups as g on g.id = p.groupID 
where (g.name like '%bugzilla%' or g.name like '%etherpad%' or g.name like '%persona%') order by g.name;
```

and my setting for 'browser.content.full-zoom' on id.etherpad.m.o was 0.9 (zoomed in). If I reset that value in the browser View->Zoom->Reset the dialog lays out at its normal width. If I zoomed in again for id.etherpad.mozilla.org, the dialog came up in a slightly narrower width.

It does seem odd that the text zoom on a given site affects the interpretation of window.open sizes, but that is what happens.

**Comment by jrgm** [comment] 2012-07-31 22:54
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=779335. This seems more like a general issue with Firefox.

**Comment by shane-tomlinson** [comment] 2012-08-13 12:39
@jrgm - since this is upstream, can we close the issue here?

**Comment by jrgm** [comment] 2012-08-13 16:38
I had a random thought that if we knew the devicePixelRatio we could adjust the width and height to compensate. But afaik in Gecko there's no simple call to get that (although it could be binary searched at a cost). So, yeah, I'm going to close this as upstream.

**Closed as completed by jrgm** 2012-08-13 16:38 UTC
Labels: ★★★★, qa:verified, type:upstream
