### ISSUE TITLE
Chrome / Safari call onlogout when onlogin navigates away

### ISSUE THREAD

**Issue by stephank** [mozilla/persona#2423] opened 2012-09-04 13:52 UTC
Our application uses the `watch()` API, and submits a POST form from `onlogin` and `onlogout`. This works fine on Firefox, but causes strange behavior on Chrome and Safari.

The call to `watch()` looks roughly as follows: (This is done in a `jQuery(function() { ... });`)

```
navigator.id.watch({
    loggedInEmail: email,
    onlogin: function(assertion) {
        var form = $('<form/>', {
            method: 'post',
            action: '/login'
        });
        $('<input/>', {
            type: 'hidden',
            name: 'assertion',
            value: assertion
        }).appendTo(form);
        form.appendTo(document.body).submit();
    },
    onlogout: function() {
        var form = $('<form/>', {
            method: 'post',
            action: '/logout'
        });
        form.appendTo(document.body).submit();
    }
});
```

The application has page links directly hooked up to `request()` and `logout()`.

In Chrome, when logging in, the popup opens normally, and I walk through the login process. After the popup closes, `onlogin` is called as usual. However, there's also a call to `onlogout` immediately after, before the page unloads. This does not happen when `form.submit()` is commented.

The net effect is that `onlogout` submits another form, cancelling the first form from `onlogin`. The browser now loads the `/logout` action, which simply redirects back to our login form. When the login form again calls `watch()`, it immediately gets the `onlogin` notification, which now completes successfully. (Ie., no further `onlogout` call in this situation, the `/login` action is called, and our app redirects to the dashboard.)

**Comment by callahad** [comment] 2012-09-04 14:50
Looking into this now...

**Comment by seanmonstar** [comment] 2012-09-05 02:19
Do you happen to have a link to this happening?

**Comment by callahad** [comment] 2012-09-05 02:34
Okay, that's strange. I'm actually seeing a slightly different set of events in Chrome and Safari:
1. Invoke `navigator.id.request()`
2. `onlogin` runs
3. `onlogout` runs
4. `onlogin` runs

/me grumbles

I'm able to reproduce this, and have a minimal case up at https://github.com/callahad/persona-issue-2423

**Comment by seanmonstar** [comment] 2012-09-05 03:21
Some investigation notes:
- When onlogin is triggered, the shim also tells the communication_frame that the dialog_completed. This triggers insice the iframe a request to getSilentAssertion, I guess to make sure everything worked out?
- If I turn on the debugger and step through, everything works.
- If I don't step through, and let it error immediately, I get an error saying the status was 0, which tells me the XHR was cut short. Probably, since the submit is unloading the window, and this killing the iframe, the asynchronous XHR is cancelled? That would then make the iframe think stuff blew up, and triggers a logout message.

Still, this is all speculation, since I can't definitively prove it.

**Comment by stephank** [comment] 2012-09-05 08:18
@callahad That's actually the same sequence of events that I'm seeing. Though, not in 'one sitting', the 3. `onlogout` completes, and the 4. `onlogin` is on a new page.

@seanmonstar I haven't yet seend or found the code on 'the other side' of the iframe, so I can't comment on the details, but that makes a bit of sense. Though, is `getSilentAssertion` something that's called from `request()` and not from `watch()`? There's something different between those two code paths.

**Comment by callahad** [comment] 2012-09-06 16:44
Reassigning to @lloyd since he has more experience with the communication iframe...

**Comment by seanmonstar** [comment] 2012-09-25 22:55
@callahad Do we think this could be a common enough occurance to warrant beta2 nomination?

**Comment by ku1ik** [comment] 2012-10-30 20:58
Same thing happens for me. The code (coffeescript) is following:

``` coffeescript
$ ->
  navigator.id.watch
    loggedInUser: window.browserIdUser

    onlogin: (assertion) ->
      console.log 'onlogin'

      if assertion
        form = $(
          "<form action='/auth/browser_id/callback'>" +
          "<input type='hidden' name='assertion' value='#{assertion}' />"
        )

        $('body').append form
        form.submit()

    onlogout: ->
      console.log 'onlogout'
      window.location = '/logout'
```

With above code following happens when Persona window closes:
- `onlogin` is called, which submits the form
- immediately after submiting the form `onlogout` is called, which redirects to /logout, then to /
- `onlogin` is called, which submits the form
- no further call to `onlogout`, user is signed in correctly

I commented out `form.submit()` and only `onlogin` is being called (correctly).

I'm on Chrome 22. I tried on latest Firefox and there's no such issue there.

**Comment by jrgm** [comment] 2012-10-30 21:04
@sickill is what you're saying above observed between 10:55 PDT and 13:10 PDT today. If so, that was a regression in production that was shipped and reverted. Or was observed outside that window.

**Comment by ku1ik** [comment] 2012-10-30 21:09
@jrgm It was about 30-40 minutes ago, so most likely after 13:10 PDT. I just checked now and the issue is still there.

**Comment by seanmonstar** [comment] 2012-10-30 22:22
Like I said above, this is probably because a request is getting cut short inside the communication_iframe, and we handle the onFailure to mean the user should be logged out.

**Comment by ku1ik** [comment] 2012-10-31 20:17
What are the options for fixing this? I can definitely help with testing (or with fixing if I manage to wrap my head around the code).

**Comment by seanmonstar** [comment] 2012-10-31 20:25
When the dialog completes, it tells the communication iframe, and the iframe checks to see if it needs to generate an assertion: https://github.com/mozilla/browserid/blob/dev/resources/static/communication_iframe/start.js#L110

As that request is happening, and you redirect the page somewhere else, and hence make the XHR cancel, it triggers the onFailure callback: https://github.com/mozilla/browserid/blob/dev/resources/static/communication_iframe/start.js#L67

While likely with most failures we _do_ want it to mark the user as logged out, in this case, we don't.

**Comment by madjar** [comment] 2013-02-21 10:33
I'm am quite surprise that this bug hasn't received more love, since its consequences (at least, the ones described in #3006) seems quite important (potential logout when the user navigates too fast). Thus, I wonder, am I using the observer API wrong, in a way that reveals this bug while it is not a problem in the right way ?

**Comment by rmorlok** [comment] 2013-04-11 04:03
I also encountered this issue in my project. I was able to get around it by by making an AJAX call back up to my product's endpoint to verify the assertion/setup session cookie, and then doing the redirect to the next page on the client side when the ajax call returned. Prevents you from interrupting the response from the persona iframe, and thus triggering the logout failure case.

``` javascript
navigator.id.watch({
    onlogin: function(assertion) {
        $.when($.ajax({
            type: 'POST',
            url: '/persona/assertion/validation/endpoint',
            contentType: 'application/json',
            dataType: 'json',
            data: JSON.stringify({assertion:assertion})
        })).then(function (data) {
            // Redirect where you want to go after login, possibly based on response from server
        });
    },
    onlogout: function() {
        var form = $('<form/>').attr({'method':'post','action':'/logout/endpoint','style':'display:none'});
        $('body').append(form);
        form.submit();
    }
});
```

Can anyone see a problem with doing this?

**Comment by seanmonstar** [comment] 2013-04-11 17:29
You're verifying the assertion on your server with an ajax call, and once
verified, sending the user to a logged in page? Sounds perfectly fine to me.

As long as you don't log in users if the assertion is invalid :)

**Comment by seanmonstar** [comment] 2013-04-16 22:40
will be my first priority starting on Monday

**Comment by rmorlok** [comment] 2013-04-18 04:12
Thanks Sean.

**Comment by stephank** [comment] 2013-04-18 06:37
You rock, Sean.

**Comment by madjar** [comment] 2013-06-26 09:03
@seanmonstar , any update on this ?

**Comment by seanmonstar** [comment] 2013-06-27 15:49
I'd been updating in #2560. I can't reproduce locally, and so I need
information about when the requests fail to know if I can fix it.

**Comment by madjar** [comment] 2013-06-28 08:24
The demo application from [`pyramid_persona`](https://github.com/madjar/pyramid_persona/) have this bug. It may be a good way to reproduce it. The bug appears when the loading of the page is canceled (by navigating away or reloading the page).

If you prefer, I can run it on some host so you can try it.

**Comment by shane-tomlinson** [comment] 2013-07-01 15:52
@seanmonstar - I believe we should be cancelling all in flight XHR requests when a user browses away from the current context. Will an iframe receive an onbeforeunload event when the parent document is closed/or sent to a new URL?

**Comment by seanmonstar** [comment] 2013-07-01 18:36
@shane-tomlinson that may an easier way to solve this than trying to figure out the error code and whatnot.

**Closed as completed** 2013-07-08 18:06 UTC
Labels: ★★★★, area:api
