### ISSUE TITLE
Persona lets you delete your only email

### ISSUE THREAD

**Issue by nomicode** [mozilla/persona#4098] opened 2014-03-01 14:58 UTC
I created a Harp.io account by creating a Persona account with the nslater@apache.org email address. I then subscribed to a Harp.io paid plan.

Today, I was trying to edit my Persona email, but I couldn't find a way to add a new one from the account dashboard. So I deleted my existing email, hoping I could add a new one. But as soon as I did that, Persona logged me out.

So that Persona account is now dead. Completely unaccessible. But that also means that my Harp.io account is completely unaccessible.

So, I created a new Persona account using nslater@tumbolia.org (which is what I had wanted to change my email address to) and added my nslater@apache.org email address. Then I tried to sign in to Harp.io, hoping it would do something smart, and match my Persona identity (via email) to the existing account.

Instead, Harp.io created a new account for me. My old app is gone. My credit card details are locked into an inaccessible account. And there is no way for me to cancel my recurring subscription.

This seems like a pretty serious flaw with Persona to me.

Why doesn't Persona have a way to add email address from the account dashboard?

Why does Persona allow me to remove my last remaining email address? This is guaranteed to make that Persona account inaccessible.

**Comment by nomicode** [comment] 2014-03-02 00:03
Follow-up. It appears that I can create a second Persona account, and add the original email. This does, in fact, allow me to re-access my original Harp.io account.

I'm tempted to close this issue. But I think the original action (allowing me to delete my only email and then logging me out) is very confusing. It threw me into quite a panic.

**Comment by sintaxi** [comment] 2014-03-02 00:50
@nslater sorry for the trouble you had on harp.io. 

Persona is a different paradigm that can at times be confusing. Let me attempt to clarify...

When you authenticate with harp.io (or any other third party using persona), your harp.io account is mapped to your email address and not your persona account. That means that harp.io does not have any opinion which persona account the authentication handshake happens. This is actually a great design decision but is often not expected behaviour because most authentication systems map to an account and the email address is just a property on that account. WIth persona the email address is first-class and the definitive source of your identity. This means persona accounts can be transient and even created/destroyed without affecting your ability to log into 3rd party systems.

I don't think there is an actionable bug here but there may be some take away with how it is communicated within the persona system. Thanks for sharing your experience and voicing your concern.

**Comment by nomicode** [comment] 2014-03-02 02:15
Thanks for the explanation.

However, from the account edit screen, there is no way to add an email. In fact, I had to look high and low through the sparse documentation to find out how to add an email. It seems quite unintuitive to me that you'd add a new email at the point of logging in, and not once you've logged in.

There _is_ an account admin, with a list of emails, and an edit button. So it seems logical that I'd be able to add an email here. Regardless, though, I don't think it should be possible to delete your only remaining email. If it is, logging the user out without any sort of explanation is quite hostile. Perhaps an explanation similar to what you wrote above would do.

**Comment by djc** [comment] 2014-03-02 16:18
The whole setup where a Persona account is something different than just an email address is kind of a crutch, and slated to be removed. This kind of thing should be dealt with by the RP. Apparently the Harp.io folks might not have thought this through completely?

**Comment by nomicode** [comment] 2014-03-02 17:28
What is RP?

This seems like a Persona bug. Again, just to restate:
- Persona does not allow me to add email address from the account admin screen, once I am logged in. But it does have an _Edit_ button, and it does let me remove email addresses. This seems like an issue to me. I had to spend some time reading various pages trying to figure out how to add a new email address. It was not at all obvious to me that this action needs to take place at the point of logging into Persona. It seems to me that adding a new email address is a legitimate action you might want to perform having already logged in.
- The account admin screen lets me remove my _only remaining_ email address, logging me out in the process. This action is very alarming for someone unfamiliar with Persona.

**Comment by djc** [comment] 2014-03-02 17:31
Ah, sorry, Relying Party.

The whole current setup where the fallback Identity Provider (what you see at login.persona.org, that has your account) has some conceptual clashes with the rest of Persona, which is what results in these issues. The fix will be to further limit the number of things you can do with a fallback IdP account (indeed, there probably shouldn't be a concept of "accounts" at the fallback), so the usability issues you're describing here are probably water under the bridge at this point.

**Comment by seanmonstar** [comment] 2014-03-02 19:44
I filed #4099 that would put an end to issues like this.

**Comment by sintaxi** [comment] 2014-03-02 22:51
@djc can you clarify? what is harp.io not doing correctly?

**Comment by djc** [comment] 2014-03-03 07:56
Well, actually, I'm not sure if Noah tried it, but it should be possible to attach multiple email addresses to the Harp.io account in order for the Persona login to work in the face of email address transitions.

**Comment by shane-tomlinson** [comment] 2014-03-03 10:56
@nslater - sorry for the confusion, the lack of an "add email" button from the manage screen is a long-standing issue. For background discussion, please see #421, #386, #1626, #843, and #2461.

The bug with harp.io that @djc is referring to is the fact that you should be able to delete and create a Persona account with the same email address an infinite number of times without affecting your account on Harp.io. The only stable data we pass to the relying party (RP) is an email address. In our world, no other account identifiers exist. If the email address you signed up with before you deleted your Persona account is _exactly_ the same as the email address you signed up with the next time around, Harp.io should see no difference. Note, email capitalization matters.

**Comment by sintaxi** [comment] 2014-03-03 11:51
> Persona account with the same email address an infinite number of times without affecting your account on Harp.io

@shane-tomlinson @djc This is the way it is implemented with harp.io. I think the issue @nslater has was he was thrown off by this behaviour. When he deleted his Persona account he assumed it was lost forever and did eventually recreate a new person account to get back into harp.io but only after some confusion.

**Comment by shane-tomlinson** [comment] 2014-03-03 13:08
Thanks for the clarification @sintaxi!

**Comment by nomicode** [comment] 2014-03-03 13:20
@sintaxi is correct. This was PEBKAC. But the experience was alarming!

**Comment by shane-tomlinson** [comment] 2014-03-03 13:24
@nslater - We'd love some feedback on how we could have made this less of a frustrating experience, with fewer unpleasant surprises.

It sounds like there are at least two areas of concern:
1) Lack of ability to add a new email address from the manage page.
2) Surprise that you could completely delete and recreate a Persona account with no adverse effects on the external site.

**Comment by nomicode** [comment] 2014-03-03 13:34
Two suggestions:
1. Let me add new addresses once I am logged in.
2. Either prevent me from removing my last address, or present a notice telling me that if I create a new Persona account with the same address, I will gain access to all my other accounts.

Note that on this last point: I had initially assumed that this would be the case. This is what I tried. Unfortunately, I got my email addresses mixed up, and so I concluded that it was not possible. This might be helped with in-app docs explaining that this is, indeed, how it is supposed to work.

**Comment by callahad** [comment] 2014-10-31 19:49
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:49 UTC
Labels: cleanup-2014
