### ISSUE TITLE
build privacy policy agreement

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#602] opened 2011-11-18 01:24 UTC
Most sites have a legal requirement to present a privacy policy that users must agree to. It seems like the BrowserID login is a good time to present that policy, especially since the alternative is to add a step to the login flow.

This was brought up by the Mozilla affiliates site.

**Comment by shane-tomlinson** [comment] 2012-01-13 14:38
Closing as a duplicate of #841

**Closed as completed by shane-tomlinson** 2012-01-13 14:38 UTC
Labels: ★★★, qa:verified
