### ISSUE TITLE
On create account, "Confira suas mensagens em %s" is displayed

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3894] opened 2013-09-18 17:18 UTC
Luis Kaufman Silva reports in [Bug 917084](https://bugzilla.mozilla.org/show_bug.cgi?id=917084):

User Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.65 Safari/537.36

Steps to reproduce:

Click in "Identificar-se"
Put the email data
Put password and confirm password
Receive the screen in attachment

![captura de tela de 2013-09-16 19_36_23](https://f.cloud.github.com/assets/532953/1166992/325ffdc6-2086-11e3-85a3-539293a01a5e.png)

**Comment by luis-kaufmann-silva** [comment] 2013-09-18 17:22
thanks for put this in correct place ;)

**Comment by seanmonstar** [comment] 2013-09-18 18:15
dupe of #3859

**Closed as completed by seanmonstar** 2013-09-18 18:15 UTC
Labels: area:dialog, FxOS
