### ISSUE TITLE
IOS5 - Sign In with iOS5 results in weird tab behaviour

### ISSUE THREAD

**Issue by rtilder** [mozilla/persona#425] opened 2011-10-14 17:05 UTC
Odd behaviour based on tab focus in iOS5 on a 1st gen iPad results when trying to sign in to beta.myfavoritebeer.org

Reproduce:
1. Go to _beta.myfavoritebeer.org_ in Mobile Safari
2. Click the Sign In image
3. A new tab will open with an _about:blank_ URL
4. This tab will remain a blank page until one attempts to return to the _beta.myfavoritebeer.org_ tab.  Not any other tab, just the tab with _beta.mfb.org_
5. The recently created _about:blank_ tab will immediately take focus and load _https://diresworb.org/sign_up#_.

This doesn't appear to be a timing issue.  I've tried this multiple times with the longest I waited before attempting step 4 being greater than 30 seconds.

**Comment by patricksan** [comment] 2011-10-14 21:15
I'm having the same problem with iOS5 on iPhone 4.
It is definitely a bug when used on Safari iOS 5.

https://github.com/openphoto/mobile-ios/issues/42

**Comment by shane-tomlinson** [comment] 2011-10-20 17:05
Duplicate of #442.

**Closed as completed by shane-tomlinson** 2011-10-20 17:05 UTC
Labels: ★★★, qa:verified
