### ISSUE TITLE
Lots of cancelled network requests in Chrome (from prefetches)

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3561] opened 2013-06-19 22:56 UTC
Looks like the `<link rel="prefetch">` tags in the head of the communication iframe are causing quite a bit of console noise:

http://cl.ly/image/3v3E0I0Z2G2L

I don't know how you're generating the iframe, but perhaps the iframe is being generated twice and the first one is destroyed before any of the requests can be made? (I'm just speculating)

**Comment by vladikoff** [comment] 2013-06-19 22:59
Some notes on this at  http://stackoverflow.com/a/13459106/216672

> > - The DOM element that caused the request to be made got deleted (i.e. an IMG is being loaded, but before the load happened, you deleted the IMG node)
> > - You did something that made loading the data unnecessary. (i.e. you started loading a iframe, then changed the src or overwrite the contents)
> > - There are lots of requests going to the same server, and a network problem on earlier requests showed that subsequent requests weren't going to work (DNS lookup error, etc)

**Comment by shane-tomlinson** [comment] 2013-06-20 17:17
@fmarier - what do you think here, is this a problem or expected behavior?

**Comment by fmarier** [comment] 2013-06-22 03:01
Is this only visible in the dev tools? Or does it affect the throbber as well?

I mean, it's not really a problem that the browser decides to cancels a bunch of optional network requests. That's kind of the idea behind prefetching: load these things if the network is idle, otherwise don't bother. It's a bit unnecessary/noisy to show that in the console I guess, but I'm not really worried about it.

That said, if it's a sign that we're doing something weird with the iframe and that the prefetching broke, then we should investigate.

**Comment by mattbasta** [comment] 2013-06-22 03:22
I would be less concerned if it didn't happen on every request. It happens
without fail on every page load.

**Comment by fmarier** [comment] 2013-06-22 03:25
Then it's probably worth looking into. It's either a Chrome bug or something weird we're doing with the iframe. I don't remember seeing that when I was testing the pull request for it.

**Comment by brainstorm** [comment] 2013-12-16 10:57
I'm actually having the same problem while using `django_browserid` in my Django app. Even if persona itself works without much issues, assets like the button/logo are not shown in my web, namely (according to Chrome's developer tool):

```
  <link rel="prefetch" href="https://static.login.persona.org/v/937bf3893a/production/sv/dialog.js">
  <link rel="prefetch" href="https://static.login.persona.org/v/0a008947f9/production/sv/dialog.css">
  <link rel="prefetch" href="https://static.login.persona.org/v/4c35c324fb/common/i/grain.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/3ffe5e62d2/dialog/i/persona-logo-transparent.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/8a83ded1a4/dialog/i/arrow_grey.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/ace06c36a7/common/i/button-loader.gif">
  <link rel="prefetch" href="https://static.login.persona.org/v/ccd9128527/common/i/button-arrow.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/aa7b97aed0/common/i/button-arrow-hover.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/043be45f4d/common/i/button-arrow-active.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/0a9faad451/dialog/i/persona_watermark.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/77e5d5d4c5/dialog/i/persona_watermark_sm.png">
  <link rel="prefetch" href="https://static.login.persona.org/v/29d9e089cb/dialog/i/persona_watermark_dark_sm.png">
```

:-/

**Comment by jlzg** [comment] 2014-06-30 04:15
for my application, the prefetch is aborted because, in same page, another (real) request to the specific resources started.

**Comment by callahad** [comment] 2014-10-31 19:51
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:51 UTC
Labels: ★★★, cleanup-2014
