### ISSUE TITLE
Wrongly escaped string in the "you must enable cookies" screen

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3050] opened 2013-02-26 04:59 UTC
The link to SUMO is escaped and raw HTML is displayed when cookies are disabled:

![doubly_escaped_cookie_error](https://f.cloud.github.com/assets/167821/195035/351abe30-7fd1-11e2-90e2-62e701c9bd07.png)

**Comment by jrgm** [comment] 2013-02-26 05:08
Duplicate of GH-2979. Closing as dup.

**Closed as completed** 2013-02-26 08:45 UTC
Labels: qa:verified
