### ISSUE TITLE
database problems, marketplace/partners affected

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3669] opened 2013-07-16 20:25 UTC
Five-star to investigate.

See https://bugzilla.mozilla.org/show_bug.cgi?id=894466 for the report that started it all.

**Comment by jedp** [comment] 2013-07-16 20:31
IRC log begins here: http://irclog.gr/#show/irc.mozilla.org/identity/296506

**Comment by gene1wood** [comment] 2013-07-16 20:40
db servers in us-east-1 didn't have their EBS volumes mounted for some reason and so were writing to local storage which filled up. additionally our monitoring detected the problem but didn't alert. I'll be
- fixing the mount issue
- fixing replication
- undraining us-east-1
- fixing alerting

**Comment by jrgm** [comment] 2013-07-16 20:45
With replication broken in one region, users making changes (change password, delete user, new account, add user to account) would have experienced failures in those actions. Regular signin to relying parties would not have been affected.

**Comment by jedp** [comment] 2013-07-16 21:01
@krupa reported new accounts failing when trying to purchase the Jaxogram app.  STR were:
1. launch marketplace (prod)
2. change region in marketplace to Spain (gears button) and save changes
3. search for jaxogram
4. try to purchase with a new email

Both @vladikoff and I tried: We succeeded to create a new unverified email and went on with no errors to the purchasing flow.  @krupa and testing partners, however, continued to have problems.  Waiting to hear back if it's still an issue with testers.

**Comment by gene1wood** [comment] 2013-07-16 21:28
Of the 3 databases that users read from in us-east-1, one of the databases (the local master) was and is still working correctly. One of the databases (a local slave) filled it's drive yesterday at 3:02PM PDT at which point it stopped receiving replicated writes. One of the databases (a local slave) filled it's drive today at 7:52am PDT at which point it stopped receiving replicated writes.

At 12:52pm krupa reported problems to #identity
At 1:06pm jrgm called me while I was on my motorcycle
At 1:13pm I got off my bike and saw the missed call and called jrgm back
At 1:16pm I reached jlaz asking him to drain us-east-1
At 1:20pm he drained us-east-1
At 2:18pm I blocked the listeners on us-east-1 webheads to prevent anyone (even those not respecting DNS) from getting to persona in us-east-1 

This means that globally from 7/15 at 3:02pm through today at 7:52am potentially 16.6% of db reads would be going to a database that did not have the newest writes replicated to it. From 7:52am today until 1:20pm potentially 33.3% of db reads would be going to a database that did not have the newest writes replicated to it.

At 2:46pm after repairing all of the DBs, I re-enabled traffic at us-east-1

**Comment by jedp** [comment] 2013-07-16 21:31
@krupa reports that she and folks in Poland could log in.  Closing this.  Thanks, everyone, for jumping in and fixing.

**Closed as completed** 2013-07-16 21:31 UTC
Labels: ★★★★★

**Comment by gene1wood** [comment] 2013-07-16 21:57
The root cause of the monitoring failure to alert when it should have about the replication issue is this
- 2 months I discovered a bug in our automatic monitoring self registration which caused hosts to register with all notifications disabled
- I fixed this bug here : https://github.com/gene1wood/opsview_client/commit/290ed9b2ff9348359fcdb6c6090c1381ef84fe16
- I manually went through to take existing hosts that had self-registered and set themselves to not notify and set notifications on
- I somehow missed the 3 database hosts in us-east-1 so they were set with notifications off.

I've now manually set their notifications on and audited the 1 other long lived host in each datacenter which was set correctly.

The root cause of the drive filling is also user error on my part. I created EBS volumes for these databases and failed to add them into /etc/fstab and mount them. As a result, MySQL was writing to the smaller local boot volume instead of the separate data EBS volume.

End cause, user error on my part for fixing the monitoring bug but failing to go back and address all the systems that had been affected by the bug as well as user error on my part in failing to complete the process of establishing and mounting the MySQL data drives.
