### ISSUE TITLE
privacy policy render issues with BetterPrivacy add-on

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#856] opened 2012-01-10 02:51 UTC

**Comment by shane-tomlinson** [comment] 2012-01-13 11:34
@benadida - I am not seeing anything strange - is there a screenshot or steps to reproduce?

**Comment by benadida** [comment] 2012-01-13 23:39
this was reported by a Mozillian whose email I'm having trouble finding....

**Comment by jrgm** [comment] 2012-01-15 08:35
@benadida: Not sure what this bug is about exactly. But a quick note.

The BetterPrivacy extension (v1.67 on AMO) detects the Firefox major version
incorrectly. So FF >= 10.x are detected as FF 1.0. (See getFFMainVersion()
in content/bprivacy.js in the .xpi file).

So, in current Beta(10.x)/Aurora(11.x)/Nightly(12.x) channels, BP reverts to
a behaviour intended for FF < 4.x where it literally deletes the
'webappsstore.sqlite' file from the user's profile on every new window!
Good luck with using (local|session)Storage for browserid or anything ;-)

(This also depends on the new permissive addon checking behaviour, which
I think is in FF10.x).

If this is the issue, then it's broader than just browserid, of course. I'll
figure out who in extensions & AMO to talk to after the  weekend.

**Comment by shane-tomlinson** [comment] 2012-01-16 09:24
@jrgm - Thanks for the updated details - with Firefox 10 Beta (today's) and BetterPrivacy 1.67, I am showing no problems on browser restart.  If I sign in to my BrowserID account and restart the browser, all emails are still shown.  We are using localStorage as a local cache, If localStorage is deleted on every restart of the browser but the session cookie remains then when BrowserID restarts, it will re-sync its emails with the backend and generate new keypairs as necessary (when an address is selected).

**Comment by shane-tomlinson** [comment] 2012-01-16 09:25
@jrgm - ah yeah, now I'm getting some very wack behavior.  Will investigate further.

**Comment by jrgm** [comment] 2012-01-16 09:29
@shane-tomlinson So, it's not on browser restart that localStorage is deleted (although that happens too). It's on every new window.

**Comment by shane-tomlinson** [comment] 2012-01-16 09:34
@jrgm - The problem I am seeing reproduces reliably under the following conditions.

1) Start with a new profile
2) Install the BetterPrivacy addon
3) Restart browser.
4) Open one tab to https://diresworb.org
5) sign in using the "sign in" button - notice the redirection to "/" and your email addresses are shown.
6) Refresh the page - email addresses are still there.
7) Open another tab to "http://beta.myfavoritebeer.org"
8) Sign in using BrowserID.
9) Go back to tab with "https://diresworb.org"
10) Refresh page - all addresses are gone.
11) Refresh "http://beta.myfavoritebeer.org" - it's all messed up too.

EDIT (add new steps):
12) Restart Browser
13) Go to "https://diresworb.org" - all email addresses are again available.

**Comment by jrgm** [comment] 2012-01-16 09:56
@shane-tomlinson 

Actually, for me following the above with FF10 (beta), I don't succeed at sign in at step 8. Error console shows

Error: uncaught exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMStorage.removeItem]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: https://diresworb.org/shared/storage.js :: clear :: line 53"  data: no]

I get the same with steps 9,10,11 above though. And 12, 13 too.

**Comment by jrgm** [comment] 2013-02-28 07:49
This can be closed. Closing.

**Closed as completed by jrgm** 2013-02-28 07:49 UTC
Labels: ★★★, qa:verified
