### ISSUE TITLE
Persist selection of email address in selection window

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#340] opened 2011-09-30 16:34 UTC
If i choose a second email address to sign into, the selection on the UI should default to checking the email address i chose, not my previous one. 

For example, i have a emailA@home.com and emailB@work.com, both registered on browserID.   If i sign in with emailB@work.com, it takes me to the email selection window, but emailA@home.com is the default selection checked.    It should be emailB, since thats the one i signed in with.  and so forth with any additional emails.

REpro:
1) create 2+ email address in browserID
2) goto beta.myfavoritebeer.org, and sign in with your 2nd email address
3) Verify the email address chooser selects the first one on your list by default, and not your second

Expected:
- whichever your email address you chose to sign in to, should be the default one selected when choosing the email

Actual:
- the very first email address is checked, even though it wasnt the one you signed in with.

**Comment by tonychung** [comment] 2011-09-30 16:42
I can see the case if a user has like 5 different email personas, choosing which one they used to log into should persist that email as their selection for that session.   No sense making them take an extra step and have to choose which email to use in the chooser window, since they already signed in with that email.   

Of course, it takes half a second to pick another email in that window if they change their mind.  But lets make the flow easy enough assuming which account they initially selected to log into, should be that default selection persisted in the settings.

**Comment by shane-tomlinson** [comment] 2011-09-30 16:58
Duplicate of https://github.com/mozilla/browserid/issues/106.

**Closed as completed by shane-tomlinson** 2011-09-30 16:58 UTC
Labels: ★★★, qa:verified
