### ISSUE TITLE
tosfix.myfavoritebeer.org iOS 5 JS Error

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1307] opened 2012-03-14 01:01 UTC
Safari iOS 5.1 (9B179)

Steps to Reproduce:
0) Enable JS Console
1) Using Safari on iOS 5.1 go to http://tosfix.myfavoritebeer.org/ 
2) Click Sign In

Actual:
No activity
http://skitch.com/oztenskitch/8j4k5/photo-2

JavaScript: Error undefined TypeError: 'undefined' is not an object
http://skitch.com/oztenskitch/8j4ku/photo-1

Expected:
New page with login screen

**Comment by lloyd** [comment] 2012-03-15 16:48
dupe of #1308

**Closed as completed by lloyd** 2012-03-15 16:48 UTC
Labels: qa:verified
