### ISSUE TITLE
include.js loads very slowly for the addons "My Profile" page in FF

### ISSUE THREAD

**Issue by Marlena** [mozilla/persona#1206] opened 2012-02-27 18:20 UTC
Steps to reproduce:
1. Open Firefox
2. Go to addons-dev.allizom.org
3. Open Firebug or some other tool for viewing network response times
4. In the header, click username -> my profile
5. Notice the response time for include.js

The response time has routinely been between 5 - 13 seconds and a few times, it hasn't loaded at all.  

We have an automated test that is failing a lot because of this issue:

It's very important that Firefox have a good response time because most people look at the addons website in Firefox.  If it's necessary, I can get some user data numbers 

Here is a screenshot: https://skitch.com/e-marlenac/8fftq/browserid-homepage-viewprofile

I've logged a [similar bug](https://github.com/mozilla/browserid/issues/742) before, but for some reason this is consistently happening on the "My profile" page.  The similar but different "Account Settings" page seems unaffected.

**Comment by lloyd** [comment] 2012-03-01 17:57
duplicate of issue #1204

**Closed as completed by lloyd** 2012-03-01 17:57 UTC
Labels: qa:verified
