### ISSUE TITLE
rp_api missing from kpi blob

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3104] opened 2013-03-15 17:46 UTC
I don't see it when testing against my ephemeral browserid instance. I've been testing by logging into/out of the 123done site.

@skinny97214 is interested in knowing how many RPs are using .get vs .watch

**Comment by shane-tomlinson** [comment] 2013-03-18 11:53
This was introduced by the fix for #1827.

If a kpi_data message is sent before session_context has a chance to complete, then the kpi's are not stored.

**Comment by jrgm** [comment] 2013-03-28 03:21
Reopening. I was using dev.123done.org and dev.myfavoritebeer.org with FF19 and using scripts/inspect_localstorage.js to lazy-inspect the localStorage.interaction_data json, and I've seen rp_api in the blob a couple of times, but it's not in every blob (and I've cross checked my tool with live web inspector between dialog pops). Sorry, to not dig further at the moment...

**Comment by shane-tomlinson** [comment] 2013-03-28 11:27
@jrgm - I am trying to narrow down why this could be happening - do you know if these blobs without rp_api are continuations after returning from a primary?

**Comment by jrgm** [comment] 2013-03-29 06:56
Sorry, tried this a bit, but don't have an answer at the moment.

**Comment by shane-tomlinson** [comment] 2013-04-03 15:51
@kparlante - have you seen this at all on the backend of things? I have been unable to reproduce on the front end.

**Comment by shane-tomlinson** [comment] 2013-04-03 17:08
@jrgm - Are you seeing this in IE8 only? I just reproduced it there.

**Comment by kparlante** [comment] 2013-04-03 17:12
I think I do see it when looking at the data on stage, but I'm not sure which flows. I'm going to do an "audit" where I look at the outputs of a bunch of different flows to diagnose another problem (with how the dashboard is interpreting data), I'll keep my eye out for this as well.

**Comment by shane-tomlinson** [comment] 2013-06-12 15:45
@kparlante - I am wondering if this will be taken care of with the outstanding KPI updates. Have you seen this recently?

**Comment by kparlante** [comment] 2013-06-13 19:15
@shane-tomlinson : I can find blobs missing rp_api if I go looking for them. Some sample data here (both from dashboard production data and from kpiggybank-dev): https://id.etherpad.mozilla.org/kpi-issue-3104-data

The rate is low enough that I'm not sure its a big issue. If you want we can wait for recent changes to land on production and then do another analysis.

**Comment by jedp** [comment] 2013-07-10 05:50
If this is not a big issue, may I demote this to a three-star?  Please reassign if I am mistaken.

**Comment by callahad** [comment] 2014-10-31 19:52
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:52 UTC
Labels: ★★★, KPI, cleanup-2014
