### ISSUE TITLE
The user is not always logged in when using BrowserID

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#525] opened 2011-11-03 08:28 UTC
Environment:
1: Ubuntu 11.04 + Firefox 7.0.1
2: Android 2.2 HTC Desire A8181 + native browser

STR:
1. Open https://beta.myfavoritebeer.org in the browser.
2. Click on the Sign in button.
3. Sign in using an email and a password.
4. Select an email and sign in.

When the user selects the email and clicks on the Sign in button, the Signing in dialog is closed but the user is not logged in (the Sign in button is still displayed on the myfavoritebeer.org site.

Note: This issue reproduced about 4/5 times for an hour, then it stopped reproducing for a few hours (the only thing I did during this time on that OS was trying to log in with BrowserID).

**Comment by lloyd** [comment] 2011-11-03 16:56
two things:  
1. make myfavoritebeer fail better on assertion validation failures
2. check logs to see what ionana was seeing.

**Comment by lloyd** [comment] 2011-11-03 16:59
5 stars until we can understand the cause, then downgrade.

**Comment by ghost** [comment] 2011-11-04 10:42
When this bug was found, I kept getting the "Communicating with server" message displayed for a long time before the emails list was displayed. After the list was displayed, the bug reproduced.

This issue only reproduced for me on the environment in the bug description (I also tried it at the time on an iOS 4.2.1 iPhone and on Windows XP but it didn't reproduce on them).

Verified the bug today on the same environments as initially. The current results are:
Ubuntu 11.04 + Firefox 7.0.1 - no issues when logging in;
Android 2.2 HTC Desire A8181 + native browser - I get the "Yucky" error message at the same point I got the "Communicating with server" message before; when re-opening the Sign In dialog, the emails list is retrieved and the user can log in without any issues.

As I specified in the bug description, this bug reproduces intermittently. It may not reproduce for a whole day, then start reproducing very often for some time. Considering this, I will try to reproduce it again whenever I get the necessary time (I will only update the bug when finding something or if anyone needs any answers).

**Comment by lloyd** [comment] 2011-11-04 15:14
the android specific issue seems like one we should look into.  looking through the verifier logs for the last 16 hours or so I see no unexpected restarts.  

Given that @ioanab cannot reproduce the same issue, and that evidence of the only viable culprit we've identified suggests the problem is fixed (issue #523) - are we comfortable considering this bug fixed for now and continuing to try to reproduce it on the next beta, as well as digging into the other bug that @ioanab found (re Android 2.2)?

IOW, are we comfortable pushing train-2011.10.27 into production now?

**Comment by lloyd** [comment] 2011-11-07 20:20
I'm a little confused with where we go now.  I'll wait for QA to verify this one by watching the logs.  Maybe we say if we have clean logs come wed, we close down this issue and open a new one if a similar problem is found?

"watching the logs" here means watching closely for unexpected daemon restarts...  @jbonacci ?

**Comment by lloyd** [comment] 2011-11-09 01:10
closing down, @jbonacci will reopen if this thing rears its head again.

**Closed as completed by lloyd** 2011-11-09 01:10 UTC
Labels: ★★★★, qa:verified
