### ISSUE TITLE
Pop-up not rendering on Firefox Nightly 2012-09-11

### ISSUE THREAD

**Issue by indygreg** [mozilla/persona#2467] opened 2012-09-12 00:42 UTC
STR:

1) https://developer.mozilla.org/en-US/
2) Click "Sign-in" button
3) Nothing happens

This is with Firefox Nightly 2012-09-11 build. Is reproducible with all add-ons disabled. I can sign in through https://login.persona.org/signin just fine.

There is no output in the Error Console when I click the sign-in button. However, my chrome toolbar does "flash." I wonder if the built-in Persona support in Firefox is trying to kick in and fails. Who knows. I was told to file this bug.

**Comment by callahad** [comment] 2012-09-12 00:55
Thanks for filing this @indygreg! I don't have Windows 7 handy, and I can't reproduce this on OS X.

A few days ago another user reported the same issue in #identity, but quickly stated that it was an issue with noscript and that all was well. Alas, noscript isn't a factor in this bug report :(

**Comment by jrgm** [comment] 2012-09-12 01:51
I am running 18.0a1 (2012-09-11) on Windows 7 Pro SP1, no addons enabled and fairly vanilla profile. When I go to https://developer.mozilla.org/en-US/ and click 'Sign in' the popup opens and I am able to sign in to MDN with my persona email address. 

((I don't want to morph this bug from what Greg reported, but for completeness I'll note that if I explicity enable dom.identity.enabled in about:config, when I click on 'Sign in' a new tab is opened to developer.mozilla.org and the error console shows:

```
Error: TypeError: navigator.id.getVerifiedEmail is not a function
Source File: https://developer.mozilla.org/media/js/mdn-min.js?build=919eaca
Line: 16
```

That not being implemented was noted here https://bugzilla.mozilla.org/show_bug.cgi?id=790141 ))

**Comment by lloyd** [comment] 2012-09-13 16:43
works for me.  I'm closing down but urge you to re-open if you gain more information.

**Closed as completed by lloyd** 2012-09-13 16:43 UTC
Labels: qa:verified
