### ISSUE TITLE
Restore Persona branding during sign-on

### ISSUE THREAD

**Issue by chemistrydioxide** [mozilla/persona#3829] opened 2013-08-22 21:58 UTC
Some time ago, the Persona logo at the top of the login dialog has been removed. To me, part of this step made sense. However, I just tried to use Persona from my cell phone and I noticed that on mobile devices the whole thing even went further. All Mozilla Persona branding has been removed from the login dialog. There is neither a Persona logo nor does the dialog match the branding that Persona is using on the desktop. As a result, mobile users have no idea that they are using Persona. They have no clue that they are accessing a web site that is part of an SSO system. This may be no problem as long as the user is just using 1 (one) Persona-enabled site. However, when the user tries to log in to the 2nd Persona-enabled site, they will have no clue which password to enter. They assume their password to be for site X only, not for Persona.

I therefore suggest that when interacting with the fallback IdP, users should see a Persona logo. It doesn't have to be as big as it used to be in former times, but removing it entirely is definitely going to hurt.

**Comment by shane-tomlinson** [comment] 2013-08-23 06:42
@chemistrydioxide - this change was made as part of the mobile redesign for FirefoxOS. @manhratty and @ryanfeeley  - What are your thoughts here? Should be bring the Persona logo back in some small way? In mobile, we show a persona logo as the background image in the email input box as well as next to the email addresses, but nowhere else.

**Comment by ryanfeeley** [comment] 2013-08-23 11:43
![screen shot 2013-08-23 at 7 37 17 am](https://f.cloud.github.com/assets/68213/1015850/7894182a-0be8-11e3-8ce4-63c3d51f0ba0.png)
I will reach out to @manhratty. We need something. Also we're moving towards language like "Sign in with email" and not "Sign in with Persona" (which messes with the mental model somewhat). I need a full tour of mobile.

**Comment by chemistrydioxide** [comment] 2013-08-25 14:58
This is in fact the same issue as #2539.

**Comment by jaredhirsch** [comment] 2013-08-29 16:43
if this is a dupe of #2539, closing. reopen if i'm missing something

**Closed as completed by jaredhirsch** 2013-08-29 16:43 UTC
