### ISSUE TITLE
[Unconfirmed] `oncancel` not being fired after `navigator.id.request` on FXOS

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3519] opened 2013-06-12 18:20 UTC
We've gotten reports that `navigator.id.request`'s `oncancel` event isn't firing on FXOS (not sure of version number). I've put out requests for more info, but figured I'd file it to see if you guys could hunt down a potential cause on your end.

**Comment by mattbasta** [comment] 2013-06-12 18:57
We seem to be getting this in a bunch of places:

https://bugzilla.mozilla.org/show_bug.cgi?id=881167
https://bugzilla.mozilla.org/show_bug.cgi?id=881962

**Comment by jaredhirsch** [comment] 2013-06-12 19:22
@mattbasta is this a dupe of https://github.com/mozilla/browserid/issues/3456?

**Comment by mattbasta** [comment] 2013-06-12 19:26
Yes, it appears that it is

**Comment by jaredhirsch** [comment] 2013-06-12 21:33
@mattbasta Awesome. In that case, closing in favor of #3456. I'll copy over the bugzilla links you found, and update those bugzilla bugs as well. Thanks mang!

**Closed as completed by jaredhirsch** 2013-06-12 21:33 UTC
