### ISSUE TITLE
Persona Login Fails *sometimes* on ChromeOS

### ISSUE THREAD

**Issue by FattusMannus** [mozilla/persona#3844] opened 2013-08-29 15:27 UTC
It works sometimes (and I know that's not helpful and I cant work out steps to reproduce), but other times it tells me to get a modern browser....

I have experienced this inconsistency over several days usage.
Right now I have 2 bugzilla tabs open - 1 allows me to login, the other says unsupported browser.

Chrome OS details:
Version 29.0.1547.57 beta
Platform 4319.74.0 (Official Build) beta-channel lumpy
Firmware Google_Lumpy.2.111.0

Any other details I can provide I will be happy to.

**Comment by vladikoff** [comment] 2013-08-29 16:38
Is this on the Samsung Series 5 550 Chromebook?

**Comment by jaredhirsch** [comment] 2013-08-29 16:49
it'd be great to get reliable steps to reproduce

**Comment by ozten** [comment] 2013-08-29 16:50
Can Chromebook produce web developer debug logs? Like [HAR files](http://www.speedawarenessmonth.com/what-is-a-har-file-and-what-do-i-use-it-for/) or anything like that?

We don't have a way to reproduce this bug, so we need debug information.

**Comment by FattusMannus** [comment] 2013-08-30 08:02
@vladikoff Yes it is on that Chromebook.

@ozten Ill try to get you some HAR files today

**Comment by vladikoff** [comment] 2013-08-30 16:39
@FattusMannus Thanks for submitting the issue by the way and taking the time to provide details :)

**Comment by FattusMannus** [comment] 2013-09-02 08:05
I cant reproduce this so I am sure it will be closed.

This has happened multiple times over the last few weeks and seems to be site independant - i got it on FFOS Marketplace and BugZilla. 
I am adamant there is an issue, but I cant reproduce it.

**Comment by vladikoff** [comment] 2013-09-03 01:49
Can't reproduce this on the Chromebook Pixel (30.0.1599.21 dev), tried a few different sites multiple times.

**Comment by callahad** [comment] 2014-10-31 19:51
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:51 UTC
Labels: ★★, cleanup-2014
