### ISSUE TITLE
Gmail login prompts for user's email address twice

### ISSUE THREAD

**Issue by richardcrichardc** [mozilla/persona#3904] opened 2013-09-19 23:59 UTC
When identity bridging to gmail, the user is prompted twice for their email address:
- Once by Persona
- Once by Google

This is quite a conspicuous usability hurdle. I'm worried users who have taken a punt at logging in to my website for the first time are going to see this and bail out.

I don't know which Google API is used for logging in, but this problem seems to be quite avoidable using OAuth2 - see the `login_hint` parameter documented [here](https://developers.google.com/accounts/docs/OAuth2UserAgent):

> When your application knows which user it is trying to authenticate, it may provide this parameter as a hint to the Authentication Server. Passing this hint will either **pre-fill the email box on the sign-in form** or select the proper multi-login session, thereby simplifying the login flow.

**Comment by seanmonstar** [comment] 2013-09-20 00:20
Yep, we started with the OpenID API, but have a PR out to use OAuth2 instead: https://github.com/mozilla/browserid-sideshow/pull/114

**Comment by richardcrichardc** [comment] 2013-09-20 00:43
@seanmonstar Great.

Tell me where is the best place to find/report  'known issues' for identity bridging. I'm doing some testing with Internet Exploder 8 and am getting this error, though IE8 is configure to accept all third party cookies:

> Cannot verify myemailaddress@gmail.com
> 
> This may be due to your browser blocking third-party cookies. Please ensure your browser's privacy preferences are set to accept third-party cookies for gmail.com and try again.

**Comment by seanmonstar** [comment] 2013-09-20 00:56
Here is fine. Interesting. I just ran through our test site (http://123done.org) in IE8, and was able to log in with my Gmail account. What could be different? Got a screenshot of the error? And exactly at what point it shows up?

**Comment by richardcrichardc** [comment] 2013-09-20 02:11
Interesting. I have the same problem on 123done. This is running on XP -  the Linux Virtualbox IE8 XP image available from http://www.modern.ie/en-us/virtualization-tools#downloads.

![persona-login](https://f.cloud.github.com/assets/885016/1178012/d2f30d42-2198-11e3-8f7e-7f912e649785.png)

**Comment by jaredhirsch** [comment] 2013-09-26 16:39
looks like the problem is that 123done.org has a blank line above the doctype, so IE8 is jumping into quirks mode.

**Comment by jedp** [comment] 2013-09-26 16:41
For the blank line, I have opened https://github.com/mozilla/123done/issues/87

**Comment by richardcrichardc** [comment] 2013-09-26 21:36
Strange. My problem is also fixed. But I have not changed my app -  I have been working on other stuff for the whole week. It is not and was not running in quirks mode.

I am glad that it is now working, but a bit nervous as I don't know what fixed it.

Are there any other possible explanations?

On another note, assuming it is quirks mode that breaks Persona, is it possible for Persona to detect this and spit out an appropriate error message. Maybe on the console, as this would be directed towards developers.

**Comment by richardcrichardc** [comment] 2013-09-26 23:12
I hate to be the bringer of bad news. I have moved onto testing my app with IE9 and IE10 and identity bridging to gmail fails, with a different error. The errors also occur or 123done.org.

I have retested with Google Chrome. The problem does not occur. I have not retested with IE8.

![done-ie9](https://f.cloud.github.com/assets/885016/1222679/44c966a8-26ff-11e3-8fc4-c87d730c2538.png)

![123done-ie10](https://f.cloud.github.com/assets/885016/1222731/9d8c4836-2700-11e3-936a-fe556a6c86c1.png)

**Comment by callahad** [comment] 2013-09-27 08:11
Moving discussion of the login failure bug to https://github.com/mozilla/browserid-sideshow/issues/119

**Comment by callahad** [comment] 2014-10-31 19:50
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:50 UTC
Labels: ★★★, area:dialog, cleanup-2014
