### ISSUE TITLE
[ie8] cannot sign in with eyedee.me with ie8 (at least on an ephemeral instance) 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2239] opened 2012-08-07 04:54 UTC
STR
1. Go to train0730.123done.org and click sign in.
2. Enter &lt;somename&gt;@eyedee.me and click next. When eyedee.me is looked up, continue on to get https://eyedee.me/browserid/sign_in.html?email=...
3. Click 'Create my account' 

Expected: dialog transitions and is eventually logged in to train0730.123done.org as a primary eyedee.me email address

Actual: dialog tries to load https://eyedee.me/browserid/ and gets a 404 and stops there.

Notes: 'Cancel' instead of 'Create my account' also fails

This probably regressed with train-2012.07.06.

**Comment by jrgm** [comment] 2012-08-07 05:04
To be clear, both signin and cancel cases work with ie9 (on win7), and chrome, ff14, safari, opera on winxp. This is just IE8.

**Comment by shane-tomlinson** [comment] 2012-08-07 13:55
@jrgm - I cannot sign in using eyedee.me on ephemeral instances in Firefox even.  I believe this is known about already:

See issue #1571

**Comment by jrgm** [comment] 2012-08-07 15:42
GH-1571 is about using e.g., mockmyid with non-production instances. 

I can sign in using eyedee.me with an ephemeral instance and Firefox.

**Comment by shane-tomlinson** [comment] 2012-08-07 16:18
My failure is due to having 3rd party cookies disabled.  Moving forward on testing.

**Comment by jrgm** [comment] 2012-08-07 21:11
Just noting that this appears for ie8 (but not ie9) on both train-2012.07.30 and current dev

**Comment by jrgm** [comment] 2012-08-07 23:16
Additional note: if I try to do this a second time, I have to enter the username @eyedee.me again, but on that try I do not need to interact with the form from eyedee.me and I am authed and logged into 123done.

**Comment by lloyd** [comment] 2012-08-09 15:24
I can reproduce this with the original STR.  hmm.

**Comment by lloyd** [comment] 2012-08-09 20:45
The issue is that we have one eyedee.me deployment that works against dev/ephemeral/beta/prod and the way that eyedee.me tells who is talking to it is by deferring to referer headers.

With IE8, referer headers are not sent when the user is directed to the "auth" page from within the dialog, so eyedee.me includes _production_ resources for all environments.

This only breaks things when the env you're testing does not match production for the authentication_api.js resource.  Because a change has been made to this resource since production, stuff is broken.

This is not a regression, but rather a fragility in how an IdP can be built that supports all of our environments at the same hostname.  

Closing this issue down, to be continued in issue #2077

**Comment by jrgm** [comment] 2013-03-20 03:51
I'm going to reopen this. My bad for not doing so many moons ago. Sure it can be done in GH-2077 if that is the right overall fix.

**Comment by shane-tomlinson** [comment] 2013-04-03 13:13
@lloyd: reassigning to you. Could you do something ghettotastic like in the provisioning iframe, save the origin of postMessage into localStorage and dynamically load the correct script when the authentication page is displayed?

**Comment by callahad** [comment] 2014-10-31 19:54
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:54 UTC
Labels: ★★★★, cleanup-2014
