### ISSUE TITLE
Attempting to log in using Chinese or Japanese fails, no browserid dialog

### ISSUE THREAD

**Issue by a2sheppy** [mozilla/persona#1537] opened 2012-05-03 13:12 UTC
This happens on MDN in particular; if I click the "sign in" link, no browserid UI is appearing if I'm on a page that's in Chinese or Japanese. Works fine for all other languages. In addition, if I'm logged in on MDN (via an English page), Chinese and Japanese pages do not think I'm logged in.

**Comment by lloyd** [comment] 2012-05-03 16:42
several folks here have tried to reproduce this, we can't.  what else can you give us in terms of steps to reproduce?  @jrgm will follow up

**Comment by a2sheppy** [comment] 2012-05-03 19:01
I can reproduce it on my laptop as well as my desktop. It's pretty easy:

Go to, say: https://developer.mozilla.org/Project:ja/Copyrights

Try to sign in.

Doesn't work.

**Comment by stephendonner** [comment] 2012-05-03 19:38
I can reproduce this as well, but am wondering (and have asked the MDN folks) if it's something they've purposefully disabled/redirected.  @lmorchard, @groovecoder?

**Comment by jrgm** [comment] 2012-05-03 22:39
So it turned out that browserid login was disabled on MDN for Japanese and Chinese. The reason, as I understand it, 
was that MDN folks were under the impression that browserid was not localized for those languages, and if so, wanted
to serve a localized username/password web form (instead of offering English in the browserid dialog). 

So, browserid in production is localized for zh-CN and zh-TW. And MDN has now reenabled browserid signin to MDN for
uses of those locales. However, while Japanese was available for browserid in the prior release (03.28), it was removed 
for the 04.11 train due to not being fully complete. So, MDN has left browserid signin disabled at this time. 

With FF 12 set to be 'en-US', I can do the following:
- Start as not signed in to MDN
- I go to https://developer.mozilla.org/Project:ja/Copyrights and see a link in English 'Sign in'
  which points at https://developer.mozilla.org/users/login.
- I click that link which redirects to https://developer.mozilla.org/en-US/users/login where I am
  offered signin with Browserid. I sign in (in English) as my email, and I'm redirected back to
  https://developer.mozilla.org/Project:ja/Copyrights where I now see 'User tools' | jrgm | 'Sign
  out'
- I logout, change my browser to prefer Japanese 'Accept-Language
  ja,en-us;q=0.7,en;q=0.3' go to https://developer.mozilla.org/Project:ja/Copyrights,
  click the 'Sign in' link, get redirected to https://developer.mozilla.org/ja/users/login
  where I get a traditional username/password form.
  Which is pretty much what I'd expect to be able to do given that browserid signin on MDN is disabled for Japanese.

**Comment by jrgm** [comment] 2012-05-07 18:29
This seems to have been an issue with MDN configuration. Closing.

**Closed as completed by jrgm** 2012-05-07 18:29 UTC
Labels: ★★★★, qa:verified
