### ISSUE TITLE
[opera] primary email address signin fails with mockmyid.com

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2626] opened 2012-10-22 22:17 UTC
STR
1. Use Opera and load http://beta.123done.org and click Sign in
2. Enter someuser@mockmyid.com and click Next

Expected: dialog looks up address_info, fetches provisioning.html and logs the user in

Actual: dialog says 'Check with your email provider', and after 20 seconds or so, shows an error screen with 'Action: Checking Address Info'.

Notes: There are no JS errors in the console on Opera. This does work in current production. Also, Opera + eyedee.me works on stage OK.

Opera 12.02 on Win7 or osx/10.7

**Comment by jrgm** [comment] 2012-10-22 22:48
This also doesn't work on the main site - https://login.anosrep.org/signin

**Comment by callahad** [comment] 2012-10-25 16:56
12.02 breakage confirmed by @shane-tomlinson. 12.50 works.

**Comment by lloyd** [comment] 2012-10-25 16:58
let's figure out whether this affects bigtent and get to the bottom of this.

**Comment by lloyd** [comment] 2012-10-25 19:09
I can reproduce on opera 12.02. 

dug a little bit and found you can get an error by loading https://mockmyid.com/browserid/provision.html directly in opera.  `Unhandled DOMException: INVALID_ CHARACTER_ERROR`

Something about the way `bidbundle-min.js is minified causing problems for the parser of this specific version of opera?

**Comment by callahad** [comment] 2012-10-25 20:37
I'm getting errors even earlier in the process:
1. Go to http://beta.123done.org/
2. Click "Sign in"
3. Open Dragonfly (in Tools -> Options -> Advanced)
4. Select the "Scripts" tab (and make sure "show parse errors and break on exceptions" is enabled)
5. Click the reload button inside the Scripts tab

I get a whole series of errors in dialog.js, including `INVALID_CHARACTER_ERR`, trouble converting things to objects, and an inability to find modules like `bigint` and `crypto`.

**Comment by callahad** [comment] 2012-10-25 20:50
Note: I can reproduce most of the above errors in prod, yet MockMyID works fine in that environment. I _think_ this is a red herring.

Either way, Opera also reports an `INVALID_CHARACTER_ERR` for [line 823 of bidbundle.js](https://github.com/callahad/mockmyid/blob/daded13fc381c59d9be0fe83fd92e2dd6a8ff075/public_html/browserid/bidbundle.js#L823): `try { document.createElement('$'); }`

**Comment by callahad** [comment] 2012-10-25 20:54
What's interesting is that this code block (taken from bidbundle above):

``` javascript
var INVALID_CHARACTER_ERR = (function () {
      // fabricate a suitable error object
      try { document.createElement('$'); }
      catch (error) { return error; }}());
```

is what's failing with "Unhandled DOMException: INVALID_CHARACTER_ERR" when it tries to do `document.createElement('$');`.

But shouldn't the `catch` statement... catch that?

**Comment by shane-tomlinson** [comment] 2013-04-09 13:17
@callahad, @jrgm - I am able to sign in using Opera on beta.123done.org. If the INVALID_CHARACTER_ERR is still a problem, can you open a separate issue? Closing as "works for me!"

**Closed as completed by shane-tomlinson** 2013-04-09 13:17 UTC
Labels: ★★★★

**Comment by jrgm** [comment] 2013-04-09 19:18
Yeah, works for me now on Opera 12.14 osx. It still occurs on 12.02, but that is an old version.
