### ISSUE TITLE
communication_iframe can't provision Yahoo! email addresses

### ISSUE THREAD

**Issue by peder541** [mozilla/persona#3922] opened 2013-09-26 20:08 UTC
I am signed in to Persona using a Yahoo! email address. After two minutes, the cert has expired, so on a refresh the communication_iframe has to go through the provisioning process.  The console returns "hooking up begin provisioning with users=" and provisioning fails.

I couldn't replicate on 123done.org because it seems to skip provisioning.

**Comment by callahad** [comment] 2013-10-10 16:43
Temporarily flagging as 5-star: we need to check to see if automatic reprovisioning is working.

**Comment by shane-tomlinson** [comment] 2013-10-17 19:21
I just manually tested this and am unable to reproduce.

Steps that I tried.
1. sign in to my personal blog that uses the .watch api using a yahoo address
2. wait 2 hours
3. delete the session cookie for my site from the Firefox preferences.
4. open the network console
5. refresh my blog's page.

```
32 GET https://login.persona.org/communication_iframe [HTTP/1.1 304 Not Modified 171ms]
20:17:53.535 GET https://login.persona.org/wsapi/session_context [HTTP/1.1 200 OK 186ms]
20:17:53.972 GET https://login.persona.org/wsapi/list_emails [HTTP/1.1 200 OK 180ms]
20:17:54.419 GET https://login.persona.org/wsapi/address_info [HTTP/1.1 200 OK 680ms]
20:17:55.060 GET https://yahoo.login.persona.org/provision [HTTP/1.1 200 OK 820ms]
20:17:56.116 GET https://login.persona.org/provisioning_api.js [HTTP/1.1 304 Not Modified 186ms]
20:17:56.117 GET https://yahoo.login.persona.org/provision.js [HTTP/1.1 200 OK 185ms]
20:17:56.431 "hooking up begin provisioning with users=" provision.js:6
```

All good. @peder541 - which browser are you on, and what are your cookie settings?

**Comment by shane-tomlinson** [comment] 2013-10-17 19:24
I lied. I am not signed in to my site as expected. Provisioning starts, then nothing.

**Comment by shane-tomlinson** [comment] 2013-10-17 19:35
After re-trying, more information was given:

```
20:34:05.057 GET https://yahoo.login.persona.org/provision [HTTP/1.1 200 OK 825ms]
20:34:05.979 GET https://login.persona.org/provisioning_api.js [HTTP/1.1 200 OK 294ms]
20:34:05.980 GET https://yahoo.login.persona.org/v/ddb84c1587/js/lib/jquery.min.js [HTTP/1.1 200 OK 379ms]
20:34:05.980 GET https://yahoo.login.persona.org/provision.js [HTTP/1.1 200 OK 381ms]
20:34:06.297 "hooking up begin provisioning with users=" provision.js:6
20:34:06.364 "callback" provision.js:6
20:34:06.364 "begining provisioning set117@yahoo.com 21600" provision.js:6
20:34:06.364 "no session, failing"
```

**Comment by peder541** [comment] 2013-10-17 19:50
Current log readout in Firefox:

```
[14:46:04.768] GET https://login.persona.org/include.js [1ms]
[14:46:05.585] GET https://login.persona.org/communication_iframe [HTTP/1.1 304 Not Modified 149ms]
[14:46:05.787] GET https://login.persona.org/wsapi/session_context [HTTP/1.1 200 OK 154ms]
[14:46:06.005] GET https://login.persona.org/wsapi/list_emails [HTTP/1.1 200 OK 152ms]
[14:46:06.162] GET https://login.persona.org/wsapi/address_info?email=xbroprox%40yahoo.com&issuer=default [HTTP/1.1 200 OK 483ms]
[14:46:06.661] GET https://yahoo.login.persona.org/provision [HTTP/1.1 200 OK 259ms]
[14:46:06.941] GET https://login.persona.org/provisioning_api.js [HTTP/1.1 304 Not Modified 149ms]
[14:46:06.942] GET https://yahoo.login.persona.org/provision.js [HTTP/1.1 200 OK 84ms]
[14:46:07.058] "hooking up begin provisioning with users="
```

I've received that second readout Shane got before, but it happens pretty sporadically. Usually "hooking up begin provisioning with users=" is the last line.

Edit: Just tested in Chrome. It outputs the additional information and an origin error:

```
Unable to post message to https://yahoo.login.persona.org. Recipient has origin https://login.persona.org.
 communication_iframe.js:1
t communication_iframe.js:1
(anonymous function) communication_iframe.js:1
hooking up begin provisioning with users= provision.js:6
callback provision.js:6
begining provisioning xbroprox@yahoo.com 21600 provision.js:6
no session, failing provision.js:6
```

**Comment by jaredhirsch** [comment] 2013-10-17 20:04
@callahad do you have context on the yahoo provisioning flow, any thoughts on what might be lurking here? also, is this a five-star or a four-star?

**Comment by jaredhirsch** [comment] 2013-10-18 18:34
i'll take this.

_edited to remove sour tone_ :beers:

**Comment by jaredhirsch** [comment] 2013-10-21 23:06
argh! I got wrapped up in fallback idp stuff and didn't get to this today.

@callahad are we _sure_ this isn't 4 stars to investigate?

**Comment by jaredhirsch** [comment] 2013-10-22 18:30
talked with callahad about this in [irc](http://irclog.gr/#show/irc.mozilla.org/identity/332403), bumping down to four stars. still a priority, but not blocking other work.

**Comment by callahad** [comment] 2014-10-31 19:50
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:50 UTC
Labels: ★★★★, cleanup-2014
