### ISSUE TITLE
Only the headers and footers of the diresworb.org pages are localized 

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1111] opened 2012-02-14 17:12 UTC
OS: Windows 7
Browser: Firefox 11.0
Language: French

STR:
1. Load https://diresworb.org/ in the browser.
2. Browse through its pages (home, sigin, sign up etc).
3. Sign in and repeat step 2.

Only the headers and footers of the pages are localized (the rest of the strings are in English).

**Comment by ozten** [comment] 2012-02-14 17:34
Great point @ioanab. This is by design, we'll use this bug to track work for the l10n-rebrand milestone.

**Comment by ghost** [comment] 2012-02-15 13:41
The following messages displayed on https://diresworb.org/ pages aren't localized either:
- message displayed when trying to sign in with a wrong password;
- message displayed when trying to sign in with an email not associated to BID;
- message displayed when trying to sign up with an email already associated to BID;
- message displayed when trying to reset the password for a non-existent user;
- error messages displayed when trying to change the password (not entering one of the passwords, entering an erred old password);
- messages displayed when removing an email;
- message displayed when canceling an account.

**Comment by shane-tomlinson** [comment] 2012-02-15 14:08
@ioanab - can you take screen shots of the offenders in Skitch or other alternative?  Is this in the dialog or on the main site - the main site is only partially translated at the moment, which is "as expected" for the moment.

**Comment by ghost** [comment] 2012-02-15 14:24
@shane-tomlinson - this is all on the main site (server). I will take the screen shots and add corresponding links in here when done.

**Comment by shane-tomlinson** [comment] 2012-02-15 14:29
@ioanab - thanks, the screen shots really really help me out!  Great work on the bug finding btw.

**Comment by ghost** [comment] 2012-02-15 16:17
thanks, @shane-tomlinson. Here are the screen shots for the cases listed above (both pages and messages) http://bit.ly/x0pYJw. Please let me know if I missed any.

**Comment by lloyd** [comment] 2012-07-16 03:22
this is a duplicate of issue #1862

**Closed as completed by lloyd** 2012-07-16 03:22 UTC
Labels: ★★★★, qa:verified
