### ISSUE TITLE
"Unable to post message to https://gmail.login.persona.org"

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3700] opened 2013-07-23 23:53 UTC
The following messages are appearing in the console on marketplace-dev:

```
Unable to post message to https://gmail.login.persona.org. Recipient has origin https://login.persona.org.
Refused to set unsafe header "Connection"
```

I'm logged in with `mattbasta@gmail.com`

**Comment by seanmonstar** [comment] 2013-07-24 00:06
I've seen this too, but don't see any actual bad consequences happening here. Is it stopping your logins?

**Comment by gene1wood** [comment] 2013-07-24 00:07
We cutover to using bridge-gmail/sideshow at 4:40pm which is what's causing this

**Comment by mattbasta** [comment] 2013-07-24 00:34
No ill effects observed, but it is alarming nonetheless.

**Comment by seanmonstar** [comment] 2013-07-24 00:57
Agreed, it'd be nice if we could get rid of that. The error is coming from within `navigator.id.registerCert()`.

**Comment by callahad** [comment] 2013-07-25 16:38
Since there are no observed ill effects, tagging this 3-star, but we definitely want to look into and resolve this. Alarming == bad.

**Comment by mattbasta** [comment] 2013-07-25 18:16
This only happens for users that have previously logged in. Clearing the "siteInfo" `localStorage` key causes the issue to go away.

Persona should start versioning its `localStorage` keys, since this tends to be an issue with new versions. Marketplace structures its keys in the format `<version>::<key>`.

**Comment by shane-tomlinson** [comment] 2013-07-25 21:17
@mattbasta - I agree that versioning storage keys would have been useful in several situations that we have faced, but I would like to know the root cause of this issue before saying this is one of them.

**Comment by mattbasta** [comment] 2013-07-25 21:20
I can confirm from two different browsers, deleting the `siteInfo` key
fixes this issue.

**Comment by shane-tomlinson** [comment] 2013-07-25 21:28
@mattbasta - siteInfo is what we use to keep track of site->email associations and whether the user is marked as signed in to that site. Getting rid of that namespace destroys our ability to pre-select the email address for the user whenever they open the dialog, and it also gets rid of our ability to automatically sign you in to a site that uses the .watch API.

**Comment by shane-tomlinson** [comment] 2013-07-26 12:53
The comment in https://github.com/mozilla/browserid/blob/fc8c91e4226d17fb2d7a5c60e6334ef70f21f7c5/resources/static/dialog/js/modules/dialog.js#L72-L73 may explain what is happening here.

WinChan may not be removing its 'message' listener correctly, though a quick glance at the code looks like it should be.

**Comment by husayt** [comment] 2013-08-12 11:00
We are experiencing this issue as well as latest as 12th of august. The worst is that sometimes it's causing an infinite loop, similar to the one described here:
http://comments.gmane.org/gmane.comp.mozilla.identity.devel/5530

**Comment by callahad** [comment] 2013-08-12 18:22
@husayt Do you only see the infinite loop in local development?

**Comment by husayt** [comment] 2013-08-12 21:53
@callahad Just now I had experienced this infinite loop issue on production. What is worse, other users been complaining whole day about this. This is really serious. I can't ask users to go and clean up their locale storage, it is really embarassing.

**Comment by gene1wood** [comment] 2013-08-13 19:44
There's also Issue #2521 which sounds like an attempt to solve the infinite loop problem in general.

**Comment by jaredhirsch** [comment] 2013-08-13 19:48
@husayt it would be extremely helpful if you could give us specific steps to reproduce the bug you're seeing, and if you could describe the bug in detail.

**Comment by ndizzle** [comment] 2013-08-13 20:23
Edit: Clicking 'stop' in chrome (or now firefox - same issue in firefox) allowed me to manually remove all persona related entries from localstorage. This allowed me to log on at least once.

**Comment by heydarli** [comment] 2013-08-14 08:07
@6a68 We had  `window.location.reload();` in `onlogout`'s success callback.
To replicate the loop just remove `emails` from localStorage. That would log user out and cause the loop.
Clearing `siteInfo` stops the loop.

**Comment by shane-tomlinson** [comment] 2013-08-14 08:13
@NadirHeydarli - siteInfo is what we use to keep track of site->email associations, clearing that causes Persona to believe the user is not signed in and it will not attempt to sign the user in. Thanks for the extra info.

**Comment by callahad** [comment] 2014-10-31 19:51
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:51 UTC
Labels: ★★★, area:api, cleanup-2014
