### ISSUE TITLE
Persona logs out at random then logs in again

### ISSUE THREAD

**Issue by khairihafsham** [mozilla/persona#2560] opened 2012-10-08 07:48 UTC
I have been testing persona locally and noticed that sometimes persona calls the onlogout handler at random and then after page refreshes, calls the onlogin handler. By random I mean, not invoking navigator.id.logout() explicitly.

after doing some digging, I noticed 2 things:
1. this happens after the request for session_context fails to get a 200.
2. everytime persona calls out my onlogout handler at random, I re-verify the assertion and it fails.

I would like to know if this is expected or an anomaly? Thank you.

**Comment by callahad** [comment] 2012-10-08 16:57
I suspect that this is less random than it seems, and may be part of an intentional feature. When you say you re-verify the assertion, are you caching the assertion, or are you verifying the new assertion that Persona provides when it calls the `onlogin` handler?

**Comment by khairihafsham** [comment] 2012-10-08 17:19
I am caching the assertion, in hope that I could somehow prevent my application from logging users out intermittently by ignoring the logout request if assertion is verified. but it doesn't.

If this behaviour is expected, it is a bit less straight forward to implement Persona than I initially thought. Any suggestions?

**Comment by callahad** [comment] 2012-10-08 17:57
Thanks for the quick response! Assertions expire after 2 minutes, and aren't designed to be cached. This is to improve security for both your site and your users, since an old assertion can't be reused later.

I'll look into the session_context issue -- that sounds like it could be a bug. When a page loads, Persona tries to make sure that the `loggedInUser` matches the browser's current user. If it doesn't, Persona will trigger an `onlogin` or an `onlogout` action to fix this.

For example, if a user logs out of Persona but forgets to log out of your site, then the next time that browser hits your site, Persona will automatically trigger an `onlogout` action.

**Comment by khairihafsham** [comment] 2012-10-08 18:23
make sense and I've assumed as much. if it is any help, I encountered this issue while primarily using Firefox for Linux and I could reproduce it by navigating around my site as fast as I can (sometimes before session_context's request manage to complete).

 Thank you for your hard work.

**Comment by callahad** [comment] 2012-10-11 17:10
Update: Our logs didn't show anything abnormal with session_context calls, and we haven't been able to reproduce this locally. Is it possible that something is weird between your computer and your connection to the broader internet? Flaky connection? Weird proxy?

How reliably can you reproduce this?

Leaving this bug open for future review with a focus on polishing the user experience.

**Comment by khairihafsham** [comment] 2012-10-11 17:35
My internet connection is stable as far I know. I have just tested it again locally (the site is not live yet) and got logged out immediately after a failed session_context request. Below is a snapshot from firebug.

<img src="http://i.imgur.com/SgURi.png" title="Hosted by imgur.com" alt="" />

I will test again this weekend with a live version of the website and see if the problem persist. Will update this thread again.

**Comment by jrgm** [comment] 2012-10-11 17:57
What is the response code that you got for the session_context call above?

**Comment by khairihafsham** [comment] 2012-10-11 18:00
there was no response code, since the request failed. at least the response panel is missing from firebug for that particular session_context.

**Comment by lloyd** [comment] 2012-10-11 22:41
can you provide the headers and body of the session_context request?  not sure that will let us diagnose, but if it is easy it's worth a shot…

**Comment by khairihafsham** [comment] 2012-10-18 15:31
Hi, sorry for the long absence.

I have tested again with a live website and now I can reproduce the issue quite well. I just have to wait until either list_emails or session_context is making a request and immediately click to a link to another page, effectively making the request to fail and getting no response. Everytime after that, I get a logout.

I have tested on chrome and firefox (ubuntu). Somehow, it only happens on firefox, even in safemode.

If anyone would like to tests themselves, the website is corak.my

Thank you.

**Comment by EreMaijala** [comment] 2012-11-01 13:49
Hi,

I've done some integration work with VuFind with the results available for testing on our development server at http://vufind-fe-kktest.lib.helsinki.fi/edge?lng=en-gb and I'm seeing the same problem (Firefox 16, Mac OS X 10.7). Looks like also navigation pages back or anything else that might cancel the request will trigger the problem. This makes the otherwise promising and pretyt nice experience significantly worse than it should, and it seems that it's quite easy to trigger the problem also with just navigating around the system fast enough as sometimes the context requests take a short while to complete.

**Comment by ethernomad** [comment] 2013-03-28 00:51
We were having this problem with the Drupal module. We solved it by de-registering the onlogout handler in response to beforeunload.

http://drupalcode.org/project/persona.git/commitdiff/99eb4c4

**Comment by ethernomad** [comment] 2013-03-28 00:52
This is how it happens. I can only reproduce it on Firefox.
![persona-logout](https://f.cloud.github.com/assets/161566/311451/cacc9b92-9741-11e2-9f53-e1cc957f24f8.png)

**Comment by ethernomad** [comment] 2013-04-13 04:16
Video of the problem: http://www.youtube.com/watch?v=__vj5bULgD0

**Comment by callahad** [comment] 2013-04-13 05:05
Suspecting the same root cause as #2423

**Comment by seanmonstar** [comment] 2013-04-24 20:40
@drupalnomad is there any way you could catch when `list_emails` request fails, and tell me what the statusCode and statusText of the request is?

**Comment by seanmonstar** [comment] 2013-05-13 21:12
I used to be able to reproduce this a while ago, and it seemed to be the browser canceling open XHRs when navigating away from a page. I haven't been able to reproduce this now, though. I'm left wondering if it was browser bugs that have been fixed.

Still, if someone still hits this, I'd love to see the statusCode and Text of the request that fails.

**Comment by ethernomad** [comment] 2013-05-13 23:45
If I remove the 

``` javascript
    $(window).bind('beforeunload', function (event) {
      navigator.id.watch({
        loggedInUser: settings.persona.email,
        onlogin: function (assertion) {},
        onlogout: function () {}
      });
    });
```

I can still trigger the problem, although it seems harder to trigger than it used to be. I think the reason there are red requests in the screenshot above is because the requests are aborted when a new page is being loaded. They don't have a response code.

Sometimes session_context is the request that gets interrupted. This does not seem to be the root cause of the problem.

**Comment by seanmonstar** [comment] 2013-05-14 18:34
@drupalnomad would you be willing to give me a login to the site affected? I can't reproduce on the sites I've been testing. I'd love to set a breakpoint inside communication_iframe at `getSilentAssertion`, and inspect  what the error is, if there is any statusCode, and whatnot.

My guess is it's erroring with `statusCode === 0`, then I can add that check into the code.

**Comment by christgamesadmin** [comment] 2013-06-26 03:49
I have been struggling with this one for awhile (weeks) and found this post tonight. Thanks for the sanity check that others are also experiencing the same issue. I thought it was just my bad code (might still be), but it appears to be a common problem. This problem looks like a performance issue to me. If I hold down the F5 key to get rapid page refreshes, approximately 1 out of every 10 hits will trigger a log out condition, then it corrects itself and logs you back on. So refreshing a page before it completes appears to be an easy way to reproduce it, at least for me. My site is http://christgames.org/auth (still under construction) if you want to test it.

**Comment by ethernomad** [comment] 2013-08-08 00:19
I am no longer able to reproduce this problem and will remove the workaround from the Drupal module.

**Comment by ethernomad** [comment] 2013-08-08 00:20
I'm not sure how to close this issue.

**Comment by jaredhirsch** [comment] 2013-08-12 18:13
Closing, since the underlying xhr-related bug seems to have been solved.

Please reopen **with steps to reproduce** if you are still seeing this bug.

**Closed as completed by jaredhirsch** 2013-08-12 18:13 UTC
Labels: ★★★, area:api
