### ISSUE TITLE
Dolphin on iOS6: Sign in dialog is not automatically dismissed after signing in

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#2542] opened 2012-09-28 12:01 UTC
Device: IPhone 4 - IOS 6
Browser: Dolphin 6.1

Steps:
1. Open http://myfavoritebeer.org in browser
2. Tap on Sigh in with Persona -> Sign in dialog opens
3. Enter credentials and press on Sign in

Expected: 
The sign in dialog is automatically dismissed after signing in 

Actual: 
Sign in dialog is not dismissed

**Comment by shane-tomlinson** [comment] 2012-09-28 12:04
This is a duplicate of #360, closing.

**Comment by shane-tomlinson** [comment] 2012-09-28 12:14
@csuciu - Thanks for the bug report! I see you closed #360, I will make this is the new tracker for Dolphin. Re-opening.

**Comment by callahad** [comment] 2014-10-31 19:53
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Closed as completed by callahad** 2014-10-31 19:53 UTC
Labels: ★★, area:mobile, cleanup-2014
