### ISSUE TITLE
The "login failure [object Object]" pop-up is sometimes displayed when selecting an email and signing in with no internet connection

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#567] opened 2011-11-14 14:39 UTC
OS: Windows 7
Browser: Firefox 8.0

STR:
1. Open the emails list dialog from http://beta.myfavoritebeer.org.
2. Loose your internet connection.
3. Select an email and click on the Sign In button.

Sometimes a pop-up with the "login failure [object Object]" text on it and an OK button was displayed. Most times the "We are sorry..." message from above was displayed.

**Comment by shane-tomlinson** [comment] 2011-11-17 16:21
@ioanab - I have been unable to reproduce this, is this intermittent or can it be caused reliably?

**Comment by ghost** [comment] 2011-11-17 16:25
@shane-tomlinson - this issue is intermittent (that is why I wrote the pop-up is only displayed sometimes). From my experience, you may need to try to reproduce it many times before it actually happens (some days it reproduced from my second try, others barely after using BrowserID for hours with an internet connection that kept getting lost).

**Comment by shane-tomlinson** [comment] 2011-11-17 16:28
@ioanab - thanks, I may have to put some rate limiting proxy on my network connection to introduce some more lag.

**Comment by ghost** [comment] 2011-12-15 10:29
OS: Android 2.3.3
Browser: Native

This issue reproduces now intermittently when the internet connection is working ok too.

**Comment by shane-tomlinson** [comment] 2012-01-13 15:38
@ioanab - have you seen this since?  I still have not, no matter what I try.  Have you seen this again?

**Comment by ghost** [comment] 2012-01-16 08:33
@shane-tomlinson - I can't verify if this issue still reproduces until issue 905 gets fixed.

**Comment by ghost** [comment] 2012-02-15 14:20
This issue reproduced again (once) today on Firefox 11.0 beta 2 + Windows 7.

**Comment by shane-tomlinson** [comment] 2012-02-17 13:17
@ioanab - just to confirm, is the "login failure [object Object]" coming from beta.myfavoritebeer.org or is it coming from the BrowserID dialog?

**Comment by shane-tomlinson** [comment] 2012-02-17 13:54
@ioanab - I am now able to reproduce this, thanks.  This is coming from beta.myfavoritebeer.org and not browserid itself.

@lloyd - I had to fix both myfavoritebeer and myfavoritebooze - myfavoriteshow handles errors differently.  Pull requests are:

https://github.com/lloyd/myfavoritebeer.org/pull/49
https://github.com/lloyd/myfavoritebooze.org/pull/5

**Comment by shane-tomlinson** [comment] 2012-02-17 13:56
@lloyd - when you review/merge the above pull requests, can you close this issue?

**Comment by shane-tomlinson** [comment] 2012-02-21 11:21
Closing as fixed.

**Comment by ghost** [comment] 2012-04-09 15:07
This issue reproduces again when loosing your internet connection while on the "Address Verified!
Your identity has been verified with your email provider, we will now try to sign you in. " dialog.

**Comment by ghost** [comment] 2012-06-15 09:48
@jbonacci I tried to reproduce this issue on http://123done.org/ several times with different BrowserID dialogs, but it never reproduced.

**Closed as completed** 2012-06-15 17:30 UTC
Labels: ★★★★, qa:verified
