### ISSUE TITLE
Safari: footer not positioned correctly in Private Browsing mode

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3219] opened 2013-04-10 00:08 UTC
busted in MobileSafari and desktop Safari/Mac.

![Screen Shot 2013-04-09 at 5 05 13 PM](https://f.cloud.github.com/assets/96396/359840/560f764a-a172-11e2-8263-d6de3b796de0.png)

![Screen Shot 2013-04-09 at 5 06 13 PM](https://f.cloud.github.com/assets/96396/359847/7b7ce43a-a172-11e2-8169-ec5a15e4ef4b.png)

**Comment by edwindotcom** [comment] 2013-09-19 17:27
we don't support private browsing: generally you'll get a 'not supported browser dialog'.  We could improve the messaging, downgrading to 3 star.

**Comment by edwindotcom** [comment] 2013-09-19 17:30
actually dupe of #3220

**Closed as completed by edwindotcom** 2013-09-19 17:30 UTC
Labels: ★★★
