### ISSUE TITLE
persona user ID receives error message "Gmail.com is not responding"

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3728] opened 2013-07-29 15:48 UTC
ed at emrsoftware.com reported in [Bug 898851](https://bugzilla.mozilla.org/show_bug.cgi?id=898851):

User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E)

Steps to reproduce:

A current User tries to login to my website (golfgrudge.com) using Persona User Id  email address = "ARJ412@Gmail.com".

Actual results:

After hitting next button, the user immediately gets the response "Gmail.com is not responding. Please wait a few minutes and try again. "  This happens every time, and happens using IE, Chrome, FireFox, (every thing I've tried it on.)  This user has been logging in successfully for months.  I assume this has something to do with the Persona / GMAIL interaction that has been recently added to Persona.

Expected results:

Persona should have the user verify the email by typing in the password, and then successfully authenticating the user.

/cc @callahad

**Comment by jedp** [comment] 2013-07-29 15:52
Ed additionally comments:

> I've tested logging in to my website with other gmail accounts, and have not had any problem.  So far just the gmail email address listed above has this issue.

**Comment by callahad** [comment] 2013-07-29 16:40
I suspect DNS issues. Can they resolve gmail.login.persona.org? Can they hit ver.txt on the same?

**Comment by seanmonstar** [comment] 2013-07-29 16:44
Nah, testing that email address myself gives me the same error.

**Comment by seanmonstar** [comment] 2013-07-29 16:53
I get the feeling this is related to his email having an uppercase G.

Trying with the g in lowercase, I get that the state is transition, and I see it load the provisioning page just fine. It's of course not proven yet, and then in the dialog, something uses the address_info again, only it uses the `normalizedEmail`. Since that includes the capital G, it hits the network again (cache key missed), and we get back that the state is offline.

```
https://login.persona.org/wsapi/address_info?email=ARJ412%40gmail.com&issuer=default
{
  "auth":"https://gmail.login.persona.org/authenticate",
  "prov":"https://gmail.login.persona.org/provision",
  "type":"primary",
  "issuer":"gmail.login.persona.org",
  "normalizedEmail":"ARJ412@Gmail.com",
  "state":"transition_to_primary"
}
```

```
https://login.persona.org/wsapi/address_info?email=ARJ412%40Gmail.com&issuer=default
{
  "type":"secondary",
  "issuer":"login.persona.org",
  "disabled":false,
  "normalizedEmail":"ARJ412@Gmail.com",
  "state":"offline"
}

```

**Comment by callahad** [comment] 2013-07-29 16:58
oh man, did I miss that in our tests? :(

**Comment by seanmonstar** [comment] 2013-07-29 16:59
sideshow would handle it just fine. the problem is in browserid. My guess is that it's not lowercasing the domain part before looking for the support document (and checking proxy_idps).

**Comment by seanmonstar** [comment] 2013-07-29 17:24
I have an oustanding PR that fixes this, but currently on production, the user can't really self heal. Do we want to hotfix this before announcing Gmail?

**Comment by edwindotcom** [comment] 2013-07-29 18:26
it's the case in the 'gmail' portion of the address.  I can repro if i use user@Gmail.com no repro with user@gmail.com

**Comment by seanmonstar** [comment] 2013-07-29 20:11
i 5-starred it since this is a regression (users who could sign in can't anymore)

**Comment by jrgm** [comment] 2013-07-29 21:25
Is this a similar potential problem here? 

https://github.com/mozilla/browserid/blob/dev/lib/wsapi/used_address_as_primary.js#L34-36

**Comment by seanmonstar** [comment] 2013-07-29 21:46
Yes, I think it is. I've got a better solution coming soon.

**Comment by jaredhirsch** [comment] 2013-07-30 15:52
@seanmonstar let me know if you need reviews or other help closing this puppy today

**Comment by jrgm** [comment] 2013-07-30 23:49
I'm in stage which has the fix for this, but...

I have a pre-existing user with capital-G Gmail and type secondary in the stage database:

```
mysql> select u.id, e.id, u.lastPasswordReset, u.failedAuthTries as fat, e.address, e.type, e.verified from email as e join user as u on u.id = e.user where e.address = 'abcabdab+s107K@Gmail.com';
+----------+----------+---------------------+-----+--------------------------+-----------+----------+
| id       | id       | lastPasswordReset   | fat | address                  | type      | verified |
+----------+----------+---------------------+-----+--------------------------+-----------+----------+
| 11211847 | 14604522 | 2013-03-06 22:40:49 |   0 | abcabdab+s107k@Gmail.com | secondary |        1 |
+----------+----------+---------------------+-----+--------------------------+-----------+----------+
1 row in set (0.00 sec)
mysql> 
```

In response to: https://login.anosrep.org/wsapi/address_info?email=abcabdab%2Bs107k%40Gmail.com&issuer=default
I get: {"auth":"https://gmail.login.anosrep.org/authenticate","prov":"https://gmail.login.anosrep.org/provision",
        "type":"primary","issuer":"gmail.login.anosrep.org","normalizedEmail":"abcabdab+s107k@Gmail.com","state":"transition_to_primary"}

The dialog shows the screen with 'Your Gmail.com account has been upgraded to work even better with Persona. We will redirect you to Gmail.com.' If I continue from there, signin with abcabdab@gmail.com, on the return I get an error. 'Action: Authenticating with Assertion '

The assertion POST'ed to /wsapi/auth_with_assertion is valid according to ./node_modules/.bin/check-assertion.

However the response to /wsapi/auth_with_assertion is:
{"success":false,"reason":"issuer 'gmail.login.anosrep.org' may not speak for emails from 'Gmail.com'"}

**Comment by jaredhirsch** [comment] 2013-07-30 23:51
le sigh. reopening

**Comment by jaredhirsch** [comment] 2013-07-31 00:48
refixed by #3739, reclosing

**Comment by jrgm** [comment] 2013-07-31 00:57
This is on login.dev.anosrep.org. There, I tried to sign in with abcabdab+capitalG@Gmail.com. The auth_with_assertion works now, but the assertion that is posted to http://dev.123done.org/api/verify is rejected with 

```
failed to verify assertion: issuer 'sideshowbob.personatest.org' may not speak for emails from 'Gmail.com
```

**Comment by jrgm** [comment] 2013-07-31 05:38
So, I can get past the issue noted in https://github.com/mozilla/browserid/issues/3728#issuecomment-21833903 and also altered the database in dev to setup so that the address abcabdab+capitalG@Gmail.com was set as a secondary and needed to be "upgraded". But I'm going to call it a night and see yall in the morning.

**Comment by karlht** [comment] 2013-07-31 20:06
Please also see #3245, which is still not closed.

**Comment by edr67** [comment] 2013-08-01 22:23
I am still seeing the issue (Gmail.com is not responding...), with the email address I reported (ARJ412@Gmail.com).  Is there any date that I can tell this user that his email ID will work in Persona again?  It's been a while since he's been able to log in to my website.

As a last resort can somebody delete his persona ID and I can have him start over, and use all lower case in the gmail.com portion of his email address.

Thank You
Ed

**Comment by seanmonstar** [comment] 2013-08-01 22:37
@edr67 sorry for taking longer. The fixes for this are ready, and deemed worthy of rolling quicker as hotfixes, but we have another hotfix that takes priority. That one is in testing and should deploy soon, and then this can happen. @jrgm would know more.

Also, since this still affects users in production, should this 5star stay open until we're deployed?

**Comment by jaredhirsch** [comment] 2013-08-03 14:28
@seanmonstar good call. reopening until the fix is live

**Comment by jaredhirsch** [comment] 2013-08-06 22:55
fix live. /me closes

**Closed as completed by jaredhirsch** 2013-08-06 22:55 UTC
Labels: ★★★★★, qa:verified

**Comment by edr67** [comment] 2013-08-07 12:29
user is back up and logging in! thanks!
