### ISSUE TITLE
OpenSans font at weight 300 malrenders on Windows

### ISSUE THREAD

**Issue by Pomax** [mozilla/persona#2448] opened 2012-09-07 19:55 UTC
It would appear that windows 7 doesn't quite know how to deal with rendering the Open Sans font that is used for browserid at a font-weight 300, based on the weight-400 font @font-face rule. On windows 7 the browserid login and website are hard to read in both Firefox and Chrome, although changing the weight from 300 to 400 makes it properly readable again, so it might just be a matter of having the CSS load the weight-300 version in addition to the weight-400 version to fix

**Comment by callahad** [comment] 2012-09-07 20:06
Hi Pomax, thanks for letting us know! I'm closing this as a dupe of #1856; a fix is staged to roll out with the next deploy.

**Closed as completed by callahad** 2012-09-07 20:06 UTC
Labels: qa:verified
