### ISSUE TITLE
[b2g] unable to sign into prod marketplace with firefoxos.anosrep.org pref'd

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3645] opened 2013-07-10 23:49 UTC
1. set pref: firefoxos.anosrep.org on b2g phone
2. open prod marketplace and click the gear
3. click sign in
4. try using any account (i'm using mozilla.com)

actual: goes into secondary flow, but upon completion, i get a error screen
Action: getting assertion
Network Info: /wsapi/cert_key

**Comment by shane-tomlinson** [comment] 2013-07-11 09:44
90% certain this is because the prod marketplace will use a forceIssuer of firefoxos.persona.org or login.persona.org instead of firefoxos.anosrep.org or login.anosrep.org. Is there a stage marketplace that points to stage persona?

**Comment by jedp** [comment] 2013-07-11 14:50
The plan is to have a separate marketplace prod (not stage) pointed at persona stage.  Work to set that up will begin after July 15.  (Note that marketplace's release schedule is more frequent than persona's, so setting up a marketplace prod only makes sense.)

Here's a bug for it: https://bugzilla.mozilla.org/show_bug.cgi?id=884606

Until that's set up, we won't be able to test persona stage with marketplace.

But either way, the expected behavior is that signing into marketplace with anosrep should not work.   So I'll close this issue.

**Closed as completed by jedp** 2013-07-11 14:50 UTC
