### ISSUE TITLE
Persona doesn't work on Chrome / iOS 6 

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3753] opened 2013-08-06 15:50 UTC
Pascal Finette reports in [bug 901745](https://bugzilla.mozilla.org/show_bug.cgi?id=901745):

Latest version of Chrome and iOS (both stable) as of today.

Error: When tapping on "Log in with Persona" a new window opens which reads: "Error: Please close this window an try again."

If you do this (i.e. follow the instructions) it still doesn't work (the Persona button becomes completely unresponsive).

**Comment by edwindotcom** [comment] 2013-08-06 16:21
I'll attempt to repro

**Comment by callahad** [comment] 2013-08-06 16:32
This is the known issue that alternative browsers on iOS don't work because they break window.open, right?

Suggest closing as dupe.

**Comment by edwindotcom** [comment] 2013-08-06 16:37
closing as dupe of https://github.com/mozilla/browserid/issues/2034 - I've update the bugzilla bug with notes about why and that we want to provide improved messaging soon.

**Closed as completed by edwindotcom** 2013-08-06 16:37 UTC

**Comment by jedp** [comment] 2013-08-06 16:45
Ah, yes.  Sorry about the dupe.

**Comment by shane-tomlinson** [comment] 2013-08-12 15:09
@edmoz - we are doing something better than messaging, we are making it work for RPs that use the .watch API.
