### ISSUE TITLE
Inactive "Sign in" button not visibly disabled on sign up for new account

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#2107] opened 2012-07-19 16:23 UTC
- go to persona.org
- choose "sign in"
- enter a new secondary email
- click the blue "sign in" button below the email
- the blue button flashes gray for a moment
- I am prompted to "sign up" and the "sign in" button turns blue again
- clicking the "sign in" button has no action

Since I'm required to sign up for a new password at this point, I would expect the blue "sign in" button to remain gray to signify that it is disabled.

**Comment by skinny97214** [comment] 2012-07-19 16:39
Dupe of #1886

**Closed as completed by skinny97214** 2012-07-19 16:39 UTC
Labels: qa:verified

**Comment by jedp** [comment] 2012-07-19 16:42
Aha - thanks.  I figured there had to already be a ticket for it.  Sorry my searching didn't find it!
