### ISSUE TITLE
B2G: unable to sign in with mozilla.com account on simulator

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/persona#4013] opened 2013-11-06 19:02 UTC
STR:
1. Open Tools > App Manager (in FF nightly) (might have to install [simulator](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Using_the_App_Manager#Simulator))
2. Add `http://download.atlasct.com/evernav/manifest.webapp` as a hosted app
3. Start the simulator, then Evernav
4. Go through sign in flow

Expected:
Signed in

Actual:
![screen shot 2013-11-06 at 10 57 24 am](https://f.cloud.github.com/assets/1823839/1485499/ee5d5f9a-4715-11e3-9939-7f78da01b2e7.png)

**Comment by nickdesaulniers** [comment] 2013-11-06 19:13
Fun fact, this doesn't seem broken in the old (deprecated) Simulator.

**Comment by callahad** [comment] 2013-11-07 17:37
Looks like an upstream issue with FxOS -- @jedp, any idea what's up?

@nickdesaulniers Can you reproduce this on other hosted applications?

**Comment by callahad** [comment] 2013-11-07 17:37
(Tagging as 5-star; jed, feel free to re-triage)

**Comment by edwindotcom** [comment] 2013-11-07 17:49
I can sign in with non-mozilla addresses, such as user@mockMyId.com.  This issue is specific with user@mozilla.com which tries to use mozilla as a primary.  This could be a vinz clortho issue.

**Comment by edwindotcom** [comment] 2013-11-07 18:23
I was able to sign in with user@mozilla.com on Inari 1.3 via 123done.org.  I believe this issue is simulator only.  I'm updating the title to refect this

**Comment by seanmonstar** [comment] 2014-03-02 19:29
Sounds like it was a bug in the simulator? Anyway, 5-star shouldn't be open this long. Closing. Feel free to throw stuff at me if I'm wrong.

**Closed as completed by seanmonstar** 2014-03-02 19:29 UTC
Labels: ★★★★★, FxOS
