### ISSUE TITLE
'is this your computer' screen not being shown for train-2014.04.16

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#4125] opened 2014-04-25 21:30 UTC
@bobsilverberg saw this with saucelabs automation in stage where the new train was deployed this week.

**Comment by jaredhirsch** [comment] 2014-04-28 00:02
This is weird, I'm having trouble consistently generating this screen on current production. The sixty-second wait doesn't seem to be enough. @jrgm, have you had a chance to poke at this a bit?

I'm also noticing extreme sluggishness in the current production dialog--I thought that was due to something in the latest train, but I guess not :-\

**Comment by bobsilverberg** [comment] 2014-04-28 00:30
I'm pretty sure that I've been able to reproduce this in production as well. I was mistaken about our tests being against production, but I tested it against the live oneanddone.mozilla.org and saw the same issue.

**Comment by jaredhirsch** [comment] 2014-04-28 02:26
@bobsilverberg thanks for the info! Yeah, I am seeing the 'is this your computer' screen, but it's oddly inconsistent. At least it seems like this wasn't introduced by the latest (2014.04.16) train.

**Comment by jrgm** [comment] 2014-04-28 03:39
Hmm, I wrote this comment on Friday night, but apparently didn't hit the submit button (I guess):

---

git bisect says that this entered branch `dev` in https://github.com/shane-tomlinson/browserid/commit/dfac0c6a1121804c67ea280e2d3af51af659744f which is part of https://github.com/mozilla/persona/pull/3997. I can see how that makes sense w.r.t. this part of it: https://github.com/mozilla/persona/commit/b374b745e8414921f287ed1b92f4da2703b20f84#diff-694330ebb4760e7f8017fc0725808474L360

STR:
1. check out build and `npm install && npm start`
2. start with a test profile with no history/localStorage/cookies/etc. and go to 
3. click on 'Get an assertion' and use a user that already exists
4. After completing that, inspect localStorage.usersComputer for origin http://127.0.0.1:10001/

Expected: it has a value with state: "seen"
Actual: it has a default value of "{}"

---

**Comment by jaredhirsch** [comment] 2014-04-28 15:39
Ah yeah, the context refactor. Too bad we landed some huge patches the week before priorities changed :-\

Nice sleuthing @jrgm!

I guess this doesn't break anything for users, and it's been live for a long time in production, so we can keep moving with the latest release?

**Comment by jaredhirsch** [comment] 2014-04-29 04:12
While chatting on IRC, @jrgm pointed out that this isn't definitively proven to be out in production.

The big question is whether the 'seen' param is set in localstorage (under the 'usersComputer' key) after logging in.

STR this screen **should** be:  start with with clean profile, sign in as known user, dialog dismisses, wait 60 seconds, then pop and sign in again. Or you can check for the 'seen' param in localstorage right after logging in.

Right now, it seems to work fine for me on stage and production, I'll poke at it a bit more and try to repro the bug consistently.

**Comment by jaredhirsch** [comment] 2014-05-10 04:11
@jrgm - I cannot repro this error with a clean profile on stage or prod in Chrome or FF. I'm consistently getting state:seen under usersComputer. Would you mind giving it a try?

**Comment by bobsilverberg** [comment] 2014-05-12 16:23
The test in question, that expects the 'is this your computer' screen is still failing for us in our CI against the staging server.

**Comment by callahad** [comment] 2014-10-31 21:48
I can't reproduce this error. The "is this your computer" screen shows up as expected in production.

Closing :(. Please comment if you can repro this manually.

**Closed as completed by callahad** 2014-10-31 21:48 UTC
Labels: ★★★★

**Comment by bobsilverberg** [comment] 2014-11-24 18:41
@callahad The problem we are having is in staging, not production. Our tests are still failing on this, and I was able to manually reproduce in staging via the http://beta.123done.org/ site.
