### ISSUE TITLE
BigTent broken on login.persona.org/signin?

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3225] opened 2013-04-10 18:40 UTC
Via https://news.ycombinator.com/item?id=5525606

> The login on the Persona site (https://login.persona.org/signin) doesn't seem to work for me, using my Yahoo account. It pops up the Window, I login to Yahoo, that little window goes away, then ... nothing else happens. If I click "verify" again, the little window pops up momentarily and then just goes away. Is it supposed to actually do something, or was that the whole demonstration?

**Comment by callahad** [comment] 2013-04-10 18:41
I'd be particularly interested in sixbrx's OS, browser and version, and whether or not 123done.org fails similarly.

**Comment by lloyd** [comment] 2013-04-10 18:45
yes please.  I really want to understand this.  please drop into our irc room (#identity on irc.mozilla.org)and we can work through it live.

Outside of that you could try going to yahoo.com, logging out, and then trying to log in.

Whatever the workaround, we want to understand the cause.

**Comment by callahad** [comment] 2013-04-10 18:59
It _sounds like_ provisioning is happening successfully, but the transition to the account manager isn't happening.

I suspect logging into a normal RP, like 123done.org, would work for sixbrx.

**Comment by callahad** [comment] 2013-04-11 17:11
We should try mixed case logins...

**Comment by callahad** [comment] 2013-04-11 17:13
@lloyd reprod successfully with a mixed-case user part.

**Comment by lloyd** [comment] 2013-04-11 17:14
confirmed, exact behavior can be caused by inputting a mixed case user part of a yahoo email.

**Comment by shane-tomlinson** [comment] 2013-04-22 12:42
This page is now gone, the dialog is used for signing in everywhere. Closing is no longer possible to see this.

**Closed as completed by shane-tomlinson** 2013-04-22 12:42 UTC
Labels: ★★★★
