### ISSUE TITLE
mozilla.com Persona IDP - upgrade message says "undefined"

### ISSUE THREAD

**Issue by gerv** [mozilla/persona#3679] opened 2013-07-18 09:08 UTC
I attempted to sign into air.mozilla.org using my gerv@mozilla.com account.

The first thing I got was:

" Your mozilla.com account has been upgraded to work even better with Persona. We will redirect you to mozilla.com.

Once you verify your account there, you will be signed in to undefined."

There seems to be a problem at the end there. :-)

Gerv

**Comment by shane-tomlinson** [comment] 2013-07-18 11:20
Thanks @gerv. I'm surprised there is not an open bug already, we knew about this.

Labeling 5\* since this is a regression. We can change it if need be.

**Comment by callahad** [comment] 2013-07-18 12:37
AFAIK this is fixed, and the fix goes into production today when we do the deployment.

Suggest we close, since this is resolved in stage.

**Comment by callahad** [comment] 2013-07-18 12:37
(We delayed Gmail by a few days to wait for that fix to land, FWIW)

**Comment by shane-tomlinson** [comment] 2013-07-18 15:50
Fantastic. Closing as fixed, no longer 5*. Thanks @callahad

**Closed as completed by shane-tomlinson** 2013-07-18 15:50 UTC
Labels: ★★★★★, area:dialog
