### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#2292] opened 2012-08-15 06:01 UTC
I get automated emails when JS chokes the cat on my site. It doesn't give a huge amount of information, but what I'm seeing is this below. I'm hoping you're testing with that browser?

```
{
  "message" : "Permission denied",
  "script" : "https://browserid.org/include.js",
  "linenumber" : 8,
  "userAgent" : "Mozilla/5.0 (compatible; MSIE 9.0; AOL 9.7; AOLBuild 4343.19; Windows NT 6.0; Trident/5.0; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C)"
}
```

**Comment by shane-tomlinson** [comment] 2012-08-15 08:26
@lookfirst - Thanks for the report!  We test very regularly on IE9, though not in an AOL specific build.  Can you give more information about what site you are using, what your browser settings are, whether the site in question has CSP enabled (https://developer.mozilla.org/en-US/docs/Security/CSP/Introducing_Content_Security_Policy), whether the site in question is in standards or quirks mode, whether your browser is using standards mode or has been manually forced into quirks mode using the dev toos?  Any information we can get helps find the root cause.

**Comment by lookfirst** [comment] 2012-08-15 16:17
Hey Shane, I gave you all the information I have. This is an automated report that I get when people hit my website.

We do not have CSP enabled and we are in standards mode.

**Comment by jrgm** [comment] 2012-08-16 20:33
@lookfirst is it always (or the 90% case) the same error message (approximately)?

Also, is it that user-agent (AOL) or does it vary? Any other UA commonly showing this?

**Comment by jrgm** [comment] 2012-08-16 22:21
I downloaded http://daol.aol.com/software/aoldesktop97/ on Windows Vista and installed it. 

1) When I go to dev.123done.org, there is a warning icon displayed in the bottom right corner of the browser window. It says: "P3P Privacy Report" - Site: https://login.dev.anosrep.org/communication_iframe, Cookies: Blocked

2) Do Edit->BrowserSettings and click on Internet Explorer Settings. On Advanced tab, uncheck disable script debugging and check "Display a notification about every script error". Restart AOL.

3) On dev.123done.org, click Sign In. No errors reported but the dialog if horked (of course given (1)).

4) Load http://myfavoritebeer.org and click Sign In. Dialog is again busted (of course). Close the dialog window and then close the browser window and I get a javascript error dialog with the same message as in the initial comment in this issue.

**Comment by shane-tomlinson** [comment] 2012-08-17 08:26
The revenge of #2183.  A new issue to actually create P3P headers is filed under #2340

**Comment by shane-tomlinson** [comment] 2013-06-12 10:18
@lookfirst - If you still have the same browser, could you give this a try on dev.123done.org to see if this problem still manifests? We have added P3P headers, so this problem may be resolved.

**Comment by lookfirst** [comment] 2013-06-12 14:07
@shane-tomlinson I haven't seen this error in ages. That said, I stopped watching 3rd party script errors, so that may be the reason why. ;-)

**Comment by jrgm** [comment] 2013-07-09 04:10
@lookfirst I'm going to speculatively close this issue. If you see something again, feel free to reopen this issue.

**Closed as completed by jrgm** 2013-07-09 04:10 UTC
Labels: ★, qa:verified
