### ISSUE TITLE
cannot sign in with @mozilla.com email alias

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/persona#4148] opened 2014-06-12 20:09 UTC
on a 1.4 device (and 1.3 sim) I can sign in with ndesaulniers@mozilla.com but not nick@mozilla.com.  The authentication flow just stops. cc @callahad

**Comment by callahad** [comment] 2014-06-12 20:17
Closing as dupe of #4144.

Testing on device (123done.org) indicates that ndesaulniers@ is currently configured with a backup password (recently used Marketplace w/forceIssuer), while nick@ is not. This is consistent with the findings in #4144.

**Closed as completed** 2014-06-12 20:24 UTC
