### ISSUE TITLE
[B2G][Marketplace] Text in marketplace persona sign in page is clipped

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#4156] opened 2014-06-24 19:05 UTC
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1027968

STR
1) Launch Marketplace app.
2) Tap on 'Settings' gear icon.
3) Tap on 'Sign In

Observed: The text to ask user to enter email address is clipped "Sign in to marketplace.firefox.com with...". Please see attached scrennshot.
Expected: The text should ask to enter email address.

The issue is reproduced on version 2.0
Gecko: f6c59193a0102d1b2ffb136b5d1d42fd30f93446
Gaia: 5b1fdc6000d35962769e789b924b24e166a27759

**Comment by callahad** [comment] 2014-11-09 00:20
Closing as a duplicate of #3828, which we need to revisit soon.

**Closed as completed** 2014-11-09 00:21 UTC
