### ISSUE TITLE
No email addresses shown in picker

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2090] opened 2012-07-18 14:36 UTC
As per this blog post (scroll down to the section titled "A Minor Bug") http://www.opine.me/mozilla-persona-browserid-is-a-step-in-the-wrong-direction/

"I ran across a minor bug while trying to collect screenshots for the blog. At one point I clicked the Login button and I was presented with the following screen:

Screenshot: http://www.opine.me/wp-content/uploads/2012/07/Bug-1.png

The Login dialog opened as if an email address should have been listed, but no email was present. Clicking the ‘sign in’ button produced the beautiful Javascript alert() saying “The selected email is invalid or has been deleted.” Very comforting. I’m not exactly sure what went wrong here…"

**Comment by lloyd** [comment] 2012-07-18 16:38
thanks for filing this, @callahad 

I can think of multiple approaches to remove the last email from an account to try to reproduce this..

If you create an account and login in browser A (one account with a single email addy associated), then go to browser B...

...  first, you could try adding that email to a different account, effectively disassociating it with the first, then return to browser A and see what you see.

... second, you could try in browser B removing the email from your account via the management page (I _think_ we've plugged this hole).

@jbonacci | @jrgm - mind having a look at this and trying to repro?

**Comment by jrgm** [comment] 2012-07-18 17:15
I reported this in GH-1472 with STR using 'this is not me' in one browser.

**Comment by lloyd** [comment] 2012-07-19 16:59
this sounds like a dupe @jrgm, please close down if you concur

**Comment by jrgm** [comment] 2012-07-19 21:41
Closing as a dupe of GH-1472 but noting a link to Lloyd's comments above

**Closed as completed by jrgm** 2012-07-19 21:41 UTC
Labels: ★★★, qa:verified
