### ISSUE TITLE
After the user cancels signing into the primary, the buttons from the BID dialog becomes unresponsive

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#967] opened 2012-01-24 16:42 UTC
STR:
1. Launch http://beta.myfavoritebeer.org.
2. Click on the Sign In button.
3. Enter an email address from a primary (eyedee.me). Make sure you are no logged into that primary with the entered email address.
4. Click on the Verify button.
5. When the primary web page opens, click on the Cancel button.

The user is returned to the Sign In dialog with the Cancel and Verify buttons but both buttons are unresponsive.

**Comment by lloyd** [comment] 2012-01-26 17:57
duplicate of GH-983

**Closed as completed** 2012-02-02 14:26 UTC
Labels: qa:verified
