### ISSUE TITLE
[next] button on sign in screen flickers blue/grey/blue

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1886] opened 2012-06-30 14:41 UTC
Once you've clicked the [next] button on the sign in screen for new users, it correctly changes to grey (inactive) for a second, then reverts to blue. It should stay grey.

**Comment by shane-tomlinson** [comment] 2012-07-02 11:19
duplicate of #1898, closing.

**Closed as completed by shane-tomlinson** 2012-07-02 11:19 UTC
Labels: qa:verified
