### ISSUE TITLE
Desktop Chrome on hidpi display shows mobile Persona UI

### ISSUE THREAD

**Issue by lukehutch** [mozilla/persona#4188] opened 2014-08-28 20:59 UTC
If I try logging into a site using Persona on a hidpi display on Chrome on Linux, I am shown the mobile Persona UI, not the desktop UI. On a regular dpi display, I am shown the desktop UI.

**Comment by callahad** [comment] 2014-10-31 19:45
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by callahad** [comment] 2014-10-31 20:06
Whoops, the mass-closing script misfired. Reopening.

Unfortunately, I don't have a HiDPI display to test with. Do you see the same thing in Firefox? Do you know off the top of your head how I could convince Xorg to treat a normal display as if it were HiDPI?

Is it possible that your text zoom is set to greater than 100%?

**Comment by callahad** [comment] 2014-11-09 00:32
I can't successfully simulate HiDPI on Linux, and I can't reproduce this bug on HiDPI OS X.

Since this seems to be specific to Chrome + Linux, and since there are still some significant [upstream bugs](https://code.google.com/p/chromium/issues/detail?id=143619), I'm going to close this for now.

If someone else can chime in with a way for us to reproduce this (or a pull request; there's only a single media query in the whole frontend), I'd be happy to review and merge.

**Closed as completed by callahad** 2014-11-09 00:32 UTC
Labels: needinfo, can't reproduce

**Comment by lukehutch** [comment] 2015-01-14 12:53
Sorry for the slow response, I don't seem to get email notifications from github.

Actually you're right, this is a default zoom issue. My default zoom sizes on Chrome are set to 150% or 175%. (This is needed because Chrome on Linux doesn't actually support hidpi displays yet.) If I zoom out, I get the desktop UI again.

So this is a case of the UI not quite fitting into the window, or rather, the window not being big enough for the UI.

Is there a way to read the physical size of the screen, and to make the popup window bigger if needed to show the desktop UI, as long as it still fits on the screen?
