### ISSUE TITLE
BrowserID UI breaks Firefox password manager

### ISSUE THREAD

**Issue by gerv** [mozilla/persona#499] opened 2011-10-27 11:46 UTC
Scenario: I want to log in to a website using BrowserID. I click the button and get the BrowserID popup. It asks me for my email address, in a form containing only one text field. I type a few characters, and Firefox helpfully autocompletes. I pick the right email address and click Next. 

It then fades in a password box, but it's not auto-filled. :-( I know I can trigger auto-fill by going back to the username box and re-selecting my email address from the Firefox-provided dropdown. I try that, but as soon as I do the password box fades out again! Maddening... 

In the end, I open up the Password Manager's big password list and search for the password by hand. <sigh>

Gerv

**Comment by shane-tomlinson** [comment] 2011-11-01 11:00
Duplicate of #314, closing.

**Closed as completed by shane-tomlinson** 2011-11-01 11:00 UTC
Labels: ★★★, qa:verified
