### ISSUE TITLE
The user is not automatically signed in when confirming his sign up from a different browser

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#722] opened 2011-12-07 10:34 UTC
OS: All
Browser: All

STR:
1. Load https://diresworb.org/ in the browser.
2. Click on the "sign up" button.
3. Enter an email in the corresponding text box and click on the "verify email" button.
4. Open the email with the confirmation link in another browser (same or another device/desktop).
5. Click on the confirmation link set a password for the new account.
6. Go back to the first browser and click on the BrowserID button on the upper left side of diresworb.org.

The user should already be signed into his new account but he's not. When clicking on the BrowserID button, the Home page with the Sign Up button is opened instead of the Account Manager.

**Comment by shane-tomlinson** [comment] 2011-12-13 16:25
@jbonacci, @ioanab - this is indeed by design.  Closing.

**Closed as completed by shane-tomlinson** 2011-12-13 16:25 UTC
Labels: qa:verified, qa:needs testcase
