### ISSUE TITLE
[regression] 'Always sign in with this email' doesn't persist login across browser restarts

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#972] opened 2012-01-24 20:45 UTC
This is in the 01.18 train "1df6d4b update changelog with hotfixes into train-2012.01.18, bump rpm version number"
1. Start with a clean/new profile (optional)
2. Go to beta.myfavoritebooze.org
3. Sign in using an existing email address and check the box for 'Always sign in...'
4. Restart browser; return to beta.myfavoritebooze.org

Expected:
- no signin required; you are logged in

Actual:
- signin button shown

Seen on FF9/XP, Chrome16/XP, FF10/OSX, Chrome16/Win7, IE9/Win7

**Comment by shane-tomlinson** [comment] 2012-01-30 09:31
Could not verify this in FF9/OSX, but could in Chrome16/OSX.

The communication_frame is being loaded up and no cookies are being sent.  With no cookies being sent, browserid thinks there is no session.  Without a session, there can be no silent assertion.

All is fine if I run myfavoritebooze locally.

@lloyd - This seems like a problem with cookies, any ideas?

**Comment by lloyd** [comment] 2012-01-31 19:03
in current dev, if you test via 127.0.0.1:10001, first logging in with "allow persistent" enabled, then signing in with "silent" checked, the silent mechanism seems to be working.  will check against that train.

**Comment by lloyd** [comment] 2012-01-31 19:19
this problem can be reproduced locally:
1. check out train-2012.01.18
2. npm install
3. visit http://127.0.0.1:10001
4. click 'allow persistent'
5. click 'get an assertion'
6. reload
7. click 'silent'
8. click 'get an assertion'

notice null is returned.  So this is a regression in train-2012.01.18 that is fixed in dev.

**Comment by lloyd** [comment] 2012-02-01 01:54
I have a fix, it's extremely low risk, will publish shortly.

**Closed as completed** 2012-02-01 02:44 UTC
Labels: ★★★★★, qa:verified, qa:needs testcase

**Comment by jrgm** [comment] 2012-02-01 20:17
Also on winxp/ie8 and android 2.2 stock browser.
