### ISSUE TITLE
Sign in one account, will prompt to select from multiple accounts

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#740] opened 2011-12-10 02:24 UTC
If a user has multiple accounts, and selects "this is not me", they will proceed to sign in email/password into one account, then be presented with an extra screen to choose from multiple accounts

Screenshot explains it better.   Go from left to right.   Affects desktop and mobile.

http://imgur.com/a/4hMyZ/all#0

Repro:
1) go to beta.myfavoritebooze.com and sign into your account.   Verify you have more than one account
2) when prompted to sign in, click "This is not me"
3) pick one of your consolidated emails and sign in + password
4) Verify the next screen prompts to choose from your list of accounts

Expected;
- dont need a prompt to choose from my other accounts.  i already signed in with one of them with password

Actual:
- prompted to choose from all my accounts.

**Comment by shane-tomlinson** [comment] 2011-12-11 00:45
@tonychung - Duplicate of #198.  Closing.

FWIW - I am against the proposed flow because password managers remember autofill the username.

**Closed as completed** 2011-12-11 00:46 UTC
Labels: qa:verified
